### ISSUE TITLE
(Re)implement campaigns?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#100]
Several people in the IEG committee were of the opinion that we should try and get our app to work with Campaigns if possible. Marti suggested that we might consider implementing a feature that allows people running the campaign to select what the current campaign would be, and all pictures submitted to the campaign by users would automatically fall under the selected category. However, she also said that she understands if we can't implement it in this IEG round, but in that case we could consider it for a future project.

What do you think? I recall there was some unused campaign code that we removed as a bugfix, right? Did that code have this functionality in it (I don't seem to recall that it did), or would we be starting from scratch if we wanted to implement this?

**Comment by misaochan** [comment]
Hi @Nicolas_Raoul, any thoughts on this? Sorry for bumping it, but I should probably get back to Marti soon on this. 

Thanks!

**Comment by nicolas-raoul** [comment]
It's surprising that there seemed to be zero interest in campaigns when we removed it, and now it seems to be important to some people.

Hopefully reintroducing it would be as simple as reverting https://github.com/nicolas-raoul/apps-android-commons/pull/24/files and https://github.com/nicolas-raoul/apps-android-commons/pull/26/files

I wanted to remove it because my goal was to have a simple app for everyone, and campaigns seemed to be a gadget unrelated to this goal, a gadget only used by insiders and whose complexity might become a burden. Also, it used to create a "Campaigns" icon in the Android launcher whose purpose and usage was unclear, in addition to being useless for most people.

But if campaigns are an important thing again, and can bring us many new users, then it might be a good thing towards the project's goal. We should identify a person familiar with campaigns who ideally can re-introduce this feature, or at least test it. Old APKs of the app can probably be found, to see what the campaigns feature used to look like.

**Comment by misaochan** [comment]
Thanks Nicolas! I'll ask and see if there is anyone familiar with campaigns whom we can talk to about this.

**Comment by tobias47n9e** [comment]
Another example of a campaign type: http://www.wikilovesearth.bio/

There are fixed areas and within those areas any photo can be submitted. Having the polygons of the biosphere reserves we can easily detect if the person is close or within the polygon. A small notification can remind them to take a picture.

**Comment by misaochan** [comment]
@tobias47n9e that looks really cool!

I wonder if we would need different support for different types of campaigns, or if it would be possible to have a framework that works for all?

Also, does anyone know if there's anyone running campaigns whom we can talk to about potential implementations?

**Comment by tobias47n9e** [comment]
@misaochan I still stink we can handle all campaigns the same. We just have to make the way we handle different types flexible enough. I am still ready to work on the API as soon as we feel that other things have become stable and we can tackle new things.

**Comment by domdomegg** [comment]
Fixed in #2113
