### ISSUE TITLE
Kotlin Debug Error

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1014]
Sometimes I get this error "`Error:Execution failed for task ':app:kaptBetaDebugKotlin'. >` " randomly and can't get rid of it. I tried to revert my commits and nothing solved, so it seems that this is not related with code itself. Sometimes cleaning the project worked, once I changed my working directiry to solve it. @psh , maybe you have some experience about this problem, do you?

**Comment by psh** [comment]
When you see that error and want to know more about the cause, take a look in the `Gradle Console` tab (or re-run on the command line) -- there's something failing in the annotation processing, and Android Studio is swallowing / hiding that error.  Sadly the error reporting from annotation processing is really poor right now.  😢

**Comment by neslihanturan** [comment]
So it must be related with the current state of the code, why it still complaints even if I revert my changes?

**Comment by psh** [comment]
The annotation processor (*kapt*) writes Java source code underneath the `build` folder of the project, so reverting your own changes under `src` wont always clear things up.  Running a `gradle clean` will remove the annotation processor output.  That said, the failure of *kapt* suggests that there's a problem somewhere so it's worth finding out what it was - which is why I suggested looking on the gradle console of Android Studio.

**Comment by neslihanturan** [comment]
Thanks for great explanation @psh , I will look at to root cause.
