### ISSUE TITLE
Release test flavour (which uploads to the test server) to Google Play

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1057]
Most people who want to use the test flavour lack the technical skills to compile the APK.
For instance, most of the Google Code-in high school students (who are currently taking screenshots of the app) would not have enough time to compile an APK.

So, it could be a good idea to release to Google Play the flavour that uploads to beta commons.
We would probably need to remove the WMF's names and logo, though, I am not sure whether flavours can do this.

**Comment by misaochan** [comment]
Do you mean that it will be an entirely different app, like Wikipedia vs Wikipedia Beta?

**Comment by nicolas-raoul** [comment]
Yes, exactly.

**Comment by sivaraam** [comment]
A few questions,
* Is this different from the "beta" version of the app available in an opt-in basis for beta testers?
* Why would you need to remove the WMF's names and logo, anyways?

**Comment by misaochan** [comment]
@nicolas-raoul I'm not sure, honestly... This raises the question of where we will host the 2nd app, since getting a 2nd app onto WMF's Play Store account will not be trivial. If we host it on a different developer account, then that will require additional maintenance I believe. I don't know if the benefits will justify the extra work?

@sivaraam 

> Is this different from the "beta" version of the app available in an opt-in basis for beta testers?

Yes. The test flavour does not upload anything onto the real Commons server. It is solely for testing.

> Why would you need to remove the WMF's names and logo, anyways?

We would need to re-obtain WMF's authorization to use their name and logo for a 2nd app, I believe. The process is not as straightforward as one might think. ;)

**Comment by nicolas-raoul** [comment]
I will close this for now, feel free to reopen if the need arises.
For now people willing to use a flavour should compile it.

**Comment by maskaravivek** [comment]
From the conversation, I gather that the intent is to have the `beta` APKs easily available for download. 

We could have the APKs available in the [releases section on Github](https://github.com/commons-app/apps-android-commons/releases). As of now, our Releases section contains just the `zip` of the source code. 

Travis lets you include APKs in your releases. 

https://docs.travis-ci.com/user/deployment/releases/

Having this would have 2 advantages:
- People who need to access the prod/beta app can simply download from Github releases section
- While making a new release, our testers can download the APK for upgrade testing rather than building it locally.

**Comment by nicolas-raoul** [comment]
I made the question title clearer, it is about the flavour which uploads to the test server.

**Comment by maskaravivek** [comment]
@nicolas-raoul I didn't misunderstand your question. :)

My suggestion was to modify the travis job and publish the artifacts (both `beta` and `prod` variants) to Releases section. 

From `beta` i meant `beta` flavour ie, the flavour which uploads to the test server.

**Comment by nicolas-raoul** [comment]
Oh I see nice! :-)
The main target for this was Google Code-In, I was worried that people would upload many bad pictures, but actually it went fine (the competition just ended) with the real server, so in the future we will keep using the real server.
That means that the main target of this feature has disappeared, so no need to spend too much time on this :-)

**Comment by sivaraam** [comment]
Closing this one assuming it has become irrelevant now. Do feel free to reopen if I misunderstood that.
