### ISSUE TITLE
Add explicit mention of beta server to login screen of beta product flavour

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1058]
We could make it more explicit in the login screen of the beta product flavour that the user is logging in to the beta servers (and that they will need a beta account). 

Rationale: to prevent issues like #1052 (we have had several questions about this), and I sometimes forget myself.

**Comment by neslihanturan** [comment]
Good point @misaochan I also very frequently re-enter username and password accidentally.

**Comment by mithlesh4257** [comment]
Can @neslihanturan , @misaochan  please explain this issue? I'm not getting it?

**Comment by neslihanturan** [comment]
We have product flavors as beta and production. When developer team making tests, we might need to upload several test images and this behavior may violate Commons site upload rules. Thus, we use beta product flavor (switch from build variant window on Android Studio) which make us use beta server, instead of real commons site. 

But we have two different accounts one for real commons site, one for beta (our beta account that Josephine mentioned). Currently, there is no indicator on login screen which tells you which flavor is selected and which account you have to login. This causes confusion sometimes. Thus this issue offers to add some information about beta account to explain. Does it clear now @mithlesh4257 ?

**Comment by mithlesh4257** [comment]
Yes, @neslihanturan.

**Comment by mithlesh4257** [comment]
Hi @neslihanturan , Shall adding one TextView be good to solve this issue mentioning "Use Commons Beta Credentials"?

**Comment by tanvidadu** [comment]
I start working on this .

**Comment by neslihanturan** [comment]
@mithlesh4257 are you still work on this issue? If not @tanvidadu is willing to take. If @mithlesh4257 has an ongoing work already, we should wait for him @tanvidadu .

**Comment by mithlesh4257** [comment]
@tanvidadu you can start working on it :-)
@neslihanturan

**Comment by domdomegg** [comment]
Done in #1102
