### ISSUE TITLE
 Edittext in SingleUploadFragment lacks Material design, No scrolling behaviour and limit on text size in edit text causes content to be cut-off from screen.

### ISSUE THREAD

**Issue by knight-shade** [commons-app/apps-android-commons#1179]
**Summary:** 
1. Image's title and description edit text in SingleUploadFragment lacks Material Design.
2. Lack of scrolling behaviour and text size limit in SingleUploadFragment causes content to be cut-off from screen.
3. There is no text size limit on Image's title and description, is this intentional or should there be appropriate limit on it?

**Steps to reproduce:** 

1. Select a photo to upload.
2. Enter appropriately large text in title and description or change device orientation to landscape.

**Expected behavior:** 

1. Users should be able to scroll vertically in case image's title and description exceeds device's screen size.
2. There maybe be a appropriate limit on image's title and description.

**Observed behavior:** 
No such scrolling behaviour  and limit on image's title and description size exists.

**Screen-shots:** 
![landscape](https://user-images.githubusercontent.com/20313518/36589148-59873528-18b0-11e8-87d0-f711749bf728.png)

![landscapetext](https://user-images.githubusercontent.com/20313518/36589151-59c222a0-18b0-11e8-9860-c3a425ef4bf7.png)

![text](https://user-images.githubusercontent.com/20313518/36589152-59f98ae2-18b0-11e8-81f5-06ead818da66.png)

**I am working on the issue.**

@maskaravivek Can you suggest if any, limit on text size of image's title and description?

**Update**
Issue has been fixed.

**Comment by nicolas-raoul** [comment]
We want to encourage users to write long descriptions.
Anything that makes typing long descriptions easier is good :-)

On Feb 23, 2018 7:18 PM, "Abhishek Poonia" <notifications@github.com> wrote:

*Summary:*

   1. Image's title and description edit text in SingleUploadFragment lacks
   Material Design.
   2. Lack of scrolling behaviour and text size limit in
   SingleUploadFragment causes content to be cut-off from screen.
   3. There is no text size limit on Image's title and description, is this
   intentional or should there be appropriate limit on it?

*Steps to reproduce:*

   1. Select a photo to upload.
   2. Enter appropriately large text in title and description or change
   device orientation to landscape.

*Expected behavior:*

   1. Users should be able to scroll vertically in case image's title and
   description exceeds device's screen size.
   2. There maybe be a appropriate limit on image's title and description.

*Observed behavior:*
No such scrolling behaviour and limit on image's title and description size
exists.

*Screen-shots:*
[image: landscape]
<https://user-images.githubusercontent.com/20313518/36589148-59873528-18b0-11e8-87d0-f711749bf728.png>

[image: landscapetext]
<https://user-images.githubusercontent.com/20313518/36589151-59c222a0-18b0-11e8-9860-c3a425ef4bf7.png>

[image: text]
<https://user-images.githubusercontent.com/20313518/36589152-59f98ae2-18b0-11e8-81f5-06ead818da66.png>

*I am working on the issue.*

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/commons-app/apps-android-commons/issues/1179>, or mute
the thread

**Comment by knight-shade** [comment]
@nicolas-raoul Thank you very much for your input Nicolas, sure.

**Comment by misaochan** [comment]
I think one line should suffice for the title? The title will actually turn into the image's filename on Commons, so I don't think Commons will be very happy with a 50-word title?

Long descriptions are great. :)

**Comment by knight-shade** [comment]
Yup @misaochan , valid point.
