### ISSUE TITLE
Change Toast to snackbars in app.

### ISSUE THREAD

**Issue by ujjwalagrawal17** [commons-app/apps-android-commons#1301]
**Summary:** 

Snack bars look better than toast and disappear when activity is destroyed. 
https://stackoverflow.com/questions/34432339/android-snackbar-vs-toast-usage-and-difference

**Steps to reproduce:** 

Add a utils function in Utils.java

>     public static void showSnackbar(View view, String message) {
>         Snackbar.make(view, message, Snackbar.LENGTH_SHORT).show();
>     }

 **Commons app version:** 

2.6.7-Debug

**Screen-shots:** 

![screenshot_20180313-202042](https://user-images.githubusercontent.com/19607555/37349695-02324d52-26fd-11e8-8099-1bb0b2acc805.png)

**Would you like to work on the issue**
Yes

**Comment by knight-shade** [comment]
@ujjwalagrawal17 Seems easy though, but you will need to take care of edge cases. Eg. As of now, the app shows a toast for each image which it could not cache (error in caching image), leading to number of toasts equal to the number of images failed to cache. You should figure out how to get past this issue, since showing 20 or merely 6 toasts continuously will definitely not a good UX.
