### ISSUE TITLE
Introducing a brief explanation of image license 

### ISSUE THREAD

**Issue by gupta-meghna64** [commons-app/apps-android-commons#1316]
#### Summary
There should be a brief explanation of the licenses of images in the application to prevent the user from randomly choosing any license. 
For example-
There should be an explanation about:
1) CC0
2) Attribution 3.0
3) Attribution-ShareAlike 3.0
4) Attribution 4.0
5) Attribution-ShareAlike 4.0  

#### Commons app version 
Commons 2.6.7

#### Would you like to work on the issue?
Yes!

It would be great if everyone could give their suggestions on how to go about this and what all can be done to make the best fix :)

**Comment by nicolas-raoul** [comment]
How about a (?) link at the right of the selection gadget, that opens a page on our Wiki or https://commons.wikimedia.org/wiki/Commons:First_steps/License_selection in the user's language?

**Comment by gupta-meghna64** [comment]
@nicolas-raoul that sounds great! I'll start working on it :)

**Comment by tanvidadu** [comment]
@gupta-meghna64 I am already working on a class that would fetch a token for url based on the language selected by the user. I can simply add the functionality to fetch the token for this url too. You can continue from there. It will save a lot of effort.

**Comment by gupta-meghna64** [comment]
@nicolas-raoul how do I retrieve the user's language? Should there be an option of selecting the language from a list on clicking info icon or some other way?

**Comment by nicolas-raoul** [comment]
@gupta-meghna64 How about just something like Locale.getDefault().getLanguage();?
Then I think a mapping to the relevant URLs would be the easiest, with English as the default.

**Comment by gupta-meghna64** [comment]
That sounds like a great idea @nicolas-raoul 
I'll start working on it as soon as possible :)

**Comment by tanvidadu** [comment]
I will start working on this issue as a part of #274

**Comment by misaochan** [comment]
@tanvidadu Sounds good. :)

**Comment by nicolas-raoul** [comment]
After thinking more about this, I believe that license choice is important enough to have its own activity, which would explain each license with proper sentences.

I believe the best would be to do like OpenArchive's app which, rather than asking for a license, asks the user what permissions they agree to let:
https://play.google.com/store/apps/details?id=net.opendasharchive.openarchive.release
![screenshot from 2018-06-11 19-44-27](https://user-images.githubusercontent.com/99590/41227542-31fa6e6c-6db0-11e8-9a55-79b0b8842147.png)
(The choices would be a bit different, as all Commons licenses allow for commercial reuse)
Upon selection it could show show the matching license's name and an explanation about it.
