### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by devaar100** [commons-app/apps-android-commons#1330]
**Summary:** 
A splash screen when the app commences may help provide a smoother transition to the primary screen for a logged in user and to the login screen as well

**Observed behavior:** 
The app begins with a blank screen and delay to abruptly switching to the main screen

**Comments:** 
The splash screen can also be used to provide buttons for maybe making a donation to the app and other concerns from time to time

**Would you like to work on the issue?**
I would love to work on this issue

**Comment by nicolas-raoul** [comment]
Relevant discussion: https://ux.stackexchange.com/questions/50363/why-have-a-splash-screen-and-best-practices-for-native-app

**Comment by devaar100** [comment]
@nicolas-raoul thanks for the discussion url 

While trying the app on 2 devices I experienced a slight delay while opening the app so going by the discussion on the mentioned stackexchange discussion a splash screen to hide the delay with simple launcher icon in centre or a background image similar to first screen might help

**Comment by psh** [comment]
Rather than add a splash screen, perhaps we should address the _root cause_ and look at _why_ the app is slow starting or we see a black screen?

**Comment by Mansi449** [comment]
@devaar100 I would like to fix this issue.

**Comment by devaar100** [comment]
@Mansi449 I want to work on this myself
The splash screen can be used as an opportunity to hide the contributions loading time a bit as well

**Comment by psh** [comment]
A splash screen would be the main entry point to the app. This would be followed by the login screen and then the main contribution screen. If you are complaining that loading contributions is slow, the splash screen will not help. The login screen is quick to load so the splash screen served no purpose.

The contribution screen is big & complex. It doesn't have a persistent model backing it. It does it's own data loading. The splash screen sounds simple on the surface but really means tackling some complex code.

Where is the actual slowdown? Have you analysed the root cause?  Can you help the problem of slow load times by optimization of the code that exists?

**Comment by devaar100** [comment]
The main reason for suggesting splash screen was to hide some loading time while the first 3-4 images visible on the contribution fragment were loaded

**Comment by nicolas-raoul** [comment]
Good news: the app starts super fast these days. 🙂
