### ISSUE TITLE
Unable to get provider [ ModificationsContentProvider ]

### ISSUE THREAD

**Issue by wailbabou** [commons-app/apps-android-commons#1340]
I'm using **directNearbyUploadsNew** branch
with sdk 19 , after installing the application and lunch it , it crush with this error : 
`Unable to get provider ModificationsContentProvider `
After searching i find this : 
[StackOverFlow question ](https://stackoverflow.com/questions/37312103/unable-to-get-provider-com-google-firebase-provider-firebaseinitprovider)

After using Application instead of MultiDexApplication in `CommonsApplication` class , and adding `    compile 'com.android.support:multidex:1.0.3'` in gradle dependencies 
the error is gone 
**Steps to reproduce:** 
- build and install the app in a device with sdk 19

**Device and Android version:** 
SDK 19 ( emulator )

 **Commons app version:** 
2.6.7-debug-directNearbyUploadsNews

**Comment by neslihanturan** [comment]
Yes, this one was expected. The error used to exist in master branch too, but it is solved. However, dNUnew branch doesn't have the fix yet. We decided not to add since we are about to merge that branch to master very soon:) 

You can add this code before testing to solve crash at least, this is how I do, https://github.com/commons-app/apps-android-commons/pull/1237/files

**Comment by wailbabou** [comment]
it was the same one that i used to lunch it :) , thank you
