### ISSUE TITLE
Categories is not shown when user look at image properties for the first time (immediately after saving)

### ISSUE THREAD

**Issue by Yahhi** [commons-app/apps-android-commons#1355]
**Summary:** 

When the user adds image and then sees image properties no category is shown even if the category was selected and save button is clicked.

**Expected behavior:** 

The category should be immediately shown after saved. If the user doesn't see the selected category, he may think that something goes wrong and category selection is not working.

**Observed behavior:** 

No category is shown if the user looks at image properties immediately after saving it.
 
 **Commons app version:** 

2.6.7

**Screen-shots:** 

I have clicked save and then try to see properties of uploaded image
![screenshot_20180323-010644](https://user-images.githubusercontent.com/4613133/37801240-e048605a-2e36-11e8-991c-64a26a9b2af8.jpg)
![screenshot_20180323-010617](https://user-images.githubusercontent.com/4613133/37801241-e06698a4-2e36-11e8-9144-03f2add4f74b.jpg)

**Would you like to work on the issue?**

yes

**Comment by Yahhi** [comment]
The same issue is already mentioned at https://github.com/commons-app/apps-android-commons/issues/1290. But the reason for this was not described. I think it happens because when the user clicks "save" system does not wait until successful saving, just adds network request to the queue (as in public void onCategoriesSave(List<String> categories) in ShareActivity. So when the user goes to image info result of the request may not be available yet. But users don't want to know anything about our network and inner work, so I think this situation needs to be solved. There are two possible options^ save categories locally or show some indicator that informs the user that setting category is in progress.

**Comment by misaochan** [comment]
How soon afterwards do you check?

Indeed, categories are submitted afterwards through an edit to the uploaded file. So there can be a delay. Saving categories locally can be an option, but in that case you need to check if remote categories exist and then replace the local categories with them (because the user can add categories through the browser, so the remote copy is the better one to use). 

To be honest I'm not sure if all that work is worth it for the convenience of being able to see categories immediately (instead of 5 minutes later), but if you would like to work on it, please feel free. :)

**Comment by neslihanturan** [comment]
I just uploaded an image and categories are there. This should be solved.
