### ISSUE TITLE
Rotating the screen while logged in redirects the user to the "create an account" page.

### ISSUE THREAD

**Issue by codaphrenic** [commons-app/apps-android-commons#1430]
#### Expected behavior
It is expected that on rotating the screen from portrait to landscape, a user should still be able to go on using the app from the landscape view and not get redirected to create an account when already you have one created and you are logged in to the account.

#### Actual behavior

The app on rotation redirects you back to the **create an account** page even when you are already logged in.

#### How to reproduce
* Download the app from fdroid store
* Scroll through your menu and launch app.
* Sign up with your desired user details
* Log in with these details
* On the user dashboard or homepage, attempt rotating the phone screen from portrait to landscape. You will notice this action redirects you to the **create an account** page.

***

* Device: TECNO-L8Plus 
* Operating system: Android 5.1

* Application: Commons
* version: 2.7.0

#### Recording Of The Bug

<center>
https://youtu.be/n57UzNWdMDE
</center>
 

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fego/rotating-the-screen-while-logged-in-redirects-the-user-to-the-create-an-account-page">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by misaochan** [comment]
Thanks for posting this, @codaphrenic ! It strikes me as very strange. From everything I can see, the user is **not actually using our app** at all, but rather http://commons.m.wikimedia.org (the mobile version of the website). In our app, when logged in, the user is brought to their contributions, not to the "welcome to Commons" page in the video. 

Yet the icon he clicks in his app launcher looks exactly like ours. Is it possible that he launched our app, selected "sign up", and after completing the signup process, he logged in into the webview version of the website instead of our app?

**Comment by misaochan** [comment]
For reference, the login screen of our app looks like this:

![screenshot_20171224-010543](https://user-images.githubusercontent.com/3611199/38468365-d010a220-3b87-11e8-8431-025621f5a317.png)

And the screen you should get upon logging in would look like this:

![screenshot_20170329-175228 1](https://user-images.githubusercontent.com/3611199/38468366-dc7cc7e6-3b87-11e8-9e98-e6b25be45f4b.png)
