### ISSUE TITLE
Include peer review to app

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#1559]
**Summary:** 

As you know, peer review #780 is roughly working. This issue will contain required steps to include it to our master codebase.

- UI: currently we used a viewpager and at each different question whole page swipes which is bad. I think the part of the page that includes question should move on next question, but image should stay still. 
- UI: Refresh button should change. I didn't think on a better UI yet.
- UI: Currently transitions between questions and new image is quite similar. But we have 2 different fuction and their transitions should feel different. First transition is when user answered a question about an image , new question comes. Second transition is whenever user requested another image or completed all questions with previous image, we give another image and start to ask questions from first question. My queestion is swiping is enough for first transition, however it could be better to add a fast forward animation for second transition.
- Compatibility: It would be nice if we can both play with random images and images that we searched for. So, this feature should be usable with images explored on explore feature. We can add them simultaneously. 

What do you suggest?

**Comment by nicolas-raoul** [comment]
I would be in favor of releasing the feature without spending time polishing it because:
- Only a few people will try the feature, I guess.
- Right now there are less than 100 uploads per day, so an inconvenient UI is not a big problem.
- Maybe we will discover some fundamental things that will require us to completely change how peer review works. So the polishing effort would be in vain.

But I believe we must add a mandatory (shown every time, no way to "skip in the future") one-page long text explanation that details:
- what peer review is,
- in case of doubt please skip, only report if you are sure a picture is a violation
- on the opposite, be generous with the "thanks" button
- explanation of copyright violation
- explanation of what is on-topic, off-topic
- This feature is experimental so the UI is not so great, it is a first iteration/proof-of-concept, but feedback is very welcome on Github Issues
I can to to write this text, if you want :-)

**Comment by nicolas-raoul** [comment]
@neslihanturan  By the way, what branch is it in? Would you mind sharing the URL? Thanks :-)

**Comment by neslihanturan** [comment]
Sure @nicolas-raoul : https://github.com/commons-app/apps-android-commons/tree/wikimedia-hackathon-2018

**Comment by misaochan** [comment]
I agree with the steps mentioned by @neslihanturan and @nicolas-raoul - preferably we will polish this a bit before incorporating it in our app. How about we include the polishing as part of our PG 2019 plans?

**Comment by nicolas-raoul** [comment]
Recent uploaded are indeed visible within the app: Tap "Explore", search for "Uploaded with Mobile/Android", tap "Categories", tap "Uploaded with Mobile/Android".

Not sure whether this can benefit Nes' work or this feature in general, though.

![screenshot_20180822-192957](https://user-images.githubusercontent.com/99590/44458884-8be6a100-a642-11e8-9fca-a8a837159921.png)
![screenshot_20180822-193029](https://user-images.githubusercontent.com/99590/44458885-8be6a100-a642-11e8-9dc0-103e0c68a3d0.png)

**Comment by nicolas-raoul** [comment]
I believe this is done? :-)
If I am mistaken, feel free to reopen.
