### ISSUE TITLE
Using branch name tags for Github issues

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#1661]
Our project has simultaneous active development happening on multiple branches. For eg. at the time of creating the issue `2.8-release`, `feedback-gamification`, `browse-commons-via-app` and `gamification` are active. Even the other branches in our repo are not exactly stale and would be merged in due course of time. 

Sometimes it's difficult to figure out which feature branch the issue is referring to. Moreover, external contributors won't have any idea that the issue might be talking about a feature branch. 

Can we have branch name tags mandated for our Github issues? This would also make finding issues for a particular feature branch easy. 

We can have this guideline added in the issue template if others agree to this proposal. :)

**Comment by sivaraam** [comment]
In any case, I suppose it would nice to have a common prefix, like `branch-` for them to distinguish them easily.

**Comment by nicolas-raoul** [comment]
@maskaravivek Yes good idea! I am guilty of submitting many bugs for the `browse-commons-via-app` and referring to it by a different name every time because I can't remember it.

@sivaraam This is not the topic of this issue, and I don't think having all branches start with `branch-` would add any value.

**Comment by sivaraam** [comment]
> This is not the topic of this issue, and I don't think having all branches start with branch- would add any value.

Seem you understood me. I wasn't proposing all branch names to have a common prefix like `branch-` (that's ridiculous). I was proposing all the branch related tags/labels that are about to be created to have a common prefix such as `branch-` so that it's easier to distinguish those tags easier.

Maybe you were thinking of giving it a different colour, but I thought a common prefix for the tags would help distinguishing them even explicitly. BTW, that was a suggestion IMHO.

**Comment by nicolas-raoul** [comment]
Sorry I misunderstood the whole issue!
I guess `branch-2.8-release` is not needed as we already have `pre-release`?
I created two branch-* labels for the main branches we have currently.

**Comment by maskaravivek** [comment]
@misaochan Yes, I was referring to having tags. Having them in the body/title will be difficult to search.

**Comment by misaochan** [comment]
I'm good with the `branch-*` labels, and it's a good idea to have that as a prefix IMO :). I would request all collaborators to help keep on top of these labels and remove them when we are done with the branches though, to prevent cluttering.

**Comment by maskaravivek** [comment]
Closing this issue as we have already reached a consensus and have started following the branch tag convention. :)
