### ISSUE TITLE
Uploading any photo fails

### ISSUE THREAD

**Issue by PeterFisk** [commons-app/apps-android-commons#1740]
**Summary:** 

When trying to upload any photo in the Wikimedia Commons app, the upload fails.

**Steps to reproduce:** 

All uploads fails, regardless of which method I use: selecting a photo directly in the app, or browsing to an image and then share it via the app.
I tried resetting the device, and loging out and in again, with no luck.

After installing the beta version, it works.

**Add System logs:**

See attached file.

**Device and Android version:** 
Galaxy S9 (SM-G960F, Norwegian), Android 8.0.0, Samsung Experience 9.0, security patch level: june, 1st 2018.

 
 **Commons app version:** 
2.7.2 (not beta)

**Screen-shots:** 

**Would you like to work on the issue?**

I can't work on the issue myself.
[logs3.txt](https://github.com/commons-app/apps-android-commons/files/2219308/logs3.txt)

**Comment by misaochan** [comment]
Thanks for the report, @PeterFisk . We are currently tracking this at #1485 , but all new information is helpful.

> After installing the beta version, it works.

This is interesting, as the current beta and production version are both 2.7.2 - i.e. there is no code difference between the two. My best guess is that it isn't the beta version that helped, but rather the **reinstallation** of the app that helped. Did you ever try reinstalling the app before trying the beta version?

Also, do you remember exactly when your uploads started failing?

Thanks so much!

**Comment by PeterFisk** [comment]
No, I joined the beta program, then reinstalled the app.
My latest successful upload was on june 27th. After that, all uploads
failed until I reinstalled today.

PeterFisk

Den man. 23. jul. 2018, 16:38 skrev Josephine Lim <notifications@github.com

**Comment by nicolas-raoul** [comment]
@misaochan The log above does not contain "mustbeloggedin" so I believe it is a different problem.
How about releasing 2.8 with HTTP debug enabled to beta (or alpha)?

**Comment by misaochan** [comment]
Thanks again @PeterFisk , this was very helpful!

@nicolas-raoul I believe the reason why the log above doesn't contain "mustbeloggedin" is because of #1489 , unfortunately, as it was probably generated via the "Send logs" setting. As you can see, the log doesn't contain any of our other usual debug messages either.

I am not against doing a release with HTTP debug enabled, but do you think it will be useful with the current state of our "send logs" feature?

**Comment by nicolas-raoul** [comment]
Logcat can also be relatively easily obtained with a USB cable and a computer, without downloading the whole SDK: https://softwarerecs.stackexchange.com/a/51226/140

**Comment by misaochan** [comment]
Sounds good. I'll create a closed testing alpha track. Should we go with using the "Only users in the specified Google Groups or Google+ Communities can join your beta programme" method? Would be easier than manually maintaining a list. We can create a Google group for alpha testing and invite people to sign up?

**Comment by nicolas-raoul** [comment]
What is wrong with allowing anyone to subscribe to the alphas? :-)

**Comment by misaochan** [comment]
I don't think there is an option to do that unfortunately. Alpha is automatically a closed track, the only 2 options are "google groups" and "lists".

**Comment by nicolas-raoul** [comment]
Oh, interesting!
Creating a Google Group (and making that Google Group joinable without confirmation from us) sounds to me like the best then :-)

**Comment by misaochan** [comment]
Okay, I've uploaded the http logging version to alpha. Apparently it takes just as long as beta/production for the release to be live, so probably check in several hours.

I am actually a bit confused about how alpha works. The opt-in URL given to me for alpha was the same as that for beta - https://play.google.com/apps/testing/fr.free.nrw.commons . However, there is the additional requirement of the user being part of the commons-app-alpha-testing google group. So I'm guessing that the way this works is that when someone opts in via the opt-in URL, if they are in that google group, they will be assigned to the alpha track, and otherwise they will be assigned to the beta track.

But what happens when I increment the version number again for the next beta release and release that one in beta? Will the people in the alpha testing google group get the new beta version, or will they be stuck in the old alpha version? They will have to leave the group to get access to 2.8 I guess?

**Comment by nicolas-raoul** [comment]
When I was a beta user I was getting whatever version was the most recent within beta+prod.
I guess alpha users will get whatever version is the most recent within alpha+beta+prod? I hope :-)

**Comment by VojtechDostal** [comment]
Hi, I just logged off from my Wikimedia account on Wikipedia and then logged back in there. This seems to have caused the bug to reappear - now I cannot upload any picture. Logging off and back in *in the app* did not help.

PS: I am using 2FA.

**Comment by misaochan** [comment]
@VojtechDostal Sorry, yes, we didn't seem to have much luck with solving the issue (see #1485 ). By the middle of this week I guess we may have to make a decision to revert all the changes we made to the auth system (including 2fa) if we still haven't managed to solve things, since the problems that this issue is causing to users outweighs the benefit of 2fa logins, and users have already been inconvenienced for over a month. Hopefully this will not be needed, but if we do that we will document everything we tried and hopefully pick it up again at a later date. @maskaravivek

**Comment by misaochan** [comment]
We decided to do a 2FA revert in v2.8 to solve this issue (for more details on how we arrived at that decision, please see https://github.com/commons-app/apps-android-commons/issues/1485#issuecomment-409519008 ). I will close this issue now due to duplication, please feel free to provide future input at #1485 . Thank you so much everyone for your reports and your patience!
