### ISSUE TITLE
"Too dark" for picture with black background

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1767]
I got the "too dark" message:

![screenshot_20180725-135401](https://user-images.githubusercontent.com/99590/43393343-a7bab33a-9431-11e8-9840-c2425fdbb648.png)

... for this picture:

![_at_ _](https://user-images.githubusercontent.com/99590/43393370-c6806e40-9431-11e8-9950-05cf9f18694c.jpg)

I don't remember the specifics of the algorithm, but maybe it divides the picture into zones, and focused on the top part of the picture too much?
The algorithm should be improved to allow such pictures where only the background is very dark.

(recent master)

**Comment by Mansi449** [comment]
@nicolas-raoul I went through the algorithm. 
According to the algorithm, the image is first divided into several rectangles.

For each rectangle:
The brightness level/luminance of each pixel in the rectangle is calculated and if it turns out to be less than 50, it is considered to be a dark pixel. If the number of dark pixels is more than 50% of the total number of pixels, then the whole rectangle is termed a dark rectangle. 

After doing this for all the rectangles, if the number of dark rectangles turns out to be more than 50% of the total number of rectangles then the whole image is considered to be a dark image.

With the current algorithm in use, I am unable to find out a way to make the algorithm differentiate between the foreground and background of an image?
Could you please throw some light on what modifications need to be made?

**Comment by nicolas-raoul** [comment]
Let's consider these perfectly valid images:
![fake_starry_night_ 3353022576](https://user-images.githubusercontent.com/99590/43523774-6aa715a8-95d8-11e8-9da2-230d4e4d41cf.jpg)

![starry_night_ unsplash 1](https://user-images.githubusercontent.com/99590/43523809-855c2a00-95d8-11e8-8efc-a60fe1dfa906.jpg)

How about this algorithm:
1. Count how many pixels have high brightness
2. Count how many pixels have medium brightness
3. If numberOfBrightPixels is below 3% AND numberOfMediumBrightnessPixels is below 30%, then the picture is too dark.

Note: Some pictures are dark but only human judgement can tell they are good, for instance the one below. Maybe the app should still say that it is too dark. It is acceptable to have false positives.
![1200px-yosemite_night_elcapitan_climbers](https://user-images.githubusercontent.com/99590/43524169-85687b60-95d9-11e8-971d-13e492b0a0c7.jpg)

**Comment by Mansi449** [comment]
Thanks for such a good explanation!  It seems to be a nice algorithm.
I wanted to know that the image has to be divided into rectangles or not.

**Comment by nicolas-raoul** [comment]
No need to divide, I think. It does not matter that a part of the image is completely black (like in my food image above).

**Comment by Mansi449** [comment]
Okay, right. I would like to work on this issue and implement the algorithm.
