### ISSUE TITLE
Provide a selectable list of reasons when requesting deletion of a file

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#1768]
**Summary:** 

The app allows the user to request the deletion of a file they uploaded from the Media details screen. The user has to provide a reason for deletion in free form text there. I suggest providing a selectable list of typical reasons to ease input and help other users to understand.

The most typical reason would probably be "_new, unused, upload by myself_" if the file has been uploaded recently enough. (generally, within 7 days since upload, the reason would be accepted by Commons administrators by default) For older photos, something along the lines of "_unused and personal photo, out of scope_" might be a good alternative.

I quickly checked https://commons.wikimedia.org/wiki/Special:NewPages?namespace=4&tagfilter=mobile+app+edit&username=&size-mode=min&size= which shows a list of deletion requests created using the app. The results of the requests can be classified as below:

* deleted (request accepted) - 23
* kept (request rejected) - 8
* undecided - 18

So at least a majority of them are accepted, which is good, but I believe we want to have less rejected cases.

The option of free text input should still be available, and ideally the selected reason should be editable.

 **Commons app version:** 

master version.

**Comment by nicolas-raoul** [comment]
Good idea!

Ideally the messages should be clearly understandable by both the user and the administrators.
While "new, unused, upload by myself" and "unused and personal photo, out of scope" would be crystal-clear to an administrator, new users (people who have never read a Mediawiki talk page in their life) would not understand what it means. They would understand things like "I uploaded it by mistake", "I did not know it would be publicly visible", "I realized it is bad for my privacy", or "I changed my mind, I don't want it to be publicly visible anymore" etc (we would have to brainstorm these sentences a bit).

The app could then concatenate to this text other information extracted automatically:
- "Uploaded by myself", always true since the button only appears for one's own uploads
- "Uploaded X days ago", easily calculable
- "Used in Y articles", I am sure there is an API to find out this number

So, the final text could look like: "I changed my mind, I don't want it to be publicly visible anymore. Uploaded by myself 3 days ago, used in 1 article."

**Comment by tanvidadu** [comment]
@nicolas-raoul @whym great addition!
Will like to work on it :) 
I was thinking of adding a spinner in alert allowing the user to select the appropriate reason and then adding the deatils mentioned above.

**Comment by whym** [comment]
I agree with Nicolas in that the list should be easy to understand. Considering multiple reasons may apply, perhaps it can be a list of simple questions and (multi-select) checkboxes, rather than one-select list? e.g.:

    Why do you want to delete it? Check all that apply.
    
    [] I mistakenly upload it.
    [] It reveals something private.
    [] It depicts nothing interesting/educational.
    [] (hidden, automatically decided:) It been recently uploaded.
    [] (hidden, automatically decided:) It has not been used on any article.
    [ enter other reasons in free text here ]

(Can they fit in a dialog, or maybe should it be a full-screen fragment instead?)

The list should be i18ned to the user using strings.xml, but when creating a deletion request page, the app could paste the selected ones in English (along with the user's language). 

That said, I don't mean to make it too complicated, and as a start point, it would be okay to cover some of the most typical cases.
