### ISSUE TITLE
Panorama thumbnail is pixelized

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#1815]
**Steps to reproduce:** 

1. Scroll featured pictures until you find a very pixelized picture
2. That's it! :-)

All featured pictures are actually high-quality, so it must be possible to generate high-quality thumbnails from them. It might be due to unusual proportions of the picture, example:

Panorama: https://commons.wikimedia.org/wiki/File:Panorama_vom_Gro%C3%9Fen_Leuchtberg.jpg
Result:
![screenshot_20180705-000514](https://user-images.githubusercontent.com/99590/43880372-0b061322-9be3-11e8-9870-442071efcfa3.png)

Current master

**Comment by neslihanturan** [comment]
2020 update, this issue is still exists.

**Comment by 4D17Y4** [comment]
Can I work on this one?
I can reproduce this on the latest master.

**Comment by nicolas-raoul** [comment]
@4D17Y4 Yes thanks :-)

**Comment by 4D17Y4** [comment]
Hey @nicolas-raoul ,
I've investigated on this issue.
To start with, as we know panoramic images have more length ( horizontal dimension ) as compared to the normal images.
And  to fetch the image from commons media API we have used.
https://github.com/commons-app/apps-android-commons/blob/0d23e65e0fed3272c53a18106215b7ddb9da7cae/app/src/main/java/fr/free/nrw/commons/media/MediaInterface.java#L14-L16

We can notice that we query constant width ( 640 ) for all images.
If we look at the image page on wiki data we can see that panoramic images have very low height for this width ( by the aspect ratio ). As the image returned retains aspect ratio and we try to fit it in a view of fixed height, the image distorts.


For the solution part,
1) We can increase the constant 640 to some reasonable constant so that they are not blurred but this will increase the data usage and time taken to show the image.

2) Other way we can remove that constant and try to query data depending original image dimentions.

3) We can reduce the height of the view to be flexible according to the height of image.


I'd prefer 2 or 3.

Let me know what to go for.

**Comment by nicolas-raoul** [comment]
Inspired by your strategy 2, how about the algorithm below?

1. Run the `iiurlwidth=640` query.
2. If the height of the returned image is below 200 pixels, then run another request with ``iiurlheight=200` (or with a calculated `iiurlwidth` if the API has no `iiurlheight` parameter).

(The value of 200 pixels might need some tuning after testing on different screen sizes etc)

**Comment by 4D17Y4** [comment]
Ive investigated further -

The API does have the parameter `iiurlheight` to get the image of specified height, but we cant query both at the same time, it considers only the first one.

Also, we haven't saved the width or height of the image anywhere, the image info does have the attribute `width` and `height` but they are never initialized/used (always 0).

To change the query parameter depending on the image width, we must change the schema and include the parameter height or width or both and then compare it with the threshold to get a better query result.

should I go ahead with it?

**Comment by nicolas-raoul** [comment]
Yes, I think it is worth it. Thanks!

**Comment by 4D17Y4** [comment]
Sorry for the delay @nicolas-raoul, had some important work.
I will continue this now.
