### ISSUE TITLE
Applying to Google Code-In 2018

### ISSUE THREAD

**Issue by ilgazer** [commons-app/apps-android-commons#1893]
As applications for [Google Code-In](https://codein.withgoogle.com) are now open, do you think our project would benefit from being a part of this? GCI is a competition that encourages high school kids to contribute to open source software. They do this by completing small tasks determined by us. A task is a small project that is expected to take between 3-5 hours of work to complete and can be about Code, Documentation/Training, Outreach/Research, Quality Assurance(Testing), Design. We would have to create hundreds of tasks for students to work on during the contest period and would be responsible for assigning mentors to help students with questions and to review students’ work on the tasks.

Do you think this would be worth it, or would the hurdle of creating and evaluating tasks be too great for the free high school student labor to be worth it. Personally, this could come in handy for having our app tested more(We could maybe assign tasks such as "Find a bug in the browse feature and create a proper issue") and for creating some rough drafts of the outreach and design stuff outlined in #1889. Of course, how useful these would be is somewhat questionable. I would love to create the tasks etc. but I can't really help with anything as I will be too busy with schoolwork this year.

**Comment by misaochan** [comment]
Great idea! I think quality assurance (testing) and outreach, especially, would be excellent and would certainly be helpful to us.

As you say, the main issue is the resources needed to mentor this. Personally I really won't have time until next year. But if anyone is interested, it would be fantastic.

**Comment by ilgazer** [comment]
>it takes as much/more time to mentor something than it does to do it yourself

I could see how mentoring high school kids about coding could take an absurdly long amount of time. But hopefully, for a task like "We are planning on having these meetings where we teach people how to use our app. Design a poster." would yield us 29 horrible posters and one great one which would be easy to mentor and easy to check. 

Also, this could be an outreach opportunity of its own merit. A task like "Ask 3 people around you to identfy one good and one bad thing about our app." could work as a free advertisement (Not sure if Google would be amused however)

**Comment by misaochan** [comment]
@ilgazer I am definitely in support of participating in GCI, no questions there! ;) But we would need to find mentors who are up for it.

**Comment by tanvidadu** [comment]
One of the potential tasks for GCI could be badge designing for achievement module. 
At the moment, we are displaying only a single design of the badge with a different color for each level. The new designs will help us diversify the badges that are assigned. 
After this task, we also go forward with the idea of showcasing all the badges that have been unlocked.

_Would love to know others opinion !_
_I might not be available during the GCI due to  college-work and prior commitments_

**Comment by tanvidadu** [comment]
One of the potential tasks for GCI could be badge designing for achievement module. 
At the moment, we are displaying only a single design of the badge with a different color for each level. The new designs will help us diversify the badges that are assigned. 
After this task, we can go forward with the idea of showcasing all the badges that have been unlocked.

_Would love to know others opinion !_
_I might not be available during the GCI due to  college-work and prior commitments_

**Comment by misaochan** [comment]
Sounds like a great idea @tanvidadu !

**Comment by domdomegg** [comment]
Closing as GCI is over
