### ISSUE TITLE
Add template in body of email for Send Log File

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#1961]
The newly-revamped Send Log File setting now allows users to send their logs to us, but the email body is very generic. Unless the user takes the initiative to write details, we're not sure what the user is trying to tell us.

A template for the email body would be good. Perhaps something like:

> What problems are you experiencing?
>
> What Android version are you using?
>

**Comment by nicolas-raoul** [comment]
Just about the Android version: can't we take it automatically?

**Comment by misaochan** [comment]
@nicolas-raoul Good point, we should take it automatically and include it in the email body :)

Additionally, I just noticed that the new Send Log File in 2.8.6 does not seem to include app version in the email body (the pre-2.8.6 version does). We would need to add this as well.

**Comment by misaochan** [comment]
@AhmedAliNaga Sure, go for it! :)

**Comment by mebr1416** [comment]
@AhmedAliNaga, good day. How's it going?

**Comment by JohnKal** [comment]
If @AhmedAliNaga has stopped working with this issue i would like to work on it.

**Comment by AhmedAliNaga** [comment]
I was working on it but had to stop for midterm exams,  but i am done with my exams now so i can work on it. I apologize for the inconvenience.

**Comment by AhmedAliNaga** [comment]
we downloaded and built the project but we don't know which java classes we are supposed to work on and which xml layout to work on.

**Comment by domdomegg** [comment]
@AhmedAliNaga Don't know if you're still interested in working on this, but you'll likely have to work in `CommonsLogSender.java` and/or `LogsSender.java`

The functions that look particularly important for this issue are
`CommonsLogSender.CommonsLogSender` (see `this.emailBody = message`)
`LogsSender.sendEmail` (see `String body = emailBody`)

However there might be a more elegant solution elsewhere (or I might just be wrong and answer is somewhere else), so do have a look around any other files that look useful.

**Comment by maskaravivek** [comment]
@domdomegg I am taking up this issue if no one else is working on it. 

@misaochan Am planning to add the following information in email body: 

- App version > will help us identify which version of the app is having the issue
- Username > will help us check if the issue is user specific
- network connection type (wifi/cellular-4g/cellular-3g/cellular-2g/no-internet) > will help us check if the issue is with user's network connection
- the device manufacturer and model > some of the crashes are specific to some device models. Will help us identify if that could be the issue
- Android version > will help us identify if the issue is specific to an android version
