### ISSUE TITLE
Move marketing stuff to a different repository

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#1973]
**Summary:** 

Currently the `/design` folder is 136MB, and because git naturally stores file histories it's contributing to the repository being quite a big download. Maybe we could move all of that to a different repo, perhaps `commons-app/design`?

Also if we do this, we might consider removing them with BFG - although caution needs to be taken as some people might be unhappy about changing the git history. At least stopping it early should mean it's not as bad in the future :)

**Comment by nicolas-raoul** [comment]
Yes, a different repo is a good idea!
Only Commons-logo.svg should probably be considered a source file.
The `marketing` folder should probably go there to. Actually, all of these files are for marketing (meaning promotion, and illustration of markets such as Google Play) and not design, so the new repository could be called "marketing" rather than "design".

**Comment by nicolas-raoul** [comment]
I moved most stuff to https://github.com/commons-app/marketing
There is still a `marketing` folder remaining, please someone figure out how it is used by translatewiki and move that too, thanks!

**Comment by chrisdebian** [comment]
It looks like this task may have been completed.
