### ISSUE TITLE
Tapping the "nearest place" card view on the main screen in 2.9 should bring user to Nearby map with that particular pin selected

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#2034]
We did not have the time to implement this in #725 , but this would be a pretty useful enhancement. Currently, when the user taps the "nearest place" card view on the main screen, they are just brought to Nearby in general. They should instead be brought to Nearby with that particular pin on the map selected.

You would need to build on the 2.9-release branch.

**Comment by spelka** [comment]
@misaochan I can have a look at this, if you like.

**Comment by misaochan** [comment]
@spelka Please feel free, thanks!

**Comment by spelka** [comment]
@misaochan I wanted to give you an update since it's been a week. I have committed a solution to my own fork, but while testing this weekend, I have discovered a bug which causes the following effect to occur on the GUI:

![image](https://user-images.githubusercontent.com/7435012/49404274-dbd60900-f703-11e8-9420-46de06e7f018.png)

This duplication effect occurs when I get report of a memory leak in the application:

![image](https://user-images.githubusercontent.com/7435012/49403952-efcd3b00-f702-11e8-94c1-d92dc562d245.png)

It looks like these message are the result of a race condition between garbage collection and the heap dump. This results in a false positive report:

https://github.com/square/leakcanary/issues/808

I'm trying to figure out the best solution to this issue right now.

**Comment by spelka** [comment]
I made a pull request, but I had a thought afterwards: currently when the nearest marker is loaded, only the info window corresponding to the marker is displayed. In contrast, when you select the item by tapping on it, an information panel slides up from the bottom in addition to the info window being displayed. So they are displaying differently.

Was the intent of this enhancement to highlight the nearest marker for the user? Or was it bring up the bottom panel as well?

Let me know you thoughts.

**Comment by maskaravivek** [comment]
IMO, it would be great if we could bring up the bottom panel too. What do others think?

**Comment by misaochan** [comment]
I agree, best to bring up the bottom panel as well. Thanks for working on this @spelka ! :)

**Comment by spelka** [comment]
@misaochan @maskaravivek I have added logic to bring up the bottom bar with the location about the nearest marker. Let me know what you think.

**Comment by misaochan** [comment]
Thanks @spelka ! It looks good to me on first glance. We will have to test it first before we merge it, and we are really busy currently, but we'll try to do it ASAP. :)

**Comment by misaochan** [comment]
@spelka contacted me and said he wasn't able to work on this anymore, so I have removed the assignment at his request. Anyone else, please feel free to take it up. :)

**Comment by ShashwatKedia** [comment]
@nicolas-raoul, this seems to be a similar to #5445 which is solved by #5453. Could we close this?

**Comment by nicolas-raoul** [comment]
Yes, actually yesterday I noticed that this works well.
