### ISSUE TITLE
Remove Notifications from hamburger menu

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2043]
**Summary:** 

Notifications and Nearby options in hamburger menu now feel redundant. After the recent UI overhaul, - we have notification bell icon aptly placed on the home screen. 
- we have nearby functionality(map and list) as a tab on home screen. 

Do we still need these options in the hamburger menu? If we remove these options, then the menu would look a lot simpler and will also give an option to add other items in the future.

**Comment by misaochan** [comment]
Is Nearby still in your hamburger menu? It isn't in mine.

I agree with removing notifications from the hamburger menu. I actually feel that we should put Nearby back onto the menu though, since it is a major feature. For instance, if I go to Explore, then I want to go to Nearby... what happens is that usually I end up opening the menu, wondering "where's Nearby?", then realizing I need to go back to Home and go to the Nearby tab. :)

What do others think?

**Comment by maskaravivek** [comment]
> Is Nearby still in your hamburger menu? It isn't in mine.
No its no longer there. Great!

**Comment by maskaravivek** [comment]
@misaochan If we all agree to remove Notifications from the hamburger menu, I will add a `beginner-friendly` tag to this task and remove the `discussion` tag.

**Comment by misaochan** [comment]
I'm good with removing Notifications from hamburger. @neslihanturan what do you think?

I would like to have a discussion about reinstating Nearby onto the hamburger menu though, as per my reasons above. :)

**Comment by maskaravivek** [comment]
Sure, if @neslihanturan we can create another task just for the Notifications and continue the discussion for nearby here. :)

**Comment by neslihanturan** [comment]
I also agree with removing notifications from menu.

When it comes to nearby, I think we can add a faciliter link to explore which will redirect us to nearby tab on main activity when people click on. I think nearby from main activity and nerby from nearby activity would be confusing and redundant. But definitely we need to put some links.
