### ISSUE TITLE
Move Nearby query to the backend

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#2058]
**Summary:** 

As of now, the SPARQL query to fetch nearby items needing pictures is part of the commons app codebase(`nearby_query.rq`). 

This has several disadvantages. 
- any query optimization is tied up with app updates. This, in turn, means that the optimization would be served only to users on the latest app version. This also exposes us to a big risk if something goes wrong with the query. In that case, only app update can fix the issue. As the user base grows, this might become difficult. 
- The app is not able to take advantage of server-side caching. The high precision location would mean the caching can be quite limited but as of now, we do not have client-side caching as well. As the user base grows, this would start looking more advantageous. 
- The app has to deal with the whole parsing logic for the query response. The logic can be extracted out and the app can simply consume the relevant JSON response containing a list of `Place` objects. `NearbyPlaces:getFromWikidataQuery` looks quite complicated as of now. 
- The app would get a clean API interface where it simply passes the `LatLng`, `lang` and `radius`. For eg. 

```
{
    "lat": 22.23,
    "long": 77.23,
    "radius": 1, 
    "language": "en"
}
```

It would be great if we can host if on tools forge as part of `commonsmisc` and query the JSON API interface instead.

**Comment by ashishkumar468** [comment]
Good point @maskaravivek. Totally agree with it .

**Comment by nicolas-raoul** [comment]
While I agree it would reduce complexity on the app side, there are also demerits:
- The complexity would just get moved to the server side.
- It adds a point of failure.
- It requires us to make sure that 24 hours a day we have someone awake with credentials to the server and who can fix it quickly.
- It is another non-standard API to create and maintain.
- It makes it impossible to refactor variable names or data structure, for fear of breaking something for some users. So in a few years the non-standard API will be bloated with many worthless variables that are only used in one version of the app. For instance if version 2.9.1 puts all translations in the JSON, then all later version have to do it too (so that 2.9.1 users don't get a crash), even if we realize that embedding all translations is a bad idea. A way to reduce that is to introduce API versions, but that also adds complexity.
- I don't believe cache would benefit anyone. With only a few thousand users around the globe, there is zero chance that two queries will be made with the same latitude and longitude. Also, people add P18 properties using the app, so caching is probably not a good idea in the first place.
- It makes forking the app less easy. Let's say some WikiProject forks the app for their own purpose and starts changing Nearby to only show monuments, for instance. Now it is relatively easy, but with a non-standard API it would be very complex.

The SPARQL API is a very solid standard defined by the W3C. Its Wikidata implementation is also rock-solid, with an uptime we can not even dream of reaching. Using a self-hosted non-standard API instead is not unthinkable, but it would require much stronger benefits, I would say.

**Comment by maskaravivek** [comment]
Closing this as #249 and #2358 should take care of this.
