### ISSUE TITLE
Taping on map doesn't close tab in 'nearby'

### ISSUE THREAD

**Issue by athatsakk** [commons-app/apps-android-commons#2252]
**Summary:** 

While exploring the map in 'neaby' , if you click a pin and open the details down there , to close that tab , you have to click again on it. It would be useful to click anywhere on map and also this tab should be closed.

**Steps to reproduce:** 

Go to 'nearby'
Click on a pin
Click down there to show these extra options
Tap anywhere on the map

Tab remains open , and in order to close to you have to tap on the tab only.

**Screen-shots:** 

![screenshot_3](https://user-images.githubusercontent.com/32622637/50559093-301cda80-0cfc-11e9-9c6b-044fb8e84934.jpg)

![screenshot_2](https://user-images.githubusercontent.com/32622637/50559015-6c037000-0cfb-11e9-963a-a20c72e92150.jpg)

**Comment by neslihanturan** [comment]
@athatsakk This screenshots seems very old version of app, currently it looks different. Are you sure your master is up to date?

**Comment by athatsakk** [comment]
Hm, i have hust dowloaded the app from playstore , so i suppose i have the latest version uploaded there. But as i can i see , it is updated there 11th of october , so maybe you are right.

**Comment by athatsakk** [comment]
@neslihanturan , how to run 2.9 version on mobile ( on playsotre there is 2.8.5 ) . Thanks !

**Comment by athatsakk** [comment]
@misaochan  Thanks a lot, i did sign up. Sorry for posting useless ''issues''. I think that this issue also exists in 2.9

**Comment by zhao-gang** [comment]
I think @athatsakk is complaining the current app behavior: when bottom detail sheet is expanded from collapsed state, the transparent view is activated and blocked click(see commit ba9cd4db7).

I am not sure why transparent view should block clickable event. Moreover, I want to argue if we really need this transparentView. Google Maps and Amap(popular in China) do not use similar transparent view when showing list in the bottom of their maps.

**Comment by neslihanturan** [comment]
Actually I think that transparent layer is better to have. Since when we see this transparent later, they are multiple buttons on bottom which we want to make our user focus on. If user also expands the FAB with "+" icon, there are 8 buttons in total. So I think blocking the map is a good decision.

Ie. google hangouts app have the same, when we click on the "+" FAB, it hides all cats with a transparent layer to make us focus on chat buttons instead.

Actually I have implemented that behavior by following material design guidelines: 

> Modal bottom sheet
A user must interact with or dismiss a modal bottom sheet. Their blocking behavior make them suitable for menus, such as in this files app, to help users focus on their available choices.

Here: https://material.io/design/components/sheets-bottom.html#usage

**Comment by nicolas-raoul** [comment]
I am OK with the semi-transparent layer, but tapping on the map should really close the details. I use Nearby very often and it is quite annoying.

By the way, imagine you are in the process of uploading 5 pictures, you have filled 4 titles and descriptions, and at the 5th picture you want to hide the bottom panel to see the picture better, so without thinking you press "Back" (because Nearby trained you to do that), and... you lose all of your work. That's another reason for not making user press "Back" on Nearby.

**Comment by neslihanturan** [comment]
Oh, I see. Currently swiping down is also an option, but it can e hard to discover I agree. So having the layer and making it clickable sounds like the solution.

**Comment by 4D17Y4** [comment]
Hey ,
I would like to work on this one.
Adding to it I think the fab should also close on tap outside both in nearby and in contribution (I was going to open a new issue for it but then found this one.)

**Comment by nicolas-raoul** [comment]
Sure!
Please note that this is labeled as `enhancement`. Since you have fixed many issues labeled as `bug`, you can now work on enhancements too, but in general we try to give a higher priority to bugs :-)
