### ISSUE TITLE
Make achievements activity more discoverable

### ISSUE THREAD

**Issue by vanshikaarora** [commons-app/apps-android-commons#2307]
**Achievements activity  is currently accessed by clicking the icon.  And that icon might not seem clickable  to some general user** 

### Why should we consider this?

- Presently there is no mention of achievements activity or any leaderboard in the app's tutorial
- Currently the icon is displayed over another image in the navigation drawer. 
- To most general users the icon might not be percieved as a clickable element or it may be considered as a UI element.

### What can we do?

- Since the learderboard is an activity. We can add it like another option in the navigation drawer
- Or if this icon looks significantly impressive to users then we can add the same icon to the toolbar

_More suggestions on this opinion are highly appreciated :)_

**Would you like to work on the issue?**
Yes

**Comment by nicolas-raoul** [comment]
While I agree that it is not visible enough now, I don't think adding another item to the navigation drawer is good, as it is already long. Displaying the current level of the user visible would certainly make it more attractive (for instance: `Alaxandrea, level 7`).

**Comment by vanshikaarora** [comment]
>  I don't think adding another item to the navigation drawer is good, as it is already long. 

Accepted

How about adding the same icon to the toolbar?
### Alternatively
Yes we can add the level of the user:
That adds a value. I can add a suggestion here how about adding this tutorial  https://github.com/KeepSafe/TapTargetView for the first time when user uses this app.

**Comment by vanshikaarora** [comment]
@nicolas-raoul So what should i start with?

- Adding level number in place of icon
- Or Add the tutorial as mentioned in the previous link

I'll start working upon this soon afterwards

**Comment by nicolas-raoul** [comment]
I don't think it is important enough to add a tutorial step, a tutorial should only show features that are essential to get started.

Adding the level number means getting that number in the first place,  which is not really easy, and would hurt performance if implemented incorrectly.

Since the achievement activity is [currently broken](https://github.com/commons-app/apps-android-commons/issues/2284), I don't think this is an issue we should focus on right now, so I suggest starting work on other tasks :-)

**Comment by vanshikaarora** [comment]
ok I'll see other tasks

**Comment by Tanvi-Goyal** [comment]
Hi i would like to work on this issue.

**Comment by Tanvi-Goyal** [comment]
Can't we add the icon in the appbar left of the notiification icon.
Please consider else i will start working on the level number idea. 
Thanks

**Comment by vanshikaarora** [comment]
Hey, If no-one is working on this Issue or shall I take this up?

**Comment by nicolas-raoul** [comment]
@Tanvi-Goyal That's an idea we can keep in mind, but I feel that near the username makes the user really feel that their achievements are associated to them. Did you get a chance to start caching the level or anything towards completing this issue? If yes please commit and push, even if it is not complete, thanks :-)

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I would like to work on this issue, could you please tell me what are we finally gonna implement for this issue?

**Comment by nicolas-raoul** [comment]
Actually due to a UI revamp, the activity is now much more discoverable.

I suggest either:
1. closing this issue,
2. or changing the menu item from `TheUser` to `TheUser's achievements`.

**Comment by ShashwatKedia** [comment]
@nicolas-raoul I tried to implement this and successfully stored the user level and displayed it in the menu item next to the username. But this works only after the user visits the achievements fragment once, since the data has to be fetched first; only then can I store it. So, when a user freshly installs and opens the app, the menu will display only their username but will show their level after visiting the achievements fragment once. Either we can go with this approach or close the issue since fetching data beforehand, just for the sake of showing level in the menu, doesn't seem feasible.

**Comment by nicolas-raoul** [comment]
Yes your screenshot shows the right place.

`Tester051005 (Level 1)` sounds good!

If the level is unknown yet, how about displaying `Tester051005 (see your achievements)`?

**Comment by ShashwatKedia** [comment]
> If the level is unknown yet, how about displaying `Tester051005 (see your achievements)`?

Sounds great! It will make the user curious and tempt them to it, nice. I'll do as required
