### ISSUE TITLE
FAB hides cancel and retry buttons on failed uploads

### ISSUE THREAD

**Issue by ShridharGoel** [commons-app/apps-android-commons#2313]
**Summary:** 

In some cases, the new image upload FAB overlaps with the "X" and retry buttons on failed images. In cases like when there are only two images, the buttons become inaccessible.

**Screen-shots:** 

![img_20190117_171810](https://user-images.githubusercontent.com/35566748/51317297-38f00900-1a7d-11e9-949c-f60f90b1556f.png)

**Would you like to work on the issue?**

Yes

**Comment by maskaravivek** [comment]
Can you share how do you suggest to address this issue?

**Comment by ShridharGoel** [comment]
@maskaravivek Actually I was thinking to ask for suggestions from you people since I don't have anything particular in mind on how to address this issue. Can you suggest some ways?

**Comment by maskaravivek** [comment]
@neslihanturan Is our UI expert. She might have some ideas. :)

**Comment by nicolas-raoul** [comment]
I don't think it is a big problem, because when there are failed uploads you just want to either cancel or retry each of them, it is a quick operation (at most the time taken by upload), then you can cancel/retry the next one. So here you would cancel or retry the first, then the buttons will become usable for the second (since failed ones always come to top).

The only problematic case would be if there is only one upload, which failed, and the screen is small enough that the buttons overlap. This case is extremely rare I believe. And there is an easy workaround: Upload another picture.

So I don't think we should spend effort on this :-) Anyone disagree?

**Comment by ShridharGoel** [comment]
Maybe we can add some padding at the end of the list? Or create a dummy entry like the Gmail app does? https://graphicdesign.stackexchange.com/a/50417

**Comment by nicolas-raoul** [comment]
If the dummy entry solution is easy and does not make the code more complex, that would be nice :-)

**Comment by neslihanturan** [comment]
I also don't think this is a big issue:)

**Comment by ShridharGoel** [comment]
Yes, we can close this.
