### ISSUE TITLE
Blue point does not move with me

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2352]
![screenshot_20190125-192150](https://user-images.githubusercontent.com/99590/51789575-5e8fb780-21cd-11e9-8a3a-4f081123c4cb.png)
Expected: The blue point is supposed to follow me.
Actually: The blue point stays where it appeared when I launched the Nearby activity. The grey point follows me.

**Comment by shabrikaruna** [comment]
Can I fix this issue?

**Comment by nicolas-raoul** [comment]
@shabrikaruna yes of course, thank you! The issue is now assigned to you :-)
Have you managed to reproduce the issue?

**Comment by shabrikaruna** [comment]
@nicolas-raoul the issue is fixed!

**Comment by nicolas-raoul** [comment]
@shabrikaruna What version of the app are you using? It is written in the About menu.

**Comment by shabrikaruna** [comment]
Hi @nicolas-raoul I am using 2.10-debug

**Comment by nicolas-raoul** [comment]
Recently I only see a blue point, and it does not move with the GPS.
When walking, to refresh the position of the blue point I am forced to kill the app and start it again.
The blue point should move with me as I walk.

**Comment by neslihanturan** [comment]
IMO solving this issue can be very tricky. Because we have some different cases such as 
- do x when list is expanded, do y when list is collapsed.
- do x when user is searching around, do y when user is walking and requesting track.

I think the main problem is new nearby UI is developed incrementally with feedbacks. And search this area feature added after the initial implementation. Work flow should have been defined better.

I can suggest picking an easier task. But if you feel confident, you can take also this one @shabrikaruna

**Comment by nicolas-raoul** [comment]
Problem still present. Blue circle is at the place where I opened the Nearby map, and the large grey circle is where I am right now:
![Screenshot_20190728-155625_Commons](https://user-images.githubusercontent.com/99590/62677291-caf33b00-b9e8-11e9-9d79-58a462ad81f5.jpg)

**Comment by nicolas-raoul** [comment]
Not perfect but fixed for now :-)
