### ISSUE TITLE
To tackle old issues

### ISSUE THREAD

**Issue by soulspark666** [commons-app/apps-android-commons#2418]
**Summary:** 
Since there are more than 400 issues still pending, with some issues still open after being solved while others being difficult to fix.

We should add the [stale](https://github.com/probot/stale) bot to tackle such problems.

**Screen-shots:** 
![](https://cloud.githubusercontent.com/assets/173/23858697/4885f0d6-07cf-11e7-96ed-716948027bbc.png)

**Would you like to work on the issue?**

Yes

**Comment by soulspark666** [comment]
@ [maskaravivek](/maskaravivek) can I know why you closed it???

**Comment by maskaravivek** [comment]
I closed it because the initial issue that you created didn't contain any details. You seem to have edited it after I closed it. 

<img width="640" alt="screen shot 2019-02-06 at 1 01 17 am" src="https://user-images.githubusercontent.com/3069373/52299193-d1a5e480-29aa-11e9-8331-a4ad4bd6275b.png">

<img width="799" alt="screen shot 2019-02-06 at 1 02 35 am" src="https://user-images.githubusercontent.com/3069373/52299231-ed10ef80-29aa-11e9-996d-09806b857f0d.png">

Feel free to reopen it. :)

**Comment by soulspark666** [comment]
I think I can't [reopen](https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github) it, as this is my first contribution to the repo.

**Comment by nicolas-raoul** [comment]
I don't think that the `stale` label is useful to our project.
It would also certainly be viewed negatively both by reporters (*"I reported an imported issue but they marked it as worthless"*) and developers (*"I don't want to spend my time working on stale issues"*).
Issue #7 has received zero activity for 9 months in 2015, then again zero activity for 9 months in 2016, before becoming a hot issue in 2017 and getting implemented in 2018.
If someone want to see inactive open issues, they just have to click `Sort` and `Least recently updated`.

**Comment by soulspark666** [comment]
We can then just change the label from to _stale_ to anything else that might be more suitable! Since stale bot is made on open source, so code can be changed to whatever may be more appropriate, or I can create a new bot from probot that will be suitable to the requirement!

**Comment by chrisdebian** [comment]
Is this ticket 'stale'?

Chris
