### ISSUE TITLE
Better icon for Achievements' "Images via Nearby Places"

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2445]
This number rewards people who walk a lot to go take pictures where we tell them.
As such, I think the running icon would be more representative.

One the other hand, the pin icon is also representative, and it is immediately recognizable for people who are familiar with Nearby (which is most people whose score at this is more than zero).

![screenshot from 2019-02-13 12-15-04](https://user-images.githubusercontent.com/99590/52684296-276d2480-2f89-11e9-9f19-9a803ed2b0b6.png)
![screenshot from 2019-02-13 12-15-30](https://user-images.githubusercontent.com/99590/52684295-276d2480-2f89-11e9-8a19-a8b1e75d7ac1.png)

https://material.io/tools/icons/?icon=directions_run&style=baseline
https://material.io/tools/icons/?icon=place&style=baseline

Any beginner to our project, please feel free to choose and send us a pull request :-)

**Comment by chris-fo** [comment]
I would like to try t work on this, but as this would be my first contribution, it might take a while.

**Comment by nicolas-raoul** [comment]
@chris-fo good luck, please let us know about your progress once in a while 🙂

**Comment by chris-fo** [comment]
Just a thought: we could maybe also change the icon to the one that marks the nearby places on the map and that is already in use:

![commons_nearby_marker](https://user-images.githubusercontent.com/47518265/52732703-222bcc00-2fc1-11e9-89bd-9b652ff82c01.PNG)

When using darkmode it would look something like this, but i could change the shadow color so it would be visible in dark mode as well:

![commons_nearby_marker_dark](https://user-images.githubusercontent.com/47518265/52733103-2c9a9580-2fc2-11e9-978f-9389c974d982.PNG)

I would have chosen the pin icon anyway (because I think it is - as you said - immediately recognizeable). Maybe this fits the layout even more, what do you think?  I would like to hear your thoughts. 🙂

**Comment by nicolas-raoul** [comment]
Yes, that looks great! :-)
