### ISSUE TITLE
Sometimes bookmarked item appears in blue instead of red

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2477]
Sometimes a bookmarked item appears in blue, instead of red.
Most other items on the same map appear correctly, bookmarked or not.
![adb-screenshot](https://user-images.githubusercontent.com/99590/52857068-6b1e8480-3169-11e9-8386-daf99202b992.png)

**Comment by madhurgupta10** [comment]
@nicolas-raoul I would love to fix this issue, also sometimes the bookmark icon does not change (see gif). We can fix it in this issue or we can create a separate one.
*Plus I think the title of this issue is incorrect* 😛
![ezgif-1-238c0c6629a0](https://user-images.githubusercontent.com/30932899/52907674-0c056080-328c-11e9-9ec2-2419bb13c0bc.gif)

**Comment by nicolas-raoul** [comment]
@madhurgupta10 Nice find! The issue is yours :-)
