### ISSUE TITLE
Adding descriptions in different languages

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#253]
We've had a few requests for that on our Google Play reviews page - is it feasible with the help of the translations community?

**Comment by nicolas-raoul** [comment]
Adding more fields to the title/description screen would only make more people skip it, I think.
If we implement this, how about in the gallery details view?
Alternatively,  in the gallery details view we could just put a link to the image on Commons, so that people can go there and access all of the available features there.

**Comment by neslihanturan** [comment]
Currently we are able to edit description in different languages too. But on description field in Media Details, only the one in English is displayed. 

Maybe a display in all languages button, which will be shown if there is a additional language exist, would solve this issue.

**Comment by vanshikaarora** [comment]
I am interested to work on this Issue.

>Maybe a display in all languages button, which will be shown if there is a additional language exist, would solve this issue.

@neslihanturan Should I add a button displaying list of languages to select from or should I display media description according to the locale (current language of the device)?

**Comment by maskaravivek** [comment]
IMO, it would be cleaner to show the description in the current locale and fall back to English if the description in that language isn't available.

**Comment by vanshikaarora** [comment]
>IMO, it would be cleaner to show the description in the current locale and fall back to English if the description in that language isn't available.

OK then I'll do it this way :+1:

**Comment by nicolas-raoul** [comment]
Please be aware that the information template might not always have the same format.
I am not sure whether the description format is always the same or not.
Here are some examples:
https://commons.wikimedia.org/wiki/Commons:Structured_data/Get_involved/Feedback_requests/Interesting_Commons_files#Variations_on_the_{{Information}}_template
In cases where you get a parsing error (example: malformed template), I suggest just showing the whole thing as now.

**Comment by its-kos** [comment]
Can i contribute to this ?

**Comment by vanshikaarora** [comment]
Hey @its-kos. I am not working on this issue currently. You can take this up :-)

**Comment by its-kos** [comment]
I can do Greek

**Comment by vanshikaarora** [comment]
@its-kos You don't have to translate the description yourself. You can use Wikimedia APIs to fetch description in user's locale.

Check them out [here](https://commons.wikimedia.org/w/api)

**Comment by its-kos** [comment]
This link doesnt work

**Comment by vanshikaarora** [comment]
I'm sorry. Please try this out https://commons.wikimedia.org/w/api.php

**Comment by its-kos** [comment]
Ah well i might have misinterpreted what the issue was, i thought it was a translation

**Comment by vanshikaarora** [comment]
Are you clear with the issue now? Do you need more help with the issue?

**Comment by sumitkp18** [comment]
Hi team,
This is my first time contribution.
I am interested to take up this issue, can I take it? or is someone working on it?

Also can someone help me understand the issue better.

**Comment by nicolas-raoul** [comment]
Ah sorry this has been implemented already... also as a first contribution please choose a bug to fix, thanks :-) See https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md

**Comment by sivaraam** [comment]
> also as a first contribution please choose a bug to fix, thanks :-)

While I agree that bug fixes serve better as first time contributions, I do wonder about the following statement:

> Ah sorry this has been implemented already... 

While we do clearly have support for adding descriptions in other languages (which is done) much of the discussion in this issue seems to be about showing other language descriptions in the media details view (which is _not_ done yet, to my knowledge). So, this issue is in a kind of awkward state given it's misleading title and description. I believe we should either edit the issue's title and description (or) close this one and open a new one for the showing descriptions in other languages.

**Comment by nicolas-raoul** [comment]
@sivaraam Indeed I had only relied on the word "adding" and did not re-read the whole discussion before closing, sorry about that. Master already falls back to showing other languages, and allows to enter captions and descriptions in any number of languages. You are right that this issue is kind of awkward, so better I created a new issue about showing (captions and) descriptions in other languages: https://github.com/commons-app/apps-android-commons/issues/3949
