### ISSUE TITLE
When user takes a photo, send push notification - "Is this a picture of A/B/C? Is it in administrative area D/E/F? (then link Wikidata/Commons)"

### ISSUE THREAD

**Issue by magnusmanske** [commons-app/apps-android-commons#259]
How about when the user take an image to upload, the location is checked against Wikidata items without image nearby (say, 200m), and then presents a list of all these under the heading "Is this a picture of..."?
Likewise, items near the location can give you a "administrative area", or at least a very short list thereof; follow that Wikidata list to "higher" units, and present the lowest one with a Commons category, as a "location category".

**Comment by nicolas-raoul** [comment]
Hello,
Great honour to receive feedback from you!
That's a great idea :-)

We happen to download a database of nearby points already in the app. But since 1) We are currently loading the whole nearby data but will switch to adhoc area-centered requests as soon as we can 2) Wikidata items missing requested pictures vastly outnumber wikipedia requested picture tags; we could also query Wikidata directly with something [like this](https://query.wikidata.org/#SELECT%20%3Fitem%20WHERE%20%7B%20SERVICE%20wikibase%3Aaround%20%7B%20%3Fitem%20wdt%3AP625%20%3Fitem_location%20.%20bd%3AserviceParam%20wikibase%3Acenter%20%22Point%28139.73060%2035.66262%29%22%5E%5Egeo%3AwktLiteral%20.%20bd%3AserviceParam%20wikibase%3Aradius%20%222%22%20.%20%7D%7D).

**Comment by nemobis** [comment]
> How about when the user take an image to upload, the location is checked against Wikidata items without image nearby (say, 200m)

I also proposed this at https://phabricator.wikimedia.org/T143884

**Comment by misaochan** [comment]
Love the idea!

Is the Wikipedia app already interested in taking this on? (since I noticed that they were tagged in the Phab task).

**Comment by nicolas-raoul** [comment]
See also: #79

**Comment by misaochan** [comment]
Relevant suggestion by Mark Traceur on nemo's Phab task:

> A word of caution...if you're pulling photos from a person's recent camera roll, you may be using pictures that were uploaded to other sites (e.g. Google Maps), which may then cause a false positive flag for copyright violation. I would suggest including a question like "have you shared this somewhere else?", which allows people to at least give Commons a heads-up that the picture is already online.

**Comment by nicolas-raoul** [comment]
Isn't it true for any OS though?
Asking for every picture would be very cumbersome.
After 10 uploads asking "Do you often also upload these pictures to other
websites?" would be the best, I think.

On 8 Dec 2016 11:49, "Josephine Lim" <notifications@github.com> wrote:

Relevant suggestion by Mark Traceur on nemo's Phab task:

A word of caution...if you're pulling photos from a person's recent camera
roll, you may be using pictures that were uploaded to other sites (e.g.
Google Maps), which may then cause a false positive flag for copyright
violation. I would suggest including a question like "have you shared this
somewhere else?", which allows people to at least give Commons a heads-up
that the picture is already online.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/commons-app/apps-android-commons/issues/259#issuecomment-265646049>,
or mute the thread

**Comment by misaochan** [comment]
That is true. Or perhaps just state in the notification that people should be aware that if the pic has been shared to other websites, it may be copyrighted?

**Comment by nicolas-raoul** [comment]
The picture is owned by the user, so the problem is not that it might be
copyrighted.
The problem that this issue tries to solve is that Commons bots might
*falsely believe* that it is copyrighted. These bmts compare all incoming
images with all flickr/etc pictures.

**Comment by misaochan** [comment]
I would like to include this in the IEG renewal proposal if possible. Some points of discussion:

1. Should this be displayed whenever the user takes a photo, or when they are in the radius of a place that needs photos, or both?

2. What should the default opt setting be? If we make it opt-in it may too obscure to find, but if it is on by default, users might get annoyed and just uninstall instead of looking for the setting to turn it off (I might have done this with one or two other apps, haha...). My suggestion would be off by default, but when user checks the Nearby list for the first time, it could ask "Would you like to be notified when you are close to a location that needs pictures? Yes/ no and never ask again". Perhaps similarly for the first time they take a picture with our app running in the background?

**Comment by nicolas-raoul** [comment]
After the 5th upload, how about showing a popup saying something like:
"Congratulations on 5 uploads! You have unlocked a new feature: Notify
about nearby items blabla. If you don't want this feature, click here,
otherwise click OK"

**Comment by misaochan** [comment]
Sounds viable! I just thought of another possible option - on by default, but the notification has a "turn off notifications" button.

**Comment by nemobis** [comment]
Testing the feature in Firenze I noticed https://www.wikidata.org/w/index.php?title=Wikidata%3ABot_requests&type=revision&diff=503771009&oldid=503765760 : very useful.

**Comment by misaochan** [comment]
Been looking further into this. It seems that we actually want **two** different types of Nearby notifications, right? 

1) Push notification (opt-in only). This will pop up if the user takes a photo while they are near a Nearby location regardless of whether or not they are in the app. 

2) Standard notification - in top panel of the proposed new UI. This just takes the nearest Nearby location and notifies the user about it. Only visible if the user has the app open.

**Comment by misaochan** [comment]
Also, for those who opt in for the push notification, do we want that to happen only when the user takes a photo near a Nearby place, or whenever they are very close to a Nearby location (even if they haven't taken a photo, but the radius for this should probably be smaller)?

**Comment by nemobis** [comment]
> Push notification (opt-in only).

Ideally the notifications would not be opt-in; Google doesn't ask permission to trick you into contributing your resources into their proprietary database, they just pester you asking to contribute to the map. But an opt-out notification is more useful in a widely used app (like Wikipedia https://phabricator.wikimedia.org/T143884 or OsmAnd http://osmand.net/blog?id=osmand-2-7-released ) so I can understand why you want to be careful.

**Comment by misaochan** [comment]
@nemobis Sorry I missed your comment! Yeah, Google certainly doesn't ask, haha. But to be honest I've personally found Google's automatic notifications to be somewhat annoying, and I'm not sure we want to follow their "strategy" in this aspect...

**Comment by janpio** [comment]
I reread the initial issue: Are you all sure that a notification (no matter how implemented) was the intended functionality here? I more understood that this should be a suggested location (similar to suggested categories) to be connected to the picture on upload in the Commons app.

Showing a notification the moment a picture taken (with nearby locations the picture might match) would be a different feature (and one where I am actually not sure if this is really possible).

**Comment by misaochan** [comment]
@janpio Good point. Perhaps @magnusmanske could clarify? :)

**Comment by misaochan** [comment]
I think going with @janpio 's interpretation for the time being would be the best way to proceed. It's much easier to implement, non-intrusive, and we can get user feedback on how helpful the feature is before considering push notifications.

My suggestion is that when the user selects an image to upload, we run an async Wikidata query in ShareActivity that searches for a place that needs pictures in a certain radius (this radius should be much smaller than the Nearby query). When found, we pick the closest one and display in the UI "Is this a photo of Place X"? If user says Yes, prefill title and description fields for them, and associate their upload with that Wikidata item (as if they had done a direct upload from Nearby). Appropriate category suggestions and p18 edits will follow. 

There needs to also be a way for them to change their mind (perhaps a button that says "Not Place X") before submitting the upload, in case they misclicked (so we don't make a wrong p18 edit).

What do you guys think?

**Comment by nicolas-raoul** [comment]
@misaochan Sounds good, but do you mean the question should pop up "when the user selects an image to upload"? That sounds disruptive, as they already have an image in mind. How about when the user opens the app, maybe? :-)

**Comment by misaochan** [comment]
Hmm, I meant that after the user selects the image, they would be brought to the Title/Desc screen as normal. The Nearby query would then run in the background for a radius of 100m, and if it finds anything, it would ask the user if this is an image of X. 

The query should be relatively quick since the radius is so small, so it would likely pop up while the user is still thinking of their title/desc if my guess is correct.

**Comment by nicolas-raoul** [comment]
Ah I see now, great idea!

**Comment by nemobis** [comment]
neslihanturan, 29/01/20 12:24:
> Closed #259 
> <https://github.com/commons-app/apps-android-commons/issues/259> via 
> #3323 <https://github.com/commons-app/apps-android-commons/pull/3323>.

Interesting! This is only after the user actively opens the Commons app 
and selects the image, right? Or does it happen as soon as one takes the 
picture?

**Comment by neslihanturan** [comment]
It works for all uploads (from gallery or camera), as soon as these conditions are satisfied: https://github.com/commons-app/apps-android-commons/pull/3323#issuecomment-578273104

**Comment by maskaravivek** [comment]
> Or does it happen as soon as one takes the picture?

It doesn't trigger when a user clicks a picture from outside the app. 

Works based on the logic described by @misaochan 

https://github.com/commons-app/apps-android-commons/issues/259#issuecomment-386995266

**Comment by nemobis** [comment]
Vivek Maskara, 29/01/20 18:33:
> It doesn't trigger when a user clicks a picture from outside the app.

Ok. So https://phabricator.wikimedia.org/T143884 remains open for 
whoever/whatever app wants to pick it up.

**Comment by maskaravivek** [comment]
Yup. Also, AFAIK the phab task is for the Wikipedia app. 

Moreover, in the future we can have a similar feature in the Commons app too ie as per T143884.

**Comment by misaochan** [comment]
> This is only after the user actively opens the Commons app
and selects the image, right?

Yeah, we are starting with this for now. :) Might consider actual push notifications in the future, depending on user feedback.

**Comment by nemobis** [comment]
Vivek Maskara, 29/01/20 18:39:
> Yup. Also, AFAIK the phab task is for the Wikipedia app.

Indeed, that was the first idea because it was the most popular app at 
the time and because we were reflecting on how to capitalise that to 
increase contributions, while the Commons app is/was mostly directed 
towards power users and in general users already meaning to contribute.

Things may change.
