### ISSUE TITLE
Level number in achievements position is a bit odd with 2 digits

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2677]
![adb-screenshot](https://user-images.githubusercontent.com/99590/54658887-ef6e7980-4b12-11e9-8e17-1b46dd0e3e5c.png)
Compare with how it looks two days ago:
https://github.com/commons-app/apps-android-commons/issues/2638#issue-421949706
I think it should be a bit more up, don't you think?
Strangely in the screenshot on the right here it looks OK: https://github.com/commons-app/apps-android-commons/pull/2665#issue-262356230
Any idea what is the problem and how to fix it?

**Comment by vanshikaarora** [comment]
>I think it should be a bit more up, don't you think?

I feel it's not exactly centred with the badge in the background.

Since after #2665 we have textview above the badge icon. I think we can centre it accordingly above the badge icon

**Comment by zhao-gang** [comment]
@nicolas-raoul @vanshikaarora I think the reason is that I used hard coded dp in layout file:
https://github.com/commons-app/apps-android-commons/blob/0612519e1cb2f091cac3a2c1c1b7b6b960ddab94/app/src/main/res/layout/activity_achievements.xml#L71-L81

The TextView is horizontally centered with `android:layout_alignParentLeft="true" android:layout_alignParentRight="true"`, but I can't find a way to vertically centered it with the badge image. As I am not very good at UI tweaking, hope someone can pick this up and address this issue.

**Comment by vanshikaarora** [comment]
@zhao-gang I can take this up :+1:
