### ISSUE TITLE
Potential problems with this image : No problem

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2692]
When uploading a picture, I got this screen:
![Screenshot_20190320-141512](https://user-images.githubusercontent.com/99590/54736534-e4891700-4bee-11e9-8937-a01c116a983e.png)
Usually a reason (examples: picture too dark, picture downloaded from Facebook, etc) is displayed, but the problem here is that zero reason is listed.
I pressed "Yes" and the picture got uploaded successfully to https://commons.wikimedia.org/wiki/File:Omotesando_station_exit_2_at_night.jpg

**Comment by nicolas-raoul** [comment]
For reference, here is an example of how reasons should be listed:
![Screenshot_20190320-144743](https://user-images.githubusercontent.com/99590/54736681-a3ddcd80-4bef-11e9-9e5b-28d089f7f1a9.png)

**Comment by vanshikaarora** [comment]
Hey, I am working on this Issue

**Comment by vanshikaarora** [comment]
Hey @nicolas-raoul I think that you have uploaded an image that was downloaded from internet. And the error dialog poped up due to the merge of #2581. However I think slight change was needed in ImageUtils.java. I have made the changes [here](https://github.com/commons-app/apps-android-commons/pull/2697). Kindly review :)
