### ISSUE TITLE
Moving GPS FAB to bottom right corner 

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#2778]
**Summary:** 
I think we should move GPS FAB to the bottom right corner. Even google maps GPS Fab is located at the right bottom and all other FAB icon we have are on the right bottom, so it makes sense to move the GPS Fab to the right-hand corner as well.

**Screen-shots:** 
![Screenshot_20190328-071649](https://user-images.githubusercontent.com/30932899/55123686-8e096480-5129-11e9-8456-0cc4c555918f.png)

**Would you like to work on the issue?**
Yes

**Comment by neslihanturan** [comment]
Where do you plan to put upload FABs @madhurgupta10 ?

**Comment by madhurgupta10** [comment]
@neslihanturan I don't think that we should move the upload FAB, when clicking on a marker and the bottom list expands, it will definitely cover the GPS FAB, but I think that is ok, as when a user clicks on a marker, they don't want to move around the map. Please let me know your opinions on this :)

**Comment by neslihanturan** [comment]
I don't think covering/blocking an item is a good idea, it would feel like there is a problem. Besides, since there are multiple FABs on the same screen we should keep them separated to prevent confusion, as material design guideline already doesn't suggest to use multiple FABS on same screen: https://material.io/design/components/buttons-floating-action-button.html#usage . Google Maps is mainly for using the map, so centering your location can be one of the main function of it. On the other hand the main function of our map is uploading. So upload button should be close to finger, and it is okay to having recenter button on the top IMO.

**Comment by madhurgupta10** [comment]
@neslihanturan Very well explained 👍 I agree that the main FAB should be on the right bottom corner,  for our app it is Upload, so we should not move the GPS fab, but if possible we can replace the margin attributes and add unified padding to it, similar to screenshot. Unified padding for all FAB makes the UI a bit more pleasing.
![InkedScreenshot_20190328-071649_LI](https://user-images.githubusercontent.com/30932899/55163889-9e085f00-5190-11e9-89f0-92e3d774a637.jpg)

**Comment by neslihanturan** [comment]
Agreed. There is a related, open PR #2780 . Please cooperate with PR owner.

**Comment by madhurgupta10** [comment]
@neslihanturan Sure, I will update the Location FAB padding aswell :)
