### ISSUE TITLE
Encourage testers to use alpha

### ISSUE THREAD

**Issue by sivaraam** [commons-app/apps-android-commons#2838]
**Summary:** 

The 'Testers' section of the ['Volunteers Welcome'](https://github.com/commons-app/apps-android-commons/wiki/Volunteers-welcome%21)Wiki page now reads:

> Use the beta version or even better, compile from the latest source! Report bugs to the issue tracker.

Given that we now release an alpha versionaybe it could be changed into something like,

> Use the beta version or even better, use the alpha version which is more cutting edge! Report bugs to the issue tracker.

**Comment by sivaraam** [comment]
BTW, I used to edit Wiki pages long time ago. Now I don't see the option to Edit them. Has editing been restricted to collaborators?

**Comment by nicolas-raoul** [comment]
Indeed this seems to be the current configuration:
![Screenshot from 2019-04-03 13-09-40](https://user-images.githubusercontent.com/99590/55452256-c91c0400-5611-11e9-8952-ba7b0aa21310.png)
I can't remember a discussion about changing it :-/

**Comment by misaochan** [comment]
We did this because there was a period of time when a spammer kept creating nonsensical wiki pages and overwriting our work. :/ 

I wish there was a way to fine-tune the permissions (IMO contributors should all be able to edit wikis, which would still exclude spammers since they wouldn't have had a merged PR).

**Comment by nicolas-raoul** [comment]
@sivaraam Updated, thanks! :-)

**Comment by sivaraam** [comment]
Looks great, thanks!
