### ISSUE TITLE
Wrong thumbnails appearing and flickering

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#2871]
when scrolling in Explore and home activity.

It started happening rather recently.
It now happens all the time, even on super-fast WiFi.

**Comment by madhurgupta10** [comment]
@nicolas-raoul I think this is happening due to the high-resolution images used for preview, this takes time for recyclerview to load. A possible approach would be using the cache mechanism ([reference](https://stackoverflow.com/questions/26856487/recyclerview-painfully-slow-to-load-cached-images-form-picasso)) or IMO we should use low-resolution images for thumbnails.

**Comment by maskaravivek** [comment]
@nicolas-raoul Does this still happen?

**Comment by nicolas-raoul** [comment]
Yes, always, even after changing phones and reinstalling the almost 10 times.
This is especially visible when uploading a new picture.

**Comment by ashishkumar468** [comment]
Even I have faced this issue, especially while uploading, all of the items flicker (including the one being uploaded), seems like some issue related with us posting the progress update.

**Comment by devarsh-mavani-19** [comment]
@nicolas-raoul How about using glide library? @madhurgupta10 mentioned that using a caching solution will help and From my past experience glide is better than picasso when there are lots of images to load. I would like to solve this issue if no one is currently working on it

**Comment by nicolas-raoul** [comment]
Actually this issue is fixed, sorry for leaving it open!
