### ISSUE TITLE
Nearby not loaded correctly if no network the first time

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#291]
1. Disable network
2. Open Nearby
3. It fails to load the CSV, this is expected
4. Go back to the main screen
5. Enable network
6. Open Nearby again
7. It fails to load the CSV, this is not expected

**Comment by misaochan** [comment]
@nicolas-raoul , it is expected with the current code because the CSV file is only downloaded the first time Nearby is opened (closing the app resets this, and of course most phones will kill inactive apps, which is same as a close).

AFAIK there are only two options:
1) We request 'access network state permission' in order to check the network and reload the CSV file if we detect that the network has been enabled
2) Load CSV file every time Nearby is opened (not a good idea IMO, significantly increases load time)

**Comment by nicolas-raoul** [comment]
Can't we just check (every time the Nearby page is opened) whether the object containing the CSV data is null or not?
It am pretty sure we don't need this permission, in any case.

**Comment by misaochan** [comment]
Hmm.

The way I fixed Vojtech's crash was by checking:

```
        if (places.size() > 0) {
            for (int i = 0; i < 100; i++) {
                Place place = places.get(i);
                String distance = formatDistanceBetween(mLatestLocation, place.location);
                place.setDistance(distance);
            }
        }
```

I don't think I can make it reattempt the connection if places.size() == 0, since if there was still no network connection, it would just fall into an infinite loop, right?

I will try to see if there is another way to do it.

**Comment by oe-bayram** [comment]
Should be closed.

**Comment by neslihanturan** [comment]
Actually, it shouldn't. I could able to reproduce this bug just a minute ago.

**Comment by misaochan** [comment]
Do you mean you encounter this when you select to use the CSV instead of Wikidata as your source, @neslihanturan ?

On a somewhat tangential note, I wonder if it would be a good idea to completely remove the CSV option from Nearby. We kept it in initially just in case some people faced issues with the Wikidata implementation, but it has been many months now and I don't think anyone is using the CSV at all. Wikidata seems to be superior in all ways, as far as I can see.

In that case, if the CSV option doesn't exist, this issue can automatically be closed. I don't think we should waste developer time on improving something that nobody is using.

@nicolas-raoul What do you think?

**Comment by nicolas-raoul** [comment]
We don't use CSV anymore, so I am in favour of closing this bug and opening new bugs for any such new problems :-)

**Comment by misaochan** [comment]
Yeah, there is an option in Settings for the user to use CSV. :) But removing the entire CSV option might reduce complexity, especially as many of the new improvements (e.g. #252 ) will only work solely for Wikidata. I wonder if anyone actually uses the CSV? It takes like 5 min to load, lol.

**Comment by nicolas-raoul** [comment]
Even if we dump CSV, keeping a layer of abstraction might help if we decide to implement #883.

**Comment by VojtechDostal** [comment]
CSV seems so slow and ineffective compared to the Wikidata-based tool that I'm supportive of abandoning it completely.
