### ISSUE TITLE
Reconsider peer review button strings

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#2920]
**Summary:** 
We want to have single line buttons, but since our button texts are too long, we reduced their text sizes for a temporary solution. 

We need to have shorter (but still meaningful) button texts. Or we need to find strings that will be relevant even in short form. 

**Steps to reproduce:** 

Open peer review activity

**Screen-shots:** 

Here how it looks now:
![Screenshot from 2019-04-24 14-23-15](https://user-images.githubusercontent.com/3127881/56661476-78e11080-66aa-11e9-9c42-36602ebc75b4.png)

Here how we want to make it look:

![Screenshot from 2019-04-24 14-27-56](https://user-images.githubusercontent.com/3127881/56661555-a4fc9180-66aa-11e9-83af-89171d9913a2.png)

**Comment by madhurgupta10** [comment]
@neslihanturan also the position of **SKIP THIS IMAGE** confuses first-time users (if it is a subtitle or a button).

**Comment by neslihanturan** [comment]
Thanks for your interest, what are your suggestions for new strings @mar7yn ?

**Comment by mar7yn** [comment]
Instead of:
"Is this correctly categorized"

Use either:
"Review image categories" or
"Review category assignment"

Button strings:
"Reject" versus "Seems fine"

Any thoughts?

**Comment by chaytanyasinha** [comment]
May I contribute to this issue @neslihanturan

**Comment by neslihanturan** [comment]
Sure @chaytanyasinha , do you have suggestions for strings?

**Comment by chaytanyasinha** [comment]
@neslihanturan ma'am,
I would say that while questioning we can let it be "Does this follow the rules of copyright?".And we can say "Logos,screenshots,movie posters are often  copyright violations".That's it,because writing "Clicking NO to nominate this image for deletion" as it's already mentioned in the first review question and it's letting the "NO,copyright violation" to hide or  we can shift the "NO,copyright violation"  little upward.
![WhatsApp Image 2019-11-09 at 22 28 01](https://user-images.githubusercontent.com/50200796/68533705-30412a00-0352-11ea-93ab-c72f8405096e.jpeg)
![WhatsApp Image 2019-11-09 at 22 28 56](https://user-images.githubusercontent.com/50200796/68533706-30412a00-0352-11ea-80f8-aa202c6118f7.jpeg)

**Comment by chaytanyasinha** [comment]
For "Is it in scope" we can write "Is the picture clicked correctly"  and instead  of "Is this picture under <category>?
where <category> is a variable which will be changed with the name of the category.

**Comment by neslihanturan** [comment]
Hey @chaytanyasinha, thanks for sharing preffered strings but they are somehow longer then the previous ones. but we want to make them shorter. Additionally it is always better to ad a single space after punctuations. By the way I am not the most suitable person to discuss language fixes so this discussion is very open for someone to join

**Comment by chaytanyasinha** [comment]
Hey @neslihanturan  thanks for letting me know.Well I  was also thinking of  of the string "Does this come under <category>?" where <category> is variable which will be adjusted with the according to whatever the category will be.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul now we have a perfectly size button so we can close this issue now
