### ISSUE TITLE
Remove SyncService and SyncAdapter

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#3070]
**Summary:** 

The app uses SyncService and SyncAdapter which does nothing but makes the api call and saves the data in db, the same can be done from the Activity as well. The Sync service is useful only when our backend supports that(send us data letting us know that do we need to sync), or if we use periodic syncs. As currently our app uses none of them. We can simply shift to making the api call from the activity itself

**Comment by ashishkumar468** [comment]
Would be great if @misaochan @maskaravivek @neslihanturan  could share your views :-)

**Comment by misaochan** [comment]
Would we not need to do periodic syncs once we implement the ability to pause/resume uploads?

**Comment by maskaravivek** [comment]
> Would we not need to do periodic syncs once we implement the ability to pause/resume uploads?

[Sync adapter](https://developer.android.com/training/sync-adapters/creating-sync-adapter) is mostly used when you want to schedule periodic syncs in the background. Our sync adapter does nothing of that sort. It simply triggers sync when MainActivity is opened. Since we don't intend to perform background syncs `SyncAdapter` is just an overhead. A simple API call would be enough.

As far as pause/resume uploads or dynamic update of list is concerned, it would be taken care of by [live data](https://developer.android.com/topic/libraries/architecture/livedata) once we move to Room DB.

**Comment by ashishkumar468** [comment]
Also, the sync adapter as of now is meant to sync contributions and takes no part in upload. The Upload is happening from a separate service  (UploadService), which will be modified along with others to support Pause/Resume.

**Comment by ilgazer** [comment]
IMO it would be better if we did away with ContributionsSyncAdapter and connected our data sources(ContributionDao for failed uploads etc. and UserClient for online data) to the recyclerview directly. How important is caching the user's contributions offline?

**Comment by ashishkumar468** [comment]
This has already been implemented
