### ISSUE TITLE
"No depictions selected" despite one selected

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3076]
![Screenshot_20190717-131311_Commons](https://user-images.githubusercontent.com/99590/61356698-de135f00-a8b1-11e9-8b4e-f0dad7aea975.jpg)
@vanshikaarora

**Comment by vanshikaarora** [comment]
I'll look into this

**Comment by nicolas-raoul** [comment]
This is still happening, did you try to reproduce it an fix it?

**Comment by vanshikaarora** [comment]
@nicolas-raoul I tried to work upon this. Actually the Issue is, when you click on the checkbox it shows not item selected however when you click on the depiction item(the text or description) it works perfectly.

The Issuue is it considers only the text and description item in it's root view and not the checkbox. I am still not able to figure out why the entire `layout_upload_depicts_item.xml` as it's root view

**Comment by nicolas-raoul** [comment]
Are the correct "Q___" items passed to the method that uploads depictions?
If yes, how about using checking whether the list of items is empty, rather than checking the UI? :-)

**Comment by vanshikaarora** [comment]
@nicolas-raoul yes the "Q____" items are passed when you click on the label or description nut are empty on clicking the check box

**Comment by nicolas-raoul** [comment]
I am sure that pressing the checkbox works for _categories_. Please compare the two in debug mode, thanks :-)

**Comment by vanshikaarora** [comment]
@nicolas-raoul I have fixed the issue [here](https://github.com/commons-app/apps-android-commons/pull/2970/commits/39834fb61faeacc0fe0c3265cceb74de54030a44)

Please check :-)

**Comment by nicolas-raoul** [comment]
Seems to work well now, thanks 🙂
