### ISSUE TITLE
Categories aren't added

### ISSUE THREAD

**Issue by AtaZh** [commons-app/apps-android-commons#310]
While struggling with #307 I uploaded image with Ukrainian interface. Now I see that file is not categorised. 
https://commons.wikimedia.org/w/index.php?title=File:Чорнобривці_.jpg&oldid=210922719
Though I did check three categories from the suggestions:
![screenshot_2016-10-26-14-08-57](https://cloud.githubusercontent.com/assets/10130813/19731716/034d9c24-9ba7-11e6-84f6-f1f07d8b3f25.png)

**Comment by misaochan** [comment]
Hm, I just tested the latest version again and could not reproduce your bug. Does it repeatedly fail to categorize any image or is it just this one?

**Comment by AtaZh** [comment]
I've just uploaded another one - same thing.
https://commons.wikimedia.org/?curid=52554328

**Comment by AtaZh** [comment]
Changed device to English - same thing
https://commons.wikimedia.org/wiki/File:Monastery_hill.jpg

**Comment by misaochan** [comment]
Wow, interesting. @AtaZh what version of the app are you using? Do you remember if categories worked for you prior to this version?

**Comment by misaochan** [comment]
Ah, okay, I think I might have reproduced this issue. It seems that categories are never submitted along with the file, but rather added later (e.g. my contribution history https://commons.wikimedia.org/wiki/Special:Contributions/Misaochan ) . Not sure why this is done, I'll have to delve into the preexisting code to see. 

But it seems that in some cases, like @AtaZh 's submissions and a few of the files I submitted, the 'extra step' doesn't happen at all, and thus no categories are added.

**Comment by misaochan** [comment]
I'm pushing a fix that I think might solve the problem (mostly just reversing any changes I made to the relevant code). Can't check whether or not it works yet though, since the category addition can take up to several hours after submission. If it doesn't work, I'll try to contact the original dev to ask.

**Comment by misaochan** [comment]
Seems to work on my phone: https://commons.wikimedia.org/wiki/File:Christchurch_Botanic_Gardens_2.jpg

Hope it works for you guys as well.

**Comment by misaochan** [comment]
Is anyone still experiencing this issue?

**Comment by misaochan** [comment]
I figured out why categories aren't submitted with the original file but are submitted as a modification later - it's because uploading starts immediately when the picture is selected, whereas categories are selected after that. So unless we only start uploading when categories have all been selected, this is necessary.

I still haven't figured out why it 'misses' the modification sometimes, and why it takes so long sometimes.

**Comment by misaochan** [comment]
Another user is having issues; https://commons.wikimedia.org/wiki/File:Plat_tunisien_de_sauce_d%27%C3%A9pinards_et_de_viande,_21_f%C3%A9vrier_2017.jpg

I don't think this will be an easy fix but we should put it on the priority list.

**Comment by misaochan** [comment]
The user has informed us that all his categories were added a few days later, lol. We should probably try to talk to yuvipanda about this.

**Comment by psh** [comment]
@misaochan - Is this still a bug that needs to be addressed?

**Comment by misaochan** [comment]
@psh It hasn't happened recently for me, but not sure. Has anyone else experienced this recently? @AtaZh ?

**Comment by AtaZh** [comment]
[Still there ](https://commons.wikimedia.org/w/index.php?title=File:Sprouts_of_dill.jpg&oldid=254815246)

**Comment by brainwane** [comment]
I'm still experiencing this; see https://commons.wikimedia.org/w/index.php?title=File:Hari-kondabolu-onstage_2.jpg&oldid=274778522 .

**Comment by misaochan** [comment]
@AtaZh and @brainwane , thanks for letting us know!

**Comment by Czeva** [comment]
Hi, I am not getting categories, either, although the files were saved from the category page in the app. The images are always uploaded but the ctg is not, even after 2 days. Example: https://commons.wikimedia.org/wiki/File:%C4%8Cesk%C3%BD_Krumlov,_PP_Cvi%C4%8D%C3%A1k.jpg, uploaded as "Uncategorized" (ctg added by myself 2 days later). The same thing happened today (uploaded image w/o the ctg). Using verion 2.7.2, update requests always allowed.

**Comment by nicolas-raoul** [comment]
@Czeva 

Do you mean that categories are *never* saved?

Would you mind pressing "menu > settings > send log file" 5 seconds after having choosing the categories and pressing the floppy icon, and then a minute after? Thanks!

The best would be to sniff local traffic, you could try this using one of the methods described at https://stackoverflow.com/questions/41152974/whats-the-best-way-to-capture-packets-sent-and-received-by-my-own-android-app

**Comment by Czeva** [comment]
@nicolas-raoul 
Well, every time I have used the app, no ctg was uploaded although it was added before upload. I did my best to send the log from my phone but had to use a different email address (gmail) than the one I had registered here with. The methods mentioned above are, I'm afraid, a bit difficult, sorry.

**Comment by misaochan** [comment]
Hmmm. I looked through the log file and unfortunately I can't find anything there that would help pinpoint the problem. :/

As this has been a longstanding and difficult-to-solve problem that causes users a lot of inconvenience, I would like to raise again the possibility of solving this issue by simply having categories sent alongside with the image upload as part of the template, instead of as a modification afterwards. 

I do understand that the downside of this would be that the image upload would begin later - instead of beginning BEFORE the categories are selected, it would only start AFTER the categories are selected. However, I personally feel that this is unlikely to impact the user too much, since they can start another upload or do whatever else they want with the app while the first image is uploading. From a user point of view, does it really matter that the upload finishes 30 seconds later, if they aren't having to wait for it?

What do you guys think?

**Comment by domdomegg** [comment]
I believe @misaochan's solution is implemented in new upload flow, so this shouldn't happen any more. Please reopen if it does.
