### ISSUE TITLE
Raising awareness of the difference between this app and the deprecated mobile web app

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#321]
https://meta.wikimedia.org/wiki/2016_Community_Wishlist_Survey/Categories/Commons#Uploading_from_a_mobile_phone - This is about the 6th time I have encountered mention of the copyvio/selfie-pocalypse of 2014 when our app is brought up. :/

Is there any way we can raise awareness of the Commons community in general about the differences between the deprecated mobile website (which was associated with the copyvio/selfie-pocalypse) and the Android app (which was not)? I have been explaining the difference each time I see it being brought up, as well as linking http://tools.wmflabs.org/commons-app-stats/ , but it doesn't seem to be very effective. The various small discussions are clearly not reaching the community as a whole, as many people are still mistakenly equating the two. 

Any suggestions? I think this is pretty important, because we need the support of the Commons community if we want to make progress with this app.

**Comment by nicolas-raoul** [comment]
Having a visible "patrolling queue" (A webapp where everyone could see "The backlog is currently 20 images" or something similar, and patrol themsleves ) would defuse all objections, especially if its backlog is kept low.

Actually I am kind of patrolling all new uploads made by the app, and the backlog is low even if I do it all by myself. The problem is it is not very visible, nobody knows someone is patrolling.

**Comment by misaochan** [comment]
Ah, nice, that could be useful! Do you mean we should put the webapp on our website? Or integrate it into the app?

**Comment by nicolas-raoul** [comment]
I was thinking about a Wikimedia-hosted webapp, see screenshot at https://commons.wikimedia.org/wiki/Commons:Recent_uploads_patrol

**Comment by nicolas-raoul** [comment]
Let's ask for one :-) https://meta.wikimedia.org/wiki/2016_Community_Wishlist_Survey/Categories/Commons#Recent_uploads_patrol_webapp

**Comment by misaochan** [comment]
Awesome, thanks!

**Comment by whym** [comment]
It might help if we provide a fine-grained list of differences - here is my attempt.

Mobile web (2013-2014(*)):

* Entry point: Logged-out user selects "Uploads" from the navigation menu of the **mobile version Wikipedia** (e.g. https://en.m.wikipedia.org) or clicks a big button at the top of an article saying "Add an image to this article". (Source: https://www.mediawiki.org/wiki/Mobile_design/Uploads#User_experience)
* Target user: **users new to Wikimedia** (*)
* Deletion stats: https://www.mediawiki.org/wiki/Mobile_design/Uploads
* Description is optional. (*)
* No option for app's user to add categories upon upload (*)
* No integration with camera (*)
* App automatically adds the image to a Wikipedia article as soon as it's uploaded.
* Integrated to Wikipedia in general

Android app (2013-2016):

* Entry point: The user searches for "Wikimedia Commons" in the Google Play Store. They can also visit Commons:Mobile_app and follow links.
* Target user: more emphasis on **existing Wikimedia users** who know what Wikimedia Commons is
* Deletion stats: https://tools.wmflabs.org/commons-app-stats/ (*)
* Description is required.
* The user can add categories using the app.
* Camera available from the app itself
* No feature to help adding images to Wikipedia
* Does not interact with Wikipedia (yet?)

(*) I believe so, but I'm not entirely sure / I'm not sure if it's by intentional design or by coincidence.

**Comment by misaochan** [comment]
That looks great, @whym . I would put "Install required" as a separate bullet point, though, since that is IMO a big factor in the discrepancy of deletion stats between the two (installation requires a certain level of 'investment' at the start, both in terms of time spent and in resources, which a troll with poor intentions would be less likely to be willing to do). 

Where do you think would be a good place to put this? On our wiki page perhaps? It looks a bit too much to be on the main page of the website IMO, though it might work on a side page.

**Comment by chrisdebian** [comment]
This seems really relevant when it was opened; is it still, or can it be closed?

Thanks,

Chris.
