### ISSUE TITLE
Color of conditions in Nearby

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3235]
In the screenshot below, "Exists" is disabled and "Needs Photo" is enabled, right?

I feel that making active thingies grey is not necessary, maybe even counter-intuitive? Same color all the time would be enough I think.

Let's wait for other people's feedback though, maybe it's just me.

![Screenshot_20191129-183826_Commons](https://user-images.githubusercontent.com/99590/69859399-6f222a00-12d7-11ea-8d6b-7985038a0f13.jpg)

**Comment by a18jouan** [comment]
Hi, 
When does this happen ? I am a new user and I can't find this situation.

**Comment by misaochan** [comment]
I guess part of the reason was that the items in the "Place Type" list are marked in grey when they are selected, so the Place State cards look uniform if they are also greyed when selected. But I am OK either way. :)

@a18jouan are you on beta testing? This feature is only released in beta and alpha.

**Comment by mds08011** [comment]
I agree.  Both the bright white and check marks make me think "selected".

On a related note, the dark text in "Place type" is a bit hard to read against the dark blue background.  Perhaps this could be a lighter grey?  It looks much clearer in this screenshot, but while on my phone I had trouble finding the "X" to close the "place type" drop down menu.

<img src="https://user-images.githubusercontent.com/8010709/73588337-d5186280-447c-11ea-95d8-c222a32b8204.jpeg" width="50%">

**Comment by misaochan** [comment]
Having used it a bit more now I agree, I think keeping a uniform color is best. If we did keep the colors, I would personally think that "greyed out" means NOT selected (the reverse of what we are currently doing)... but I recall we discussed that and had differing opinions. :) 

@mds08011 The dark text is fixed in #3331 , so will probably be out in the next version.

**Comment by ciphereck** [comment]
@misaochan Can I work on this issue?

**Comment by maskaravivek** [comment]
Yes, sure. Assigned to you.
