### ISSUE TITLE
Crash at start, every time

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3289]
with latest master 2.12.0.525

maybe because I have a failed upload?

**Comment by misaochan** [comment]
Hi @nicolas-raoul ,

All of the crash reports you have sent to the google groups mailing list have been empty, no title or body. Do you think you could take a look at why this is happening, or otherwise copy the crash logs over to this issue? I don't think it's an ACRA issue because other people's reports are coming through fine.

**Comment by nicolas-raoul** [comment]
Yes I realized that recently the app was crashing without attaching any
information.
I would have loved to take a logcat but I am travelling.
"Send logs" is also not accessible because of the app crashes before.
Because I needed Nearby I wiped app storage and connected with another
account, it solved the problem. I hope some of us can reproduce the problem
though.

**Comment by misaochan** [comment]
Hmm, okay. Could be due to a recent change in master (after the 2.12 release). We'll keep an eye out for it.

Incidentally, does Nearby work for you now (i.e. Punta Arenas bug solved)?

**Comment by ashishkumar468** [comment]
Closing this issue because there are no logs tod debug. My guess is that because of improper DB migrations which has been handled properly in 2.13/master. Closing this issue for now
