### ISSUE TITLE
Unicode escapes in strings

### ISSUE THREAD

**Issue by Nikerabbit** [commons-app/apps-android-commons#335]
Is it possible to conver the \u#### style escapes to literal characters in the strings? Our parser at translatewiki.net doesn't seem to handle them appropriately.

**Comment by misaochan** [comment]
@nicolas-raoul , @whym or @jayvdb  , any thoughts on the feasibility of this?

**Comment by nicolas-raoul** [comment]
How does the wikipedia app handle this? Let's do like them if sensible.

**Comment by Nikerabbit** [comment]
All the translations are already in Unicode, so I would be surprised if these particular characters (dashes mostly?) which are currently escaped wouldn't work.

**Comment by whym** [comment]
Yes, looking at another bug #217, it seems as if this escaping serves no purpose, but creates problems only. However, I don't know why it was introduced (it must be years ago), so I can't be perfectly sure.

If we want to be really cautious, we could perhaps remove all escaped Unicode characters from the source resource (string.xml).

I found these instances:

app/src/main/res/values/strings.xml:107:    <string name="license_name_cc_by_sa">CC\u00A0Attribution-ShareAlike\u00A03.0</string>
app/src/main/res/values/strings.xml:108:    <string name="license_name_cc_by">CC\u00A0Attribution\u00A03.0</string>
app/src/main/res/values/strings.xml:147:    <string name="tutorial_2_subtext">\u2022 Natural objects (flowers, animals, mountains) \n\u2022 Useful objec
ts (bicycles, train stations) \n\u2022 Famous people (your mayor, Olympic athletes you met)</string>
app/src/main/res/values/strings.xml:149:    <string name="tutorial_3_subtext">\u2022 Selfies or pictures of your friends \n\u2022 Pictures you downloade
d from the Internet \n\u2022 Screenshots of proprietary apps</string>
app/src/main/res/values/strings.xml:151:    <string name="tutorial_4_subtext">\u2022 Title: Sydney Opera House \n\u2022 Description: Sydney Opera House 
as viewed from across the bay \n\u2022 Categories: Sydney Opera House, Sydney Opera House from the west, Sydney Opera House remote views </string>

U+00a0 is no-break space. Do we really want to forbid line-breaking at these positions? Otherwise, a normal space will be fine.

U+2022 is a bullet. I think it's okay to replace it with a hyphen.

**Comment by nicolas-raoul** [comment]
Well let's try and remove these \u
Time has passed and tools have changed, I don't think Unicode should be a
problem for any of the tools we currently use.

**Comment by misaochan** [comment]
I've replaced all the escapes I could find in strings.xml with spaces or hyphens. Please do let me know if anything else is needed, thanks!

**Comment by misaochan** [comment]
Whoops, wrong pull request.
