### ISSUE TITLE
Handle zoom in media details view

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#3414]
App review:

> The "Contributions" section is terribly designed: full-width images with title text over them instead of thumbnails. Tapping to open one instead shows a full-height portion of the image that can't be scrolled across nor zoomed out of. Basically, it's a pain to see what you've uploaded and impossible to see a whole image unless you open it in the browser.

I actually thought that we had redesigned media details to fix this - I recall @ujjwalagrawal17 was working on it during the hackathon, and had a branch going that handled zoom and scrolling appropriately. I also recall we were close to merging, but I can't actually find the PR now. @maskaravivek any idea?

**Comment by kbhardwaj123** [comment]
![Screenshot_20200215_204443](https://user-images.githubusercontent.com/44129798/74590450-83271f00-4fdc-11ea-9f55-d316c9e34d0c.jpg)
I think it would be better if aspect ratio of the image be maintained in displaying details rather than cropping in, moreover on cropping in the quality degrades we can implement something similar to google photos or pinterest mobile app

**Comment by maskaravivek** [comment]
@misaochan Here's the original issue #2881 and PR #2954 that @ujjwalagrawal17 worked on and which was merged to the hackathon branch. I am not sure if handling zoom was part of the redesign.

**Comment by kbhardwaj123** [comment]
@misaochan I think we can implement semthing like this simple mockup app:
![GIF-200216_014623 1](https://user-images.githubusercontent.com/44129798/74594608-5a476e00-505e-11ea-9ad0-a0e9089a6715.gif)

**Comment by misaochan** [comment]
@kbhardwaj123 That looks good, would you be interested in implementing the fix? :)

>  think it would be better if aspect ratio of the image be maintained in displaying details rather than cropping in

I agree.

**Comment by kbhardwaj123** [comment]
@misaochan yes sure I'll start working on this

**Comment by misaochan** [comment]
Thanks @kbhardwaj123 . Please update us as you go along, and ping me when the PR is ready. :)

**Comment by kbhardwaj123** [comment]
@misaochan @maskaravivek I want your opinion on one thing, while working on the Media Detail Fragment It came to my mind that the details of a contribution can be shown as Material Design Cards(shown above in my mockup) rather than the grey Edgy tile design we have right now shown below:
![Screenshot_20200215_204443](https://user-images.githubusercontent.com/44129798/74590450-83271f00-4fdc-11ea-9f55-d316c9e34d0c.jpg)

**Comment by misaochan** [comment]
Yes, the grey tile design is very old. I personally would be in support of switching to material design cards, however I'm not sure we should conflate that with this issue. Perhaps you can create a new issue for it? :)

**Comment by kbhardwaj123** [comment]
@misaochan sure I'll do that right away
