### ISSUE TITLE
No location, despite EXIF and settings (failed+retried upload))

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3421]
![Screenshot_20200219-100344_Gallery](https://user-images.githubusercontent.com/99590/74792092-ba107400-52ff-11ea-8659-8c6134e899e1.jpg)
![Screenshot_20200219-100400_Commons](https://user-images.githubusercontent.com/99590/74792114-c399dc00-52ff-11ea-80ac-6d0ee7ed3398.jpg)
![Screenshot_20200219-100415_Commons](https://user-images.githubusercontent.com/99590/74792122-ca285380-52ff-11ea-96d7-4f6c8957cf05.jpg)

2.12.3.583~af97e40

**Comment by misaochan** [comment]
Could you link to the page on Commons please?

**Comment by nicolas-raoul** [comment]
Sure :-)
https://commons.wikimedia.org/wiki/File:Construction_in_Shibuya,_crane.jpg
It seems reproducible: https://commons.wikimedia.org/wiki/File:Tai_Chi_Chuan_building.jpg
A picture whose upload did not fail has correct information: https://commons.wikimedia.org/wiki/File:Hatanodai_Station.jpg

**Comment by misaochan** [comment]
Oh I see, so the issue lies with "retry". https://commons.wikimedia.org/wiki/File:Construction_in_Shibuya,_crane.jpg has coordinates in the EXIF metadata on its file page though, just not in the summary template, which is why we aren't fetching it in the app. But we need to figure out why the summary template coords are missing.

Btw do you know if the upload failed recently, and if so, was there a known reason for the failure (e.g. network issue)? We were hoping that failed uploads caused by the app were fixed...

**Comment by nicolas-raoul** [comment]
These uploads failed because there was no Internet :-)

**Comment by maskaravivek** [comment]
My first guess is that we are not persisting EXIF metadata in the Contributions database.

**Comment by misaochan** [comment]
> My first guess is that we are not persisting EXIF metadata in the Contributions database.

Possibly, but I don't think that is the sole problem, since the location template was not sent in Nicolas's example (the "location" field in the file page's summary is empty, whereas EXIF metadata at the bottom of the page exists)
