### ISSUE TITLE
LoginActivity Hides the keyboard if I try to advance focus from Username to Password

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3453]
**Summary:** 

I entered a username, pressed the `next field` affordance, focus advanced to password but the keyboard was hidden so I had to press on the password field to start typing

**Steps to reproduce:** 

Tap on username textview and then use next.

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?
What Android version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?
Is it the stock version from the manufacturer or a custom ROM ?
 
**Commons app version:** 

master & betaDebug

**Would you like to work on the issue?**

sure

**Comment by Glitch101** [comment]
`LoginActivity` is acting quite weird. When the activity starts, [the focus should go to](https://github.com/commons-app/apps-android-commons/blob/15bccdf650f76b9367865f15a7054824537b8200/app/src/main/res/layout/activity_login.xml#L109) the `username` field since we are doing `<requestFocus/>` in it (considering I am right about what `<requestFocus/>` does) but that's not happening as well. I have tried several things but nothing works. Although I have made a workaround for this issue programmatically but I am looking for a better solution.

**Comment by macgills** [comment]
watch out for those `@OnFocusChange` listeners, I would delete those and test it all out
