### ISSUE TITLE
Issue with gitignore

### ISSUE THREAD

**Issue by ashishkumar468** [commons-app/apps-android-commons#3532]
**Summary:** 

gitignore includes not to ignore files with path 
-!/.idea/codeStyles/
because of which .idea/codeStyles/Project.xml shows up in changed files

 
**Commons app version:** 

Current master

**Would you like to work on the issue?**
Yes

**Comment by macgills** [comment]
We need to address the fundamental issue of why people are not realising that AS has changed a file or why AS is changing the file.

For people not being aware of their changes I generally recommend using a git client, sourcetree/gitkraken because the ui is a lot friendlier
![image](https://user-images.githubusercontent.com/3358282/76842624-74799500-6832-11ea-981d-92b2393fbdc9.png)


As to why AS is changing it it could be that this happens only on import, or it could be that people are running different version of AS than me, I am on 3.6.1. The codestyle should not change unless a person changes it

As a last desperate measure we could just change the codestyle as I think it seems most people have problems with the c# section which obviously we don't care about

**Comment by sivaraam** [comment]
> As to why AS is changing it it could be that this happens only on import, or it could be that people are running different version of AS than me, I am on 3.6.1. The codestyle should not change unless a person changes it

As we're seeing cases where AS is messing with the codeStyle itself, I think we can look into alternatives assuming it's hard to figure out why AS is modifying the file. Is there any reason not to use alternative options such as [checkstyle](https://checkstyle.sourceforge.io/) to check for code style? I've seen the Wikipedia app use it for their [project code styles](https://github.com/wikimedia/apps-android-wikipedia/tree/master/gradle/src). There's even another issue about integrating the spotless plug-in for the code style: #3405

**Comment by macgills** [comment]
checkstyle has poor automatic formatting support if memory serves and it is only for java so it doesn't really matter to me much.

Spotless could be okay, its general purpose-ness gives me cause for doubt. Personally haven't used it.

This should be an important lesson for new contributors to learn anyhow "Don't commit something you didn't change".

I'd rather figure out why AS is changing the file, is it happening for anyone on this issue?

**Comment by misaochan** [comment]
Yes, it happens for me on AS 3.6.1.

**Comment by macgills** [comment]
@misaochan can you commit the changes to `Project.xml` a branch and I can try switching to it to see what happens for me?

**Comment by misaochan** [comment]
https://github.com/misaochan/apps-android-commons/tree/Project-xml-debugging

**Comment by Glitch101** [comment]
Happened with me as well on Android Studio 3.6.1

**Comment by macgills** [comment]
looks like I am the problem I would say https://stackoverflow.com/a/34628619 I turn off a lot of these plugins because they slow down build time

**Comment by macgills** [comment]
Who wants to open a PR to update the codestyle?

**Comment by macgills** [comment]
I'll open a PR so

**Comment by Glitch101** [comment]
> I'll open a PR so

I can take this up but I didn't respond since I am really not sure how to patch this up :sweat_smile:
