### ISSUE TITLE
Automatically add main category when uploading from Nearby map/list

### ISSUE THREAD

**Issue by VojtechDostal** [commons-app/apps-android-commons#3595]
Many items are already linked to their main Commons category via sitelink and/or Commons category property. It would be fantastic if we could add this category to the images automatically (or somehow suggest it to the uploader). 

This wasn't very interesting before we started also showing pins for objects which are already photographed. These already photographed objects have a higher probability of already having a Commons category. Now, we can display these too and thus automatic addition of this main category would be very helpful, especially for beginners.

**Comment by nicolas-raoul** [comment]
Here is the most current behavior:
- If you upload from Nearby, then the item will be suggested as a depiction.
- In turn, if you select a depiction, then the linked Commons category will be suggested as a category.

I think that it is enough :-) Don't you think so?

**Comment by VojtechDostal** [comment]
Why is the commons category suggested only if depiction is selected?
I guess the category is highly desirable any time a picture is uploaded to an item from Nearby, isn't it?

**Comment by misaochan** [comment]
Hmm. I guess in the ideal scenario, the suggested depiction will be correct, and the user will select it, and therefore the category will also be selected. In the case of the suggested depiction being wrong (or the user skipping the depicts step), the user will not select it, in which case do we still want to display the category suggestion?

I guess my personal opinion would be "yes", since it is after all just a suggestion and they can disregard it if they want.

**Comment by nicolas-raoul** [comment]
> Why [...]?

Because it was easier to implement from a source code point of view ^_^
Suggesting the category even if the user did NOT select the depiction is doable but it is one more small complexity on top of all of the others.

Actually, my personal point of view is that the user should not be able to deselect the item in depictions (_after all, if that image represents the item, it must depict it_). In that implementation scenario, the category would be always suggested.

**Comment by VojtechDostal** [comment]
I agree that user should not be able to deselect the item in depictions :). The selection of the pin in Nearby map should be enough to qualify for a depiction tag... and also the commons category suggestion.

**Comment by nicolas-raoul** [comment]
I just created #5317 containing the conclusion of our discussion here. Thanks! :-)
