### ISSUE TITLE
[structured-commons] Wrong thumbnails at the "depictions" step when uploading

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3601]
Steps to reproduce:
1. Open "Explore"
2. Tap the search icon
3. Enter "rabbit"
4. Tap "Items"
5. Thumbnails are showing correctly in this activity, as you can see
6. Now get back to the home of the app, ans tap the "+" to start uploading an image
7. At the "depictions" step, type "rabbit"
8. Problem: For the item "Rabbit (species of small mammals)", the thumbnail for "Rabbit (basketball player)" appears:

![Screenshot_20200327-193013_Commons](https://user-images.githubusercontent.com/99590/77873172-29c13980-7284-11ea-8b68-a2abe3a576de.jpg)

Please fix it by looking at how it is done in the Explore activity. Factorize code if you can (that can be another pull request though).

**Comment by dafnith** [comment]
Hey, can I take this one?

**Comment by nicolas-raoul** [comment]
@dafnith Yes sure :-)

**Comment by nicolas-raoul** [comment]
@dafnith Any progress on this? :-)

**Comment by dafnith** [comment]
@nicolas-raoul Yes I have managed to reproduce the issue. Actually it took me a while to built correctly the project but now everything is ok and I am working on the issue.

**Comment by dafnith** [comment]
hey @nicolas-raoul I think I may have misunderstood the problem here. When I type rabbit in step 2 of upload, for the item "Rabbit (species of small mammals)", various wrong thumbnails appears and not only the "Rabbit (basketball player)". I don't understand if the problem is specifically with the basketball player error or the fact that it doesn't show the right image for "Rabbit (species of small mammals)".

**Comment by nicolas-raoul** [comment]
Rabbit is only an example :-)
You are right, most (maybe all?) thumbnails are erroneous.

**Comment by dafnith** [comment]
Thank you, I will check it out!

**Comment by macgills** [comment]
@dafnith are you still working on this? I have availability currently if you are happy for me to take over

**Comment by dafnith** [comment]
@macgills I was working on this but I find it hard to solve it. You can take the issue and I will be happy to see the solution.

**Comment by nicolas-raoul** [comment]
Dafni, if possible please share how you investigated, what did not work,
things that you have checked, possibilities that you have ruled out. Thanks
🙂

Le mar. 21 avr. 2020 à 21:40, Dafni Theodorou <notifications@github.com> a
écrit :

**Comment by dafnith** [comment]
Here is the relative paths of some classes I investigated:

- fr/free/nrw/commons/upload/depicts/DepictsPresenter.java
- fr/free/nrw/commons/explore/depictions/SearchDepictionsFragmentPresenter.java

In the DepictsPresenter class I tried to change fetchThumbnailForEntityId() method to be the same as fetchThumbnailForEntityId() of class SearchDepictionsFragmentPresenter.
That didn't work for me.

Then by debugging the app I navigated in many classes that are used in order for the depictions to be fetched but I couldn't find the way that the query was sent to the provider.
I wanted to check if the query and the data returned were correct. I could not find where these steps occurred and this is were I got stuck.

I would be more than happy if anyone could explain this to me!

**Comment by macgills** [comment]
I'll let you know when I understand it myself!

**Comment by macgills** [comment]
@dafnith the problem was 2 essential points

1.The adapter was not using fresco properly
1.When we were fetching image urls we were relying on position in the adapter which is incredibly error prone as we cycle through many data sets while the user types out a phrase so it would set the image url for position 1 for "rab" to the item at position 1 for "rabbit" depending on the order of web requests which can never be relied upon

**Comment by dafnith** [comment]
Thank you for the explanation! 🙂
