### ISSUE TITLE
Failure stays after retry succeeds

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3698]
Latest master 67faa40d8c8c6de5c46ab75a4b686e0aecab0fc5
![Screenshot_20200423-142748_Commons](https://user-images.githubusercontent.com/99590/80062619-219ca700-856f-11ea-9fd8-958231cdd75e.jpg)
Even after killing and restarting the app.
The "failed" one should not appear.

**Comment by macgills** [comment]
This touches on the rather nebulous subject of how we handle upload failure

This list represents 
1. our local contributions
2. contributions fetched from the server

When Uploading a Contribution we
1.Upload it to the stash
1.Upload it from the stash
1. Mark it as complete
1. Add wikidata properties and captions

I would say this failed at step 2? And because of that if you retried this it would fail almost instantly because it already has an image in the stash

What we really need is a system to upload where we can recover from an error at any phase and additionally we shouldn't show a remote contribution if our local copy reports an error state.

**Comment by ashishkumar468** [comment]
@nicolas-raoul Are you still seeing this issue on the latest release branches?

**Comment by nicolas-raoul** [comment]
I have not tried recently.

**Comment by ashishkumar468** [comment]
Hmm, I can't seem to produce this, can you verify this please?

**Comment by nicolas-raoul** [comment]
I will reopen if I see that again :-)
