### ISSUE TITLE
In "About", remove the language selection menu of the "Translate" link

### ISSUE THREAD

**Issue by maskaravivek** [commons-app/apps-android-commons#3715]
When I mentioned "mobile-friendly", I actually was thinking of a mobile website like experience e.g., like Commons' mobile website. That's what I would call mobile-friendly. I think you're lucky that the desktop site itself appears to be mobile friendly in your device. It's not usually the case, though :)

Having clarified that, I actually think I did a mistake by mentioning the mobile unfriendliness of the website as a point when I was not even proposing to remove the "Translate" link altogether. So, apologies for that.

> If we do not specify a language, user are directed to this page which looks horribly like an error page:

Isn't that more of a translatewiki's problem than ours? Do we show all the language list just to avoid this page? If yes, I would say it seems unnecessary. A better way to prevent this would be to suggest translatewiki to fix this on their side, for everyone's good!

Also, I think someone familiar with translating using Translatewiki would know enough to realise that it's not an error but just the page they are shown when the source and target are the same languages. So, I don't think we would doing any harm by just not specifying the language in the link.

To be clear, I'm suggesting to leave the language selection to translatewiki for 2 reasons:
1. To avoid the redundancy
2. Their language selection window is better in a lot of ways!. It's searchable. They even show suggested languages. It's familiar to someone who translates in translatewiki. etc.

_Originally posted by @sivaraam in https://github.com/commons-app/apps-android-commons/pull/3643#issuecomment-619424438_

**Comment by nicolas-raoul** [comment]
I totally agree with you that it is translatewiki's fault, and we should totally report it. My experience with translatewiki is that it is slow to move, its many UI faults have existed for like 10 years. You are right that people familiar with translatewiki will have no problem, but these are very few.

**Comment by sivaraam** [comment]
How about just specifying a language other than English in the link so that anyone who opens it won't get that unhelpful page which translatewiki shows when the source and target are the same?

Something like: https://translatewiki.net/w/i.php?title=Special:Translate&group=commons-android-strings&filter=!translated&action=translate&language=ab

I chose the language code `ab` as it's lexicographically the first language for which we have translation.

**Comment by nicolas-raoul** [comment]
Sounds reasonable :-)
If doing so, how about choosing a language that most of the world has heard of, for instance "Spanish"?

**Comment by sivaraam** [comment]
> If doing so, how about choosing a language that most of the world has heard of, for instance "Spanish"?

I didn't get into doing that as that could turn out to be a subjective decision for what's just a minor thing no one would care about (Google says Chinese is the most popular language). That's why I went the objective route of choosing the first language for which we have a translation.

I myself don't care about the language specified in the link, though. So, if you say we could just stick with Spanish I'll be glad to do the change that way :)

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul is this issue still relevant now?

**Comment by sivaraam** [comment]
It's still relevant because we haven't done away with the language selection menu for the "Translate" option. We could call this issue done when we remove the language selection dialog that appears upon clicking "Translate". In place of that, "Translate" should just point to a translatewiki link like the following which specifies a particular language:

https://translatewiki.net/w/i.php?title=Special:Translate&group=commons-android-strings&filter=!translated&action=translate&language=ab

**Comment by nicolas-raoul** [comment]
The languages menu is still there but has a mismatch, it shows a language different thbn the oe selected: Afrikaans shows Suomi, Esperanto shows asturianu, etc. I am OK with removing the menu.

**Comment by nicolas-raoul** [comment]
Menu has been removed.
