### ISSUE TITLE
Refactor and convert CategoryPresenter to kotlin

### ISSUE THREAD

**Issue by macgills** [commons-app/apps-android-commons#3734]
**Summary:** 

Current usage is difficult to change and non idiomatic Rx.

**Would you like to work on the issue?**

Yes

**Comment by sivaraam** [comment]
I'm re-opening this as I believe the conversion introduced a bug. The converted version [lower-cases the search word](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/category/CategoriesModel.kt#L94) before sending it to the `allcategories` API. I'm not sure why that's done. Anyways, as detailed in [my comment](https://github.com/commons-app/apps-android-commons/issues/3179#issuecomment-605466529) in #3179 that the API is case-sensitive so lower-casing effectively [reduces the category search space](https://github.com/commons-app/apps-android-commons/issues/3179#issuecomment-605466529) to only those categories with a lower case. I certainly think we don't want that. So, why are we lower-casing the search keyword? Was this done by accident?

_side note: This issue is intriguing me. For the second time, I discover this mistake when looking for something else._

**Comment by sivaraam** [comment]
On a related note, I also think there's not much benefit in [lower-casing the words](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/category/CategoriesModel.kt#L130) sent to the [`search` API](https://www.mediawiki.org/wiki/API:Search) either. The algorithm used by `search` API is more clever than the simple prefix only search done by the `allcategories` API. You could read more about it here: [Help:CirrusSearch - MediaWiki](https://www.mediawiki.org/wiki/Help:CirrusSearch).

**Comment by misaochan** [comment]
Yes, it sounds like we should remove the `toLowerCase()` call.

**Comment by ashishkumar468** [comment]
Seems like a small fix, raising a PR soon after verifying locally

**Comment by sivaraam** [comment]
@misaochan Just a reminder that we might want to ensure that we fix this before the corresponding change goes into production.

**Comment by misaochan** [comment]
Hi @ashishkumar468 , did your PR go through? I can only seem to find the commit on your fork.

**Comment by ashishkumar468** [comment]
@misaochan I have raised a PR for the same on master, 2.13 anyways did not have the original change
