### ISSUE TITLE
Media details do not show depiction

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#3752]
I uploaded a file and set a depiction to it.
The depiction was correctly uploaded, but is not visible in the app even after trying several times on wifi:
![Screenshot_20200518-231627_Commons](https://user-images.githubusercontent.com/99590/82223288-6db7ed00-995d-11ea-9129-b82f7c400028.jpg)
https://commons.m.wikimedia.org/wiki/File%3AMouillette.jpg

Strangely it works fine for this other picture uploaded like an hour before, with the same app version: https://commons.m.wikimedia.org/wiki/File%3APink-yellow_strawberries_in_Tokyo.jpg

**Comment by macgills** [comment]
![image](https://user-images.githubusercontent.com/3358282/82454506-c5fc0580-9aa9-11ea-8549-d0b5aedf8e10.png)

I just uploaded this and it seems fine?

I can't seem to find mouilette when searching in the app, is there an easy way for me to view this item in app to debug the requests?

**Comment by nicolas-raoul** [comment]
You can find it in Explore at the bottom of the list. By the way, there are two "L" characters:
![Screenshot_20200521-001444_Commons](https://user-images.githubusercontent.com/99590/82463644-0b472400-9af8-11ea-9111-2a42cd65617b.jpg)

**Comment by macgills** [comment]
The problem was fetching the depiction labels, the web request asks for a language, in this case "en" and no such entry exists for a few of these so we got an empty list which resulted in the throwing of an exception.

What is confusing me is this parameter to the endpoint

![image](https://user-images.githubusercontent.com/3358282/82541809-efb83980-9b48-11ea-8311-916acd624157.png)

Which sounds like it should help give a result but only works in specific scenarios instead of defaulting to something.

Anyway I am pushing a fix
