### ISSUE TITLE
Available for volunteering on an Android project

### ISSUE THREAD

**Issue by VibhorChinda** [commons-app/apps-android-commons#3871]
Hii everyone. I am Vibhor Chinda.
I wanted to make contributions to any Android related project. Thus i am open for volunteering on an Android Project.

I have skills in the domain of Android and can write android related code in both java and kotlin. I am keen to make contributions to any android related project. 

My reasons for contributing in project is that it can help me to learn and grow my skills. As I know Open source can be the best way to enhance my skills in a particular domain.

Thanks @ashishkumar468 for suggesting me to introduce myself here. 
Please guide me how can I help and make contributions. @misaochan

**Comment by misaochan** [comment]
Welcome, @VibhorChinda ! :) You can look in our issues for the "good first issue" or "bug" labels, those are good places for a new contributor to start. Please also read https://github.com/commons-app/commons-app-documentation/blob/master/android/Contributing-Guidelines.md , if you haven't yet.

**Comment by VibhorChinda** [comment]
Thank you. Will surely have a look :)

**Comment by nicolas-raoul** [comment]
Hi @VibhorChinda :-) 
Did you find some good issues to fix?

**Comment by VibhorChinda** [comment]
Yes I have one issue assigned to me will probably start working on it next week. Was not able to give time due to college exams and some health related issues.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul this issue is useless you can close this

**Comment by misaochan** [comment]
@Rishavgupta12345 that is not a nice thing to say - we pride ourselves in being inclusive and welcoming towards all new contributors to open source.

That being said, this issue was opened a long time ago, and we have since changed the guidelines for new issues, so I will go ahead and close for this reason. @VibhorChinda if you ever return and need help, please feel free to create a new issue with the "Help Wanted" template. :)
