### ISSUE TITLE
Other pictures flickers when a media is selected from contributions list

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#3879]
**Summary:** 
I always knew I was seeing flickering images when I choose an item from contrib list and trying to go to Media Details Fragment. While I was testing another bug, I recognized on click to an object from contrib list, rebuildCatList method from MediaDetailsFragment is called for previous images too. And I see previous image is appeared during my debug steps. 

This issue should be investigated.

**Comment by misaochan** [comment]
Pinging @ashishkumar468

**Comment by ashishkumar468** [comment]
Hey @neslihanturan Are you still facing this issue?

**Comment by vinayak0505** [comment]
yes, this problem is still there and will stay there as viewpager is used and what is happening here is you if click on first item then it should be okay and no flickering will occur but when going to 2nd and beyond there is also a scrolling part taking place, what we can do here is adding a smooth scrolling so it looks nice plus user will able to get to know that they can scroll left and right.

**Comment by vinayak0505** [comment]
can i work on this issue

**Comment by vinayak0505** [comment]
please check Fixes #3879 #4334
solved this issue also added a little animation when opening detail screen and going back (because it looks like that was the developer trying to do while adding delay) and also minor optimization to code repetition and if else statement.
let me know if you want me to remove the animation

**Comment by nicolas-raoul** [comment]
@vinayak0505 Would you mind removing animations from this screen? Thanks! In particular I observe that in the latest master branch, when opening the app the contributions appear from the right. While animation can be good sometimes, making the main content appear from the side when starting the app is not good: the content should appear immediately. I think we should remove animations from this screen as it is quite bug-prone.

**Comment by vinayak0505** [comment]
okay so the real problem is viewpager get the complete data , not just for the single screen , so when you click on an item it takes time to load therefore the app crashes with error code like expected pager adapter count 60 found 70 pager id(its weird why there always a gap of 10 and also i am not able to reproduce this error as its not crashing on my device), so someone came up with the solution that we sould load the 1st item in adapter, wait for 5 millisec and then go to the item selected with causes flickering , the app was not crashing most of the time as it would wait for 5 millisec and if the dataloads bingo if not then the app is like its your problem , creating a method that can notifiy when the data loading is complete or removing viewpager with normal detail screen or atleast converting it to viewpager 2 , what i am soing now is creating a background thread looping till the data loads to the selected item and when it does it will it go to that page(rather than just waiting for 5 millisec), ill make a pull request , i have tried loading 80 images and i still dont face any issue so youll have to test this if this works it will also close the bug #4283

please check #4336 i am not able to reproduce this error of crashing so i have only solve them using the error you are telling and logcat you send, so you will have to test it on your device

**Comment by vinayak0505** [comment]
Thanks @nicolas-raoul
