### ISSUE TITLE
Agree just once in Settings that these are my images

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#3977]
When uploading images we have to agree that this is my work etc. each time.

Perhaps we can agree just once in Settings?

**Comment by sivaraam** [comment]
Interesting idea. I'm guessing whether that's feasible though. I presume it's legalese that the app is required to show similar to how there's a "Release rights" section in Special:UploadWizard.

**Comment by jidanni** [comment]
I can't think of any law that says agreeing to agree each time is not the same as agreeing individually. If so, then even agreeing individually could be presumed not agreeing enough.

**Comment by nicolas-raoul** [comment]
As we are not legal experts, we just blindly do the same as the Upload Wizard.
I imagine that the Upload Wizard does that because if there was a one-time settings a user could say they have tapped it by mistake, and require Commons to remove all of their images. With a dialog each time, no user can say they tapped it by mistake every time.
I will close this until the Upload Wizard changes how they do this.
