### ISSUE TITLE
Location permission setting does not match its title

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#3987]
There is a setting called display location permission. And below it we see it says ask for location permission. So maybe the title should also say that instead.

 Also it is not clear what'll happen if the user turns it off.

**Comment by nicolas-raoul** [comment]
What do you suggest for the label and secondary text of that setting?
Please read the conventions first: https://material.io/design/platform-guidance/android-settings.html#label-and-secondary-text
Thanks! :-)

**Comment by jidanni** [comment]
Hmm, I see in #4008 I made some guesses about what it should say.

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul @4D17Y4 we have better strings for display location permission now and this issue is already solved, we are using ask for location permission now which is sufficient so we can close this issue .

we have many issues open in this repository which is actually not present, I am cleaning the repository by informing

**Comment by nicolas-raoul** [comment]
This seems solved in master? @jidanni if not please post a screenshot and let us know, thanks!

**Comment by Rishavgupta12345** [comment]
> This seems solved in master? @jidanni if not please post a screenshot and let us know, thanks!

@nicolas-raoul  you can self check it easily go to the settings scroll down and you will see a ASK FOR LOCATION PERMISSION option , this option had a different name previously which was not soo clear but now it is perfect so we can close this issue
