### ISSUE TITLE
Thoughts on workflow proposal?

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#407]
Now that we have more active devs, @nicolas-raoul has posted a suggestion at https://groups.google.com/forum/#!msg/commons-app-android/vXlvbV2PZRY/8bOYHpusAAAJ regarding a proposed workflow for the team. Please chime in and let us know what you think. :) @domdomegg @veyndan and @maskaravivek , we would appreciate your thoughts in particular. If everyone is on board with it, we might try to start implementing within the next week or so.

(This will only apply to the app repo, it is entirely up to @tobias47n9e if he wants to do the same for the website repo, since there are fewer active devs there.)

**Comment by veyndan** [comment]
I think that the proposed workflow is a really good idea

**Comment by domdomegg** [comment]
Sounds good to me

**Comment by maskaravivek** [comment]
Sounds good to me too. How will be the role collaborator awarded. Will active contributors be made collaborators later. What is expected of them to get to that point.

**Comment by nicolas-raoul** [comment]
@maskaravivek At the AnkiDroid project, the decision to make people collaborator is taken arbitrarily by the current project leader (often after consultation with the existing collaborators), but usually the decision is based on how long the developer has been around, the frequency/usefulness/quality of their commits, and whether more reviewers are needed or not.
Maybe we should use the term "reviewers" instead of "collaborators", since it is what it really is about, and to sound less elitist from the point of view of the other developers?

**Comment by domdomegg** [comment]
I think reviewer is a better term

**Comment by misaochan** [comment]
Thanks for your input, all! Much appreciated.  :)

@maskaravivek I think people who stick around for some time and submit multiple substantial patches would make good candidates for new collaborators/reviewers.

**Comment by misaochan** [comment]
"Reviewers" sounds good to me. Are we able to change that in the actual Git user management tool, or is it just the term that we will use conversationally?

**Comment by nicolas-raoul** [comment]
Github groups various roles into that term, and we can not change the term
in the Github interface, so I suggest saying "reviewers" in discussions and
in the workflow explanation.

**Comment by misaochan** [comment]
Done. Workflow posted [here](https://github.com/commons-app/apps-android-commons/wiki/Project-maintenance).

**Comment by misaochan** [comment]
Closing this unless further issues.
