### ISSUE TITLE
Up-for-grabs, awesome-for-beginners and others

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#412]
Could be a good idea to add this repo to lists to get some more contributors on the team.

Many lists require a tag for beginners and the new <s>`for beginners`</s> `beginner friendly` one could be quite good - we might need some more issues though for beginners to try though!

**Comment by misaochan** [comment]
Great idea @domdomegg , please feel free to add to any lists that you think is appropriate.  I changed the label to "beginner friendly" at Nicolas's suggestion, but the essence is the same. :) I think some of the  existing tasks could potentially fit the label, but will have to go through them and see.

As a side note, to get new contributors, we might want to consider adding our project to the potential projects in GSoC, Outreachy, or Google Code-In. We need people who are willing to act as mentors if we do, though. I am hesitant to volunteer for this round's GSoC since I will be traveling during the middle of the year, but might put something up for Outreachy in Nov.

**Comment by domdomegg** [comment]
Done - will close now and follow up on them and potentially reopen this issue if they aren't merged within 48 hours

https://github.com/up-for-grabs/up-for-grabs.net/pull/614
https://github.com/MunGell/awesome-for-beginners/pull/94
