### ISSUE TITLE
A display issue with fonts in login screen

### ISSUE THREAD

**Issue by franklinbill** [commons-app/apps-android-commons#4131]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text overlap each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.
App version is 2.13.2, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.

_Before creating an issue, please search the existing issues to see if a similar one has already been created. You can search issues by specific labels (e.g. `label:nearby`) or just by typing keywords into the search filter._

**Steps to reproduce:** 

How can we reproduce the issue? 
**_font size and display size are the largest ! ! !_**

What did you expect the app to do, and what did you see instead?
I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.

**System logs:**

```
Add logcat files here (if possible).

Need help? See https://github.com/commons-app/apps-android-commons/wiki/Getting-app-logs-from-Android-Studio
```

**Device and Android version:** 

What make and model device (e.g., Samsung J7) did you encounter this on?
Google nexus 6
What Android version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?
Android 8.0
Is it the stock version from the manufacturer or a custom ROM ?
 
**Commons app version:** 
2.13.2

You can find this information by going to the navigation drawer in the app and tapping 'About'. If you are building from our codebase instead of downloading the app, please also mention the branch and build variant (e.g. master and prodDebug).

**Screen-shots:** 
<img width="445" alt="bugcommons" src="https://user-images.githubusercontent.com/18572115/103147438-0df5b000-4790-11eb-846f-0d40de081e13.png">

Can be created by pressing the Volume Down and Power Button at the same time on Android 4.0 and higher.

**Would you like to work on the issue?**

Please let us know whether you want to fix the issue by yourself. If not, anyone can get the issue assigned to them.

**Comment by Aditya-1295** [comment]
Can I work on this issue ?

**Comment by Saral-code** [comment]
I would like to work on this issue.
Please assign me

**Comment by misaochan** [comment]
@Saral-code It is yours. :)

**Comment by Saral-code** [comment]
Hello, 
So what I observed with this issue are as follows:
1. This issue occurs only when I set your font as EXTRA LARGE in my mobile (I use realme 3 pro)
2. On top of that the dpi level should be less than 330 
(very rare configuration )
3. With these setting most of the well built apps perform pretty badly like youtube, whatsapp, facebook,etc. (font cutting and layout overlapping can be observed).
4. To fix this issue only solution that i can think of is scrollview (as suggested by @franklinbill ) (i.e. changing the complete layout and many other files linked with `activity_login.xml`.)
5. I tried changing layout dimensions but it is not working because with large font and low dpi the display is already filled, changing layout dimension doesn't changes anything, although makes the condition worse.

So @misaochan should I proceed with changing the complete layout of login activity or find an alternative?

**Comment by misaochan** [comment]
Many thanks for your investigation @Saral-code . Let me ping @neslihanturan for her thoughts. You can feel free to take a look at another issue in the meantime, while we decide on a solution. :)

**Comment by Rishavgupta12345** [comment]
@nicolas-raoul  @4D17Y4 this is not an issue any more we have perfect working Ui now and so we can close this issue now

**Comment by nicolas-raoul** [comment]
Looking fine even with big font indeed:
![adb](https://user-images.githubusercontent.com/99590/157007073-62cf74cb-17f6-44e1-a0c6-f5ba1aec34f1.png)
