### ISSUE TITLE
ACRA crash reports do not display the version name in body again

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4173]
Crash reports need to have version name in body for easy filtering, not in the .stacktrace file.

**Comment by ashishkumar468** [comment]
This seems to be a problem with Gmail https://github.com/ACRA/acra/issues/744

**Comment by ashishkumar468** [comment]
https://github.com/MindorksOpenSource/CrashReporter, seems fairly simple to implement, should we try it out?

**Comment by neslihanturan** [comment]
Hey @ashishkumar468 , do you mean instead of ACRA?

**Comment by misaochan** [comment]
I reckon that it would be instead of ACRA, no point in having 2 different crash report libraries IMO. 

Personally I am a bit hesitant to switch, since ACRA seems to be significantly more popular and commonly-used. But ACRA has also said in Ashish's link that they will not be working on the issue since they perceive it to be Gmail's responsibility. So if we test and find out that Mindorks works well (and does solve the problem), it could be worth trying it.

**Comment by madhurgupta10** [comment]
@misaochan I found out that this issue may be due to this particular change in API 29+ (https://developer.android.com/training/sharing/send#adding-rich-content-previews) I checked the internal implementation of the source code of ACRA and it seems like that they have already implemented this, so I upgraded to 5.8.1-beta11 and this brings back the missing body for Gmail, I also checked it with Yahoo Mail and it works for me.

Let me know if I should proceed with this version upgrade and make a PR.

**Comment by misaochan** [comment]
@madhurgupta10 Nice! Yes, please go ahead and do that thanks. :)
