### ISSUE TITLE
Need to turn off audio

### ISSUE THREAD

**Issue by pigsonthewing** [commons-app/apps-android-commons#4189]
Please provide an option , in settings, to turn off the audio alert notification that an upload has started (and any other audio alerts).

**Comment by Roshan13046** [comment]
Unable to hear any notification alert.
Can you please provide steps to reproduce?

**Comment by pigsonthewing** [comment]
> Unable to hear any notification alert.
> Can you please provide steps to reproduce?

Upload a photo.

As upload starts, app gives an audible notification.

**Comment by nicolas-raoul** [comment]
@pigsonthewing Thanks for reporting! What version of Android are you using? Would you mind reading https://github.com/commons-app/apps-android-commons/issues/2528 and telling us whether this describes what you are experiencing? If not, would you mind detailing what is different? It might be an old issue that we are having trouble reproducing. Thanks!

**Comment by pigsonthewing** [comment]
> What version of Android are you using? 

I have a OnePlus Nord, so I'm using OxygenOS, v. 10.5.10.AC018A - https://en.wikipedia.org/wiki/OxygenOS

> Would you mind reading #2528 and telling us whether this describes what you are experiencing? 

Seems to be, though I can't speak to the error logs.

**Comment by nicolas-raoul** [comment]
The app does not willingly call any instruction to make a sound, so there must be some kind of bug deep inside one of the libraries we are using which affects only some devices/OSes.
I added your information to #2528, and will close this issue so that all investigation can be focused in one place.
Thanks a lot for using the app, and sorry for the inconvenience!
