### ISSUE TITLE
Make fetching of csv as a separate function

### ISSUE THREAD

**Issue by nextLane** [commons-app/apps-android-commons#425]
Since its a fetching call from internet, it must be surrounded by appropriate try, catch clauses and cases that cover no connection or poor connection for web cases.

**Comment by domdomegg** [comment]
Are you referring to line 30 in [`NearbyPlaces.java`](https://github.com/commons-app/apps-android-commons/blob/master/app/src/main/java/fr/free/nrw/commons/nearby/NearbyPlaces.java#L30)?

Could you copy over any relevant stacktraces from the Google group so that we can see what might need extra patching? Thanks :)

**Comment by misaochan** [comment]
I'm happy to merge if anyone wants to do this, but would like to reiterate that there are plans to remove the fetching of the CSV entirely in favour of a Wikidata query, in the near future (~2 months or so). So while patches would still be welcome, please understand that any work done on this is likely to be overwritten within that time frame (we would still need try-catch blocks, but the code in NearbyPlaces.java will likely change so much that we won't be able to keep much of anything).

**Comment by nextLane** [comment]
@domdomegg  Yes, indeed. Everytime we click on nearby the get() method is called that tries fetching the file. Ideally, this should be handled by a separate function, with suitable cases to check internet/GPS connectivity.

**Comment by misaochan** [comment]
Think we can close this, given the Nearby overhaul?
