### ISSUE TITLE
Image Dimensions should be reduced if too large.

### ISSUE THREAD

**Issue by 4D17Y4** [commons-app/apps-android-commons#4266]
**Summary:** 

If the dimension of the image is large, particularly if the length of the image is more than the screen size, then on opening the media details of the image, the image covers the whole screen making the image description visible only on scroll.

**Steps to reproduce:** 
* Upload an oversized image ( go for a full length screenshot )
* Tap on the image to see the media details.
* You'll notice that image descriptions are not visible initially, and you have to scroll to get to the description.

What did you expect the app to do, and what did you see instead?
Some part of description should be visible.

**Device and Android version:** 
Nokia 6.1+ android 10.
 
**Commons app version:** 
3.0.0 debug master.

**Would you like to work on the issue?**
Yes.

**Comment by 4D17Y4** [comment]
To add to the issue, 
we can notice that some part of the image is not visible  even on scroll if it is sufficiently large.

I think we should add an upper bound on the length of the image and adjust it's dimensions if it exceeds this bound.

@nicolas-raoul , @misaochan  for suggestions.

**Comment by nicolas-raoul** [comment]
Tip for anyone trying to reproduce the issue, here is a very high/narrow image: https://commons.wikimedia.org/wiki/File:Adolphe_Millot_carotte_longue.jpg . In media details you only see the top of the image, you have to scroll the equivalent of a few pages to reach the metadata, and the bottom of the image is never visible.

If the image is too high, I think it is a good idea to display it reduced (while keeping the aspect ratio), so that the displayed image's high is reasonable and the whole image is visible.
