### ISSUE TITLE
"Is this a picture of ...": Not too clear about which image it is asking me about

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4296]
Here I am uploading several images at one time. It (latest alpha) is asking me a question about one of those images or perhaps many of those images but the image it is asking me the question about does not appear. Therefore I'm not sure exactly which image(s) it is asking me a question about.

![Screenshot_20210320-164607.jpg](https://user-images.githubusercontent.com/1230959/111864536-6659d980-899c-11eb-92eb-230763f3753a.jpg)

Perhaps this is an intermittent race condition hard to reproduce.

Or maybe my Android setting of largest font is causing this. However older users need larger fonts.

**Comment by nicolas-raoul** [comment]
I confirm that this is an issue when uploading several pictures.
When that happens I just select "No", because I don't know for what picture the question is.

Maybe we could show a miniature?
Or only ask this question when the user reaches this picture's caption/description step, and let the user see the picture (as seen in @jidanni 's screenshot the picture is almost invisible even if it was the matching picture).

**Comment by Pratham2305** [comment]
Hey @nicolas-raoul, I would like to work on this. 
Yes, I think it would be better if this question asks when the user reaches the particular image, and also we can show a miniature image if the image is not visible properly as mentioned.

**Comment by nicolas-raoul** [comment]
@Pratham2305 Thanks it is yours! :-)

**Comment by Pratham2305** [comment]
@nicolas-raoul Can you review the #4308 PR, it would be easier to resolve this issue once that PR gets merged as the changes required for both issues are very much similar. Thanks!
