### ISSUE TITLE
Suggest categories based on entered filename

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#43]
Would it be smart to perform a category search on the file name (that the user just entered) and show a few matching categories (if any) below the nearby categories? Often people take care to write very descriptive names, so we could guess and potentially avoid the user a lot of typing.

**Comment by misaochan** [comment]
Could we potentially use "Method A" (the API that we used for flexible category search) to search for this?

**Comment by nicolas-raoul** [comment]
I guess yes :-)
Two calls to the same API makes for less code to maintain.

**Comment by misaochan** [comment]
This will need to be done asynchronously as well, I believe? I'm trying to decide whether to use Volley (similar to GPS category suggestions) or just AsyncTask (similar to MethodAUpdater).

**Comment by nicolas-raoul** [comment]
Good question.
We only get the name at a later stage, just when the user moves to the categories selection screen.
The best would be to do async and _add_ the results at the bottom of the existing suggestions.

**Comment by misaochan** [comment]
Still working on this, progress has been quite slow due to RL issues. Should hopefully be done in a week or so.

**Comment by misaochan** [comment]
Released in 1.37

**Comment by nicolas-raoul** [comment]
Strangely I can't seem to make it work:

1. Updated to 1.37
2. Chose picture
3. Entered file name "Nintendo sign at Tokyo branch in Taito"
4. The proposed categories did not contain anything related to Nintendo nor Taito.
5. Waiting some time does not change the proposed categories

Am I just unlucky? Could you give an example that works? Cheers!

**Comment by misaochan** [comment]
I tested the API directly with your title and nothing came up.

I think unfortunately the titles need to be short and succinct in order to produce results. Like 'lupins' or 'sashimi'. Basically, if the term doesn't work when you're using it in the category search (method A/prefix), it won't work for the title as well since the API query is the same.

IMO, ideally we would be able to extract keywords and then perform an 'or' search on those, but I'm not sure how we would go about that.

**Comment by nicolas-raoul** [comment]
I see! The search is more difficult than I first thought indeed.
Follow-up at #306
