### ISSUE TITLE
Allow uploading another version

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4305]
Here I am looking at one of my uploads. Not only is there no button to upload a another version, there is no button to go to the Commons website where there IS  button to upload another version. I am using the latest Alpha.
![Screenshot_20210325-152432.jpg](https://user-images.githubusercontent.com/1230959/112434404-844d8280-8d7e-11eb-98f3-ade90eff95c7.jpg)
(You see sometimes we have a better version of the same object, and we want to upload that.)

**Comment by jidanni** [comment]
There are plenty of buttons and links and everything as we scroll the page down. There's just no button to go to the commons website, or upload a newer version.

**Comment by jidanni** [comment]
Oh I see, the share button contains a link to the commons website. Okay then all that is missing is "upload another version."

**Comment by nicolas-raoul** [comment]
Overwriting a file is rather rare on Commons, in general people just upload as a new file.
While this feature indeed exists on the web UI, personally I would not consider it a priority nor even worth the maintenance burden.

Also, in the past we had bugs which were _accidentally_ overwriting files, so since then we keep an eye on overwriting statistics and when we see overwritings raising we know that there is a bug. Having an overwriting feature would make such bugs much harder to notice.

**Comment by jidanni** [comment]
OK, but how about a reasonable way to get to the file's Commons page?

**Comment by nicolas-raoul** [comment]
@jidanni Do not the three-dot menu contain a "View file page" button?
