### ISSUE TITLE
After switching to different account, contributions screen shows pictures of previous account

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4357]
1. Be logged into your usual account
2. Log out
3. Log into another account (which has never uploaded anything)
4. Expected: Contributions screen is empty. Actually: Showing 10 pictures from the usual account.

**Comment by Pratham2305** [comment]
Hey @nicolas-raoul, I think PR #4337  solves this issue too, but I am not sure about the #4286 as I am not able to reproduce the issue you guys are facing. Can you again test the PR with this issue? Thanks!

**Comment by vinayak0505** [comment]
@nicolas-raoul this is happening because at the time of logout the data is still being fetch so sometimes the images are stores in the table after the table is cleared, 
solution : every thing must be paused first when the logout is clicked and then the clearing of table must occur .
this will not only solve this problem but the problem with used seeing older contribution or no contribution when they login again problem as well

**Comment by nicolas-raoul** [comment]
Great find!

**Comment by obsidian-zero** [comment]
Sorry， if anyone work for this？ I want to have a try.

**Comment by nicolas-raoul** [comment]
@obsidian-zero Welcome to the project! :-)

@vinayak0505 Are you working on the issue, or can obsidian-zero take it based on your research work?

**Comment by vinayak0505** [comment]
Let him give it a try

**Comment by Prince-kushwaha** [comment]
@vinayak0505 you are working on this issue

**Comment by vinayak0505** [comment]
Someone else is assigned on it

**Comment by obsidian-zero** [comment]
> @vinayak0505 @obsidian-zero you are working on this issue ?
> 
> 

I'm terribly sorry for the delay.I have a lot of things to do during this time. It will take me about another week to be free. 
I think you can do it if you want.
