### ISSUE TITLE
Test Commons account for developers, with 200+ uploads

### ISSUE THREAD

**Issue by vinayak0505** [commons-app/apps-android-commons#4359]
**Summary:** 
A public account for developers, so that every developer can use that account to login and test issues with it

**Would you like to work on the issue?**
Yes!!

**Comment by nicolas-raoul** [comment]
Anyone needing this: Please contact me privately (my contact info should be [here](http://nrw.free.fr/)) explaining why you need it and for how long, then I will send you a username/password.

**Comment by vinayak0505** [comment]
Yes, I think rather then you giving you account, we can create a dev account open for everyone.

**Comment by nicolas-raoul** [comment]
No account can be open for everyone, due to vandalism.

**Comment by neslihanturan** [comment]
We usually don't need it when we have beta flavor, in which cases did you need this?

**Comment by vinayak0505** [comment]
Are you asking me? If yes , I didn't get you

**Comment by neslihanturan** [comment]
Yes I was asking to understand "What are the benefits of having a single public account for developers?". Can you explain why do you thing we need a public/shared account? We already have beta flavor. We use it for testing purposes.

**Comment by nicolas-raoul** [comment]
@neslihanturan I think this is useful when debugging scrolling issues on the contributions list. There was recently an issue occurring only when scrolling for a while, which means more pictures than a developer can upload in a reasonable time :-)

**Comment by vinayak0505** [comment]
Yes, so having a single account will make a things easy for new contributors  as they won't have to upload 200 pictures to find bugs or add improvements.
I believe there will many developers who can improve the app but are not willing to spend time in creating a different account and adding information only for testing purpose. Creating a single account will help in adding large amount of data and it will become easy to reproduce bugs.

**Comment by neslihanturan** [comment]
Hmm for the issues which requires bunch of uploads, it seems helpful indeed. Such an account can be exists only on beta debug (to prevent vandalism). However, I am some doubts about sharing login information publicly. Such an account can be an address for spammers.

**Comment by NotSoImportant** [comment]
In addition I think it would be helpful to have a process to allow uploading dummy pictures for test purposes. E.g. a certain category that will be cleaned regularely. This would be helpful to debug issues related to uploading, where I would not like to think about what to upload every time (might be many times).

**Comment by nicolas-raoul** [comment]
@NotSoImportant Such tests would pollute the production server, because even deleted files are not really 100% deleted. But don't worry, this use case is taken care of: I have thousands of acceptable pictures to upload that anyone can use for their test uploads ([link](https://drive.google.com/drive/u/1/folders/1T5wfM16qb78XCvnf1Zunww4neg8BXJj6)), and if for any reason this is inconvenient then the test server is available (just build the app's beta flavor).

**Comment by NotSoImportant** [comment]
@nicolas-raoul thank you for explaining.
However this is not the ideal solution because
- I may only be testing bits somebody else created
- I may even want to do tests with the released bits
- even when enough pictures are available, the pure uploading without good or wrong metadata or duplicate images is not what should go to the prod server, right?

How about the following 
- instead of having a beta flavour, adding a setting to switch to the test server inside of the regular app. Or is the dev flavour doing more?
This would enable more people to reproduce bugs without even needing to rebuild the app. Maybe on this server you can find a good way to really delete uploads after some time.

**Comment by nicolas-raoul** [comment]
> uploading without good or wrong metadata

These pictures have a meaningful title, an EXIF latitude/longitude, and all can be categorized "Tokyo". Not perfect but more than enough to be acceptable on Commons :-)

A server setting could be an idea worth considering, it would also allow developers to instantly test on production (many features only work in production). We try to reduce the number of options to keep the app simple, though. Would you mind creating a new issue about it so that the topic can be discussed there?

**Comment by NotSoImportant** [comment]
Sure. Can you please point me to where to open issues for the server, as commons-app repositories feels not like the right place.

**Comment by nicolas-raoul** [comment]
The server exists already and is outside of our scope, so the issue should be at https://github.com/commons-app/apps-android-commons/issues/new
