### ISSUE TITLE
Detect test file names and overwrite test/sandbox files

### ISSUE THREAD

**Issue by domdomegg** [commons-app/apps-android-commons#438]
We should look for:
- [PNG Test.png](https://commons.wikimedia.org/wiki/File:PNG_Test.png)
- [JPG Test.jpg](https://commons.wikimedia.org/wiki/File:JPG_Test.jpg)
- [Test.svg](https://commons.wikimedia.org/wiki/File:Test.svg)

If the filename matches, we could display an alert and upload overwriting these - would make testing uploads not require a load of deletion requests afterwards! At the moment it will increment the number at the end, i.e. `JPG Test 2.jpg`

**Comment by misaochan** [comment]
Uhhh... not sure. If we did do this, we would have to be very careful that the overwrites ONLY happen for these, otherwise it would cause huge issues as lots of people upload files with similar names. 

Also, I'm not sure if this would mess up http://tools.wmflabs.org/commons-app-stats/ ? As we are currently actually tracking overwrites (due to an unsolved overwrite bug), this might cause quite a bit of false alarm. @whym do you think it would be possible to have your script ignore certain files if we decided to do this?

**Comment by misaochan** [comment]
Oh, I forgot to mention that there is a little trick for testing the app without uploading. This works all the way up to the categories screen (just don't select save, otherwise it will crash).

Comment out this line in UploadController.java:
`//uploadService.queue(UploadService.ACTION_UPLOAD_FILE, contribution);`

If you choose to do this, PLEASE remember to revert it before submitting your PR. :)

**Comment by domdomegg** [comment]
Ah nice that'll be useful

**Comment by whym** [comment]
No worries about the stats. It's not difficult to post process to exclude test uploads using file name patterns, if needed.

**Comment by misaochan** [comment]
I think we can close this, with beta product flavours having been implemented?

**Comment by neslihanturan** [comment]
I agree @misaochan
