### ISSUE TITLE
Still have a checkbox on image to asking if he wants to use the same name as image one

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4391]
Here isn't the second image going to help me use the title of the first image? Why do I have to type it all in again if it's the same? Maybe I missed a step on step 1. Maybe there was a thing that said would you like to use the same name for the other images? Well even if I did miss the step that choice should still be available here on Step 2.
![Screenshot_20210501-114733.jpg](https://user-images.githubusercontent.com/1230959/116770093-ad46ee80-aa73-11eb-947e-73190382b5ed.jpg)

**Comment by benryder1988** [comment]
So I started looking into this, and found some issues with captions and descriptions not being copied to subsequent media (see issue #4521)

From a usability perspective, I am wondering if this feature might be better if it were reversed? For example by showing 'Copy from previous media' instead after the first media has had details added, and bringing the changes forward. However, this would mean multiple clicks for the user (copying for each media), rather than one click at the beginning (if it worked correctly)

I can imagine 'Copy from previous media' might be a more user friendly approach, since as @jidanni mentions users might not realise what the current button does and ignore it

**Comment by jidanni** [comment]
All I know is even months later, scrolling back to older images, one still sees identical names in the app.

**Comment by nicolas-raoul** [comment]
I think copy/paste is sufficient for such rarer cases.
