### ISSUE TITLE
Suffix version numbers with alpha, beta

### ISSUE THREAD

**Issue by jidanni** [commons-app/apps-android-commons#4474]
See https://github.com/commons-app/apps-android-commons/issues/4459#issuecomment-864549889

(Chrome goes even further, with different branding for each. Sure each version eventually catches up with other versions, but that doesn't matter.)

Or use Greek letters, instead of full word suffixes.

**Comment by jidanni** [comment]
Anyway when uploading the version to Google Play just be sure there is a suffix on the back of a number. That way without any research one could tell what "channel" it came from.

**Comment by misaochan** [comment]
Greek letters are not possible, but regular letters are possible. This can be done for alpha. However, for the time being, you can tell that a version is alpha by seeing that its version number is longer, 3.0.1.1019 vs 3.0.1 for beta. You can ignore everything after the "~" unless you are looking for commits.

For beta and production it is a little more tricky because the Google Play Store workflow involves promoting a version from beta to production directly when it is ready. Whereas the version name involves code modification in build.gradle.

**Comment by jidanni** [comment]
> longer  i.e. 3.0.1.1019 for alpha vs 3.0.1 for beta. 

But doesn't that also depend on where you look? E.g., In your cellphone's settings' app list it will always look shorter?

**Comment by misaochan** [comment]
Beta should have one less section, yes. I.e. two "."s instead of 3 "."s

**Comment by nicolas-raoul** [comment]
I added the information to https://commons-app.github.io/docs.html#app-versions
I believe it is clear enough now, so no need to increase development complexity further.
Thanks all!
