### ISSUE TITLE
When Wikidata has no decription, show class label instead

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#4539]
1. Using the app to upload a picture, search for 潮騒
2. Only the caption shows up, as item https://www.wikidata.org/wiki/Q60985286 has no description in any language.

In such cases, it would be great to show the label of the Wikidata item that Q60985286 is an instance of (https://www.wikidata.org/wiki/Q105543609 "musical work/composition").

It would be a great help in this case as there are many homonyms (novels, movies, bridges, sculptures, etc).

**Comment by Ayan-10** [comment]
@nicolas-raoul Because of the server-side response, We can't get the name of the instance of depicts directly from the response. It will show only the IDs. It will be better if we can directly get the name from the response. Otherwise, to implement it we have to search for the name by the ID for each item.

**Comment by Ayan-10** [comment]
@nicolas-raoul Can I work on it?

**Comment by nicolas-raoul** [comment]
@Ayan-10 It is yours, thanks! :-)
