### ISSUE TITLE
Descriptions in Nearby are in the wrong language

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#4583]
**Summary:** 

Descriptions in Nearby are in random languages for me. I've seen Arabic and German so far (and also English, which is correct for my phone language).

**Steps to reproduce:** 

The easiest way is to go to Nearby list and look at all the descriptions. But the bug carries over into the details shown in the individual places, and also the autofill when uploading for a Nearby place.

**Device and Android version:** 

Samsung Galaxy S20FE, Android 11
 
**Commons app version:** 

3.1-release

**Screen-shots:** 

![Screenshot_20210826-012122_Commons](https://user-images.githubusercontent.com/3611199/130819777-de862eaf-780e-4aa8-969d-2a16b84cd487.jpg)

**Would you like to work on the issue?**

No

**Comment by misaochan** [comment]
Hey @madhurgupta10 , thank you for the attempt but unfortunately the issue still recurs for me on 3.1-release. 

![Screenshot_20210831-225655_Commons](https://user-images.githubusercontent.com/3611199/131506935-d388369e-7149-46b0-b3cc-e96cd56619ac.jpg)
![Screenshot_20210831-225909_Commons](https://user-images.githubusercontent.com/3611199/131506952-55a922f5-2e99-4743-bc53-3bbe75ff1389.jpg)

**Comment by nicolas-raoul** [comment]
[Surfers Paradise Transit Centre](https://www.wikidata.org/wiki/Q14935565) has no description in English, and taking the only description available is the right thing to do:
<img width="932" alt="Screen Shot 2021-09-08 at 08 26 40" src="https://user-images.githubusercontent.com/99590/132457390-1545c048-9d35-4ad5-aebb-285465c9cc64.png">

Same for the other one:
<img width="933" alt="Screen Shot 2021-09-08 at 08 27 44" src="https://user-images.githubusercontent.com/99590/132457512-739a48be-cfea-488e-91c8-4d429094ebd0.png">

**Comment by misaochan** [comment]
@nicolas-raoul Interesting! I actually did not notice the drop down menu in Wikidata for languages, thanks for that. It looks like someone recently added a LOT of German descriptions for various points in Australia. I guess this is not a bug, then, and it is working as intended (even though it looks strange to the user)?

**Comment by nicolas-raoul** [comment]
The best thing to do is to add descriptions in your phone's language too :-)

> "_it looks strange to the user_"

Here are my thoughts on this:
- Indeed, English speakers are not used to seeing other languages show up on their screens.
- On the other hand, the [95%](https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers) of humans whose native language(s) is not English are used to seeing some English show up on their screens.
- Since English is the major language on Wikimedia projects by far, I believe that the latter will happen far more often than the former.

To mitigate the "issue":
- I added a FAQ: https://commons-app.github.io/docs.html#language-fallback
- We could consider sorting the fallback list differently, for instance by showing Latin-based languages before Arabic-based languages, based on the assumption that more people understand Latin scripts than Arabic scripts. It could be hard-coding systemic bias, though.

**Comment by misaochan** [comment]
Yeah, I don't think I would be a fan of treating different languages differently either. :) Personally my preference would probably be to only see the descriptions in my phone's language or not at all, but it's not a huge issue for me except that I wonder if other users will mistakenly consider this a bug as well. 

Thanks for the FAQ, I can point people to that if they ask me! ;)
