### ISSUE TITLE
Copied description, caption and language structure is removed after canceling upload of one media

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4607]
**Summary:** 

While multiple uploads, after clicking copy to subsequent media, if any media is removed from upload, copied description, caption, and language structure are also removed for all other media.

**Steps to reproduce:** 

1. Take more than 2 images for uploading. 
2. One of the images should be already uploaded to commons. (So that uploading this image shows problem found in image).
3. Add description caption and click copy to subsequent media. Click upload.
4. If an image is removed in between from uploads.
5. All other images are losing the copied caption and description.

**Expected Behaviour**

If any image is canceled from uploads of multiple media, copied description and caption should not be erased from other images.

**Device and Android version:** 

  Pixel 2 API 30
 
**Commons app version:** 

 lastest master betaDebug

**Screen-shots:** 

<img src="https://user-images.githubusercontent.com/71203077/132083279-1fbd0d69-5df4-4a1c-9617-5254ce143f0f.png" width=300/>

<img src="https://user-images.githubusercontent.com/71203077/132083280-6d19dd2e-bf9c-4846-b2c1-ff6e0e543e32.png" width=300/>

**Would you like to work on the issue?**

Yes

**Comment by chan-j-d** [comment]
Hi @nicolas-raoul, it's been some time since the issue was assigned. Could I take this up? I have a fix ready for it and I think the issue is slightly more bizarre than described at least for the version on the master branch. 

The copying actually works as intended and the data is saved even with the cancellation removing the violating image from the list. You can see this by going 'previous' then 'next' after cancellation and the fields will appear. The caption & description boxes that appear right after cancellation seem to be a one time thing and don't actually work. In particular, filling them in with text and going back and forth does not actually result in any changes to the media details. You can observe this by editing those boxes right after cancelling then going forward and backwards. The original copied details will be seen instead of the newly filled in details in the empty boxes.

**Comment by nicolas-raoul** [comment]
@chan-j-d  Thanks for pointing this out! @Ayan-10 would you mind unassigning yourself from open issues you are not currently working on?

Interesting, looking forward to your fix! 🙂
