### ISSUE TITLE
Filter out year categories (X in 2006)

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#47]
As seen below, many results are "X in 2006"
Such categories have very low chances of being about the current year, so better filter them out.
We could filter all categories that contain one 4-digits number that starts with "19" or "20".

![screenshot_2016-01-19-00-44-34](https://cloud.githubusercontent.com/assets/99590/12407919/fc2855d2-be9e-11e5-9dec-1850ff93a6c1.png)

**Comment by misaochan** [comment]
Do we want to keep the categories that contain years from 18__ and previous?

**Comment by nicolas-raoul** [comment]
The bulk of it is really 19xx and 20xx so better limit ourselves to it for now I guess.
There are false positives, for instance https://commons.wikimedia.org/wiki/Category:21_21_DESIGN_SIGHT would be a false positive if we decided to also filter out 21xx so it is a trade-off. I think 19/20 is a reasonable trade-off that we can adjust later if necessary.

**Comment by misaochan** [comment]
@nicolas-raoul Good point, thanks! 

Do we want them to only be filtered out for the 'initial suggestions' (GPS, title, recent) or also from the suggestions that are displayed when the user searches for a category? I'm a bit hesitant about the latter because it provides no way out for the user to search for a specific year (e.g. if someone searches for '2016 election' or something like that, they might get frustrated if nothing shows up). If we only filter for initial suggestions, the user can still search for a year if they want to.

**Comment by nicolas-raoul** [comment]
Indeed, sounds good like you describe it!

**Comment by nicolas-raoul** [comment]
Now that I think more about it, how about **not** filtering the current year and the past year?
Most people won't have pictures older than that on their phones.

**Comment by misaochan** [comment]
Wouldn't that need to be changed every year? (Not that I mind, just that it might not be sustainable in the future)

**Comment by nicolas-raoul** [comment]
Getting the current year dynamically is easy in Java :-)
`new Date().getYear()`

**Comment by misaochan** [comment]
Oh! Thanks haha. :) Will look into that.

**Comment by nicolas-raoul** [comment]
Apparently `Calendar.getInstance().get(Calendar.YEAR);` is better.

**Comment by misaochan** [comment]
Released in v1.38
