### ISSUE TITLE
Categories should be fetch every time they are updated

### ISSUE THREAD

**Issue by Ayan-10** [commons-app/apps-android-commons#4733]
**Summary:** 

Categories are being updated programmatically in the current app which sometimes leads to lag while updating recent changes on categories and depictions. Categories should be fetched every time they are getting updated. There is a TODO too in the `updateCategory()` method

**Steps to reproduce:** 

Update categories of any media. Sometimes it's not showing new categories.

**Device and Android version:** 

Pixel 3 API 30 
 
**Commons app version:** 

latest master prodDebug

**Would you like to work on the issue?**

YES

**Comment by nicolas-raoul** [comment]
I am not sure to understand why fetching more would make the app faster... would you mind giving a sequence example? Thanks! 🙂

**Comment by mnalis** [comment]
> I am not sure to understand why fetching more would make the app faster

Umm @nicolas-raoul, I'm not seeing that it is claimed it would make the app **faster**? 
Instead it seems to me it says it would make app **more correct**, by not returning stale data? 

It think it was about this:

https://github.com/commons-app/apps-android-commons/blob/1c9267ca0874826645090e1cc83164a6c8830b6d/app/src/main/java/fr/free/nrw/commons/media/MediaDetailFragment.java#L651-L656


But the code seems to have changed in 4.x.x series, so I'm not sure how the code currently works though.
Perhaps @Ayan-10 could confirm if the issue is still happening with latest release, or whether it has been fixed (as that comment at least is no longer there in `updateCategoryList()` in current codebase)?

**Comment by nicolas-raoul** [comment]
@mnalis Ah you are right, I was misreading the par about lag!

**Comment by Ayan-10** [comment]
@nicolas-raoul @mnalis I believe I addressed this issue in PR #4928 and also removed the TODO.

**Comment by nicolas-raoul** [comment]
Wonderful, thanks a lot! 🙂
