### ISSUE TITLE
Allow account creation from within the app

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#48]
Non-Wikimedians who witness an important event may become aware of the app and install it in a hurry to upload their pictures. But anonymous upload is not allowed by Commons ("You must be logged in to upload file"). In such case, better make whatever we can to make account registration as fast and straightforward as possible. Embedding that within the app would be the best. For reference, the web site registration form looks like this:

![create-account](https://cloud.githubusercontent.com/assets/99590/12410908/ca7ef270-bebc-11e5-9e0f-9cd356145ee1.png)

**Comment by misaochan** [comment]
Is there a way to find out how these fields are sent to Commons in the web interface? Maybe a repo of the source code? I think creating the form fields should be fairly straightforward, but I'm not sure how these will be sent to the actual Commons user account database. Also, will we automatically have the right to write-access in that database, which I think we will need to create accounts?

**Comment by nicolas-raoul** [comment]
Yes, it is not obvious, and probably involves some back-and-forth requests.
If the Wikipedia app has this feature, copying from it would be the easiest.

**Comment by misaochan** [comment]
Yeah, I've been looking at the Wikipedia app source code, but haven't managed to find the exact code used to write to their DB. The closest I got was https://github.com/wikimedia/apps-android-wikipedia/blob/master/app/src/main/java/org/wikipedia/createaccount/CreateAccountActivity.java . Also doesn't the Wikipedia app create a Wikipedia account, and not a Commons account?

**Comment by nicolas-raoul** [comment]
Looks very usable :-)
I believe that now with SUL, an account from Wikipedia can be used on Commons.
https://meta.wikimedia.org/wiki/Help:Unified_login

**Comment by misaochan** [comment]
Oh okay, thanks! So we won't need special write permission or the password to the user account DB to do this?

**Comment by misaochan** [comment]
I've been looking at the Wikipedia app CreateAccountActivity.java source code, and it refers to multiple other classes, for instance:

```
import org.wikipedia.NonEmptyValidator;
import org.wikipedia.R;
import org.wikipedia.WikipediaApp;
import org.wikipedia.activity.ActivityUtil;
import org.wikipedia.activity.ThemedActionBarActivity;
import org.wikipedia.analytics.CreateAccountFunnel;
import org.wikipedia.editing.CaptchaHandler;
import org.wikipedia.editing.CaptchaResult;
import org.wikipedia.util.FeedbackUtil;
import org.wikipedia.util.log.L;
import org.wikipedia.views.PasswordTextInput;
import static org.wikipedia.util.FeedbackUtil.setErrorPopup;
import static org.wikipedia.util.DeviceUtil.hideSoftKeyboard
```

And some of them like org.wikipedia.WikipediaApp refer to other classes, and so on and so forth. Do you think there is a neat way of getting all of the required classes from there instead of copying and pasting all of them? Or would I be better off starting from scratch and just copying the code that does the backend submission?

**Comment by nicolas-raoul** [comment]
Better reuse even if that means copying 100 classes I would say.

**Comment by misaochan** [comment]
Stuck at the captcha validation... it appears to be handled server-side on Wikipedia as far as I can tell, and it requires a 'site' to be specified? I looked up 3rd party captcha libs like https://github.com/ayltai/Android-Lib-reCAPTCHA and they also require a domain to sign up for the API keys. What 'site'/domain do we use?

**Comment by nicolas-raoul** [comment]
A Wikipedia account is a Commons account if I am not mistaken, so I guess
we can reuse the same site as the Wikipedia app does?
Or if the API key is secret and we can't get two for the same domain, how
about using commons.wikimedia.org as the domain?

**Comment by misaochan** [comment]
I've used commons.wikimedia.org for the reCAPTCHA lib signup and it appears to work. We do have to specify our secret key in the code to use it though. Given that this is open source, is that a good idea?

**Comment by nicolas-raoul** [comment]
Let's do like the Wikipedia app does :-)
I guess they have a placeholder like XYZ and their build script replaces
that with a local file that only core developers have, or something similar.

**Comment by misaochan** [comment]
Haha, the wikipedia app signup is really quite complicated. So far I've needed to copy over about 10 classes and import 4 new dependencies in Gradle, and there are a few classes that I am still trying to figure out how to avoid copying (because they depend on 20 other classes). I've remodeled the UI to use minimal dependencies (so instead of their custom UI classes I'm only using basic UI elements), but the account creation code and captcha code is pretty extensive.

I've been thinking... err, what do you think about just using a WebView? It does sound a bit hack-ish but the account creation and captcha will be guaranteed to work properly (as opposed to if I try to re-do it myself) and we can avoid all the extra classes and external dependencies (which will increase app size).

**Comment by nicolas-raoul** [comment]
Why not! A web view could be a simpler solution indeed. How would you implement a smooth workflow where you can use the app immediately after creating the account? We need to get out of the webview once it is done.

**Comment by misaochan** [comment]
Do you mean just returning to the login screen of our app, or is automatically logging in a necessity?

**Comment by nicolas-raoul** [comment]
Showing a logging screen is also acceptable I guess.

**Comment by nicolas-raoul** [comment]
Would you mind committing your current code imported from the Wikipedia app, into a separate "account-creation-from-wikipedia-app" Git branch?
Even if we don't use it now, and even if it does not compile, it could be useful in the future, or for passer-bys to judge the difficulty of the integration. Thanks!

**Comment by misaochan** [comment]
Sure thing. It's currently on https://github.com/misaochan/apps-android-commons/tree/signup-activity , would that suffice?

**Comment by nicolas-raoul** [comment]
So you will create a separate branch for the webview-based approach? OK :-)

**Comment by misaochan** [comment]
Yup, will try the WebView approach in a different branch. :)

**Comment by misaochan** [comment]
I've tried overriding the URL that is displayed to the user when an acc is successfully created, in order to take them back to the login screen, but no luck so far. Posted on http://stackoverflow.com/questions/38781890/loading-an-activity-when-user-clicks-create-account-button-in-webview , hopefully someone knows how.

**Comment by misaochan** [comment]
Oh, whoops, the new code causes issues with logging in for some reason. :/ Please don't release current code until this is fixed.

**Comment by misaochan** [comment]
Think I might have fixed it, but would appreciate if anyone could test it as well (since I can only create 6 user accounts/day to test). This is the first step a new user would encounter, so probably pretty important that it works as intended. :)

**Comment by nicolas-raoul** [comment]
Tested once with the current Git code, it worked :-)

**Comment by misaochan** [comment]
Awesome, thanks :) Will try to do a release tomorrow.
