### ISSUE TITLE
Invalid resource directory name `values-ks-arab`

### ISSUE THREAD

**Issue by madhurgupta10** [commons-app/apps-android-commons#5029]
It seems like the CI is failing with the following error. Seems related to #4927

```
values-ks-arab: Resource and asset merger: Invalid resource directory name
```

**Comment by misaochan** [comment]
@translatewiki could you help with this please?

**Comment by nicolas-raoul** [comment]
@Nikerabbit Sorry for the frequent pings, would you mind checking maybe? I think it is [Kashmiri](https://en.wikipedia.org/wiki/Kashmiri_language) in a Perso-Arabic script.

**Comment by whym** [comment]
It looks as though the problem was fixed for the Wikipedia app around Aug 5. Maybe what's left to do is just to rename the offending directory, like https://github.com/wikimedia/apps-android-wikipedia/commit/802f4d6cb256c35ee19d141f675763450908fb05 ? [Updates made since then](https://github.com/wikimedia/apps-android-wikipedia/commits/main/app/src/main/res/values-ks) look fine for the Wikipedia app.

See also: https://github.com/wikimedia/translatewiki/commit/a653c7ca7ac6696cc99de82ee05df524754d57c0
