### ISSUE TITLE
Upload often fails or gets stuck, especially when uploading 3 or more pictures

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5128]
Steps to reproduce:
1. Take 3 (or more) interesting pictures of at least 2 MB (_for instance pictures of cars or houses. If you need I can also provide many pictures, just send an email to the address found [here](http://nrw.free.fr/)_).
2. Get a slow Internet connection by installing [the Throttly app](https://play.google.com/store/apps/details?id=me.twocities.throttly) and setting it to `Good 2G 450kbps↓ 150kbps↑`.
3. In your gallery app, select the 3 (or more) pictures, tap `Share`, then select the Commons app.
4. As soon as the upload starts, turn off your screen and do not touch your phone for 5 minutes.
5. Some of the pictures will probably fail to upload.

Many other apps always upload reliably (for instance Gmail with attachments) even with slow Internet connections, even the Commons browser-based uploader seems to perform better, so hopefully we can fix this.

Possible strategy:
1. Reproduce the issue with the Android Studio debugger (or similar), find out what the exact error message is.
2. Based on the error message, change the app's network parameters, such as timeout or buffer sizes.
3. If still not reliable, implement a retry loop (for instance try again 3 times).

Measuring improvements:
- Percentage of failure with the reproduction steps above, as of 2023 January 12's master branch:
  - 1 failure out of a 3-pictures set upload on fast WiFi: 2 occurrences
  - 2 failures out of a 10-pictures set upload on fast WiFi: 1 occurrence
  - 6 failures out of a 9-pictures set upload on fast 5G: 1 occurrence
  - 0 failures out of a 2-pictures set upload on slow WiFi: 1 occurrence

Some uploads get stuck (no progress despite the progress bar showing an animation). Among those stuck, some file have actually been uploaded already, some not.

Aggravating factors:
- Brief network disconnections, for instance when entering an elevator for 1 minute, seem to make uploads less reliable. I have not measured this theory but this could be investigated by putting your phone in a metal box (use a ping chart app to verify)
- I had many successes uploading from the custom picker, and many failures uploading by sharing from the gallery. There might be something about the app going to the background, or something other about activities, that might have an effect on reliability.

Recent Google Play comments:
- "Not a single photo is uploading even though i tried a dozen times"
- "50% of uploads are failed"
- "fails to upload pictures without saying the reason"
- "I can't upload photos. They all say failed. Before it worked fine"
- "Photos cannot be uploaded"

**Comment by ayushanand308** [comment]
@nicolas-raoul This seems to be an interesting issue to solve. Willing to work on it.

**Comment by nicolas-raoul** [comment]
@ayushanand308 Are you planning to apply for Google Summer of Code, by any chance?

**Comment by ayushanand308** [comment]
@ayushanand308  Yes I am!

**Comment by nicolas-raoul** [comment]
@ayushanand308 Then please the instructions at https://github.com/commons-app/commons-app-documentation/blob/master/android/Students.md, at the "Fix 1 bug" step please choose a different bug, because this one is among the bugs that make the GSoC's task itself :-) How about https://github.com/commons-app/apps-android-commons/issues/5057 for instance? Thank you for your interest!

**Comment by Shantanub05** [comment]
> @nicolas-raoul This seems to be an interesting issue to solve. Willing to work on it.

Hey Ayush, I would like to contribute to this issue along with you for GSOC 2023.....Can we connect?

**Comment by siva-subramaniam-v** [comment]
This error occurs when the app sends the "Failed to Upload" notification.

![image](https://user-images.githubusercontent.com/112970189/231746352-05d404fc-bb27-41af-8f5a-fd0f1599cbf2.png)

The error is thrown at line 227 in _UploadClient.java_ in the _upload_ package

![image](https://user-images.githubusercontent.com/112970189/231747316-59f8bc65-cd22-4ce8-a6ff-e6f1ea1fc55f.png)

This happens when the condition _uploadResult.getUpload() == null_ evaluates to true at line 223

Here _uploadResult_ is of type _UploadResponse_

![image](https://user-images.githubusercontent.com/112970189/231749333-78e3fb53-8df8-4899-918b-05a95ac24d1b.png)

So _uploadResult.getUpload()_ returns the nullable property _upload_ of type _UploadResult_ which is a data class

![image](https://user-images.githubusercontent.com/112970189/231750206-08db8761-1921-4668-af76-fc1a677e1149.png)

At line 221 in _UploadClient.java_ the value of a _gson.fromJson()_ call is stored in the _uploadResult_ field

![image](https://user-images.githubusercontent.com/112970189/231751923-03c4861c-468c-4db7-93b8-7ae895a33133.png)

So _uploadResult.getUpload() == null_ indicates that the _upload_ property was returned as null by gson after parsing a JSON response from the server, which indicates that the server likely returned an empty or null response,

As  _uploadResult.getUpload() == null_ is true, an exception of type _MwException_ is thrown.

The _getErrorCode()_ method in _MwException_ class returns _error.getCode()_ where error is of type _MwServiceError_

![image](https://user-images.githubusercontent.com/112970189/231756683-dbe17e58-1cd3-4c5b-a4a4-99e8eff3e857.png)

A top-level comment in _MwServiceError.java_ says **"Gson POJO for a MediaWiki API error"**

![image](https://user-images.githubusercontent.com/112970189/231757813-c3196db5-7e74-4432-8102-01fe99f66fcd.png)

The class _MwServiceError_ extends _ServiceError_ which likely represents an error reported by the server via the API. It says **"The API reported an error in the payload."**

![image](https://user-images.githubusercontent.com/112970189/231758363-144bb1b3-c77d-4f38-997a-5b19826f88ff.png)

All this happens when the _uploadClient.uploadFileFromStash()_ method is called at line 296 in _UploadWorker.kt_

![image](https://user-images.githubusercontent.com/112970189/231761879-6e0fe614-ca48-4626-ba6c-818631d5dfb6.png)

As the  _uploadClient.uploadFileFromStash()_ call causes an exception the _onErrorReturn { }_ block is executed. A _null_ value is passed here which causes the NullPointerException as shown in the Logcat screenshot attached first.

![image](https://user-images.githubusercontent.com/112970189/231763379-b91b7b58-b559-463f-be86-ba509752d6a9.png)

![image](https://user-images.githubusercontent.com/112970189/231765006-a7cf1b70-6d0b-48d8-b6f0-d248fe6e9e95.png)

The exact _error message_ is as below

![image](https://user-images.githubusercontent.com/112970189/231765701-0b2c710c-4ce6-4fb1-83b4-9ee5ac8f240e.png)

The message **Could not acquire locks on server rdb1** indicates that this is likely to be a problem with the server, rather than the Android client.

Two key methods are executed during the process in _UploadWorker.kt_:

1.  _uploadClient.uploadFileToStash()_ and
2. _uploadClient.uploadFileFromStash()_

while _uploadFileToStash()_ turns out to be executed without a problem, _uploadFileFromStash()_ causes the exception.

So what is **Stash**?

I'm still unsure what it is. But it is clear that it's something the server handles. Refer [https://www.mediawiki.org/wiki/Manual:UploadStash](https://www.mediawiki.org/wiki/Manual:UploadStash)

**Comment by nicolas-raoul** [comment]
Stashing is a way to first send the picture's JPEG bytes to the server, then finalize the "upload" (file registration) a bit later.

**Comment by siva-subramaniam-v** [comment]
Steps to reproduce the error:

1. Select a few images and start upload
2. A notification alert with the message _"Uploading file: file-name"_ is received
3. After the upload progress bar reaches the end, a notification alert with the message  _"Failed to upload file-name"_  is received
4. The following error is received

![image](https://user-images.githubusercontent.com/112970189/232032106-cc30642e-5441-48b1-8ec7-086d425da35d.png)

@nicolas-raoul Can you verify if the behavior is the same for you?

**Comment by nicolas-raoul** [comment]
@siva-subramaniam-v Does step 3 happen for you every time after steps 1 and 2? For me, after steps 1 and 2, step 3 **sometimes** happens.

**Comment by siva-subramaniam-v** [comment]
When I tested yesterday after step 2 the notification message changed from "Uploading file: file-name" to _"Finishing uploading file-name"_ and then to step 3 (_"Failed to upload file-name"_). But this sequence happens consistently for me and leads to the same error.

**Comment by nicolas-raoul** [comment]
@siva-subramaniam-v If I understand correctly, multi-upload never works for you? If yes, would you mind creating a new GitHub issue? Thank you! 🙂

**Comment by nicolas-raoul** [comment]
On latest master, upload often gets stuck when uploading a set of around 10 pictures, this happened today on a very fast WiFi at home, not moving, but switching display off, on Pixel 6:
![Screenshot_20230630-155736.png](https://github.com/commons-app/apps-android-commons/assets/99590/5bcb3e95-3fdc-4711-8cb1-a8be0bf9805e)
I can send the logcat if necessary.

**Comment by nicolas-raoul** [comment]
I just got upload stuck but uploading several medium-size sets (10 sets of 2 to 10 pictures).

**Comment by RitikaPahwa4444** [comment]
Hi @nicolas-raoul, could you please share the logs too?

**Comment by nicolas-raoul** [comment]
Solved by Ritika. :-)
