### ISSUE TITLE
Peer review: Always getting the same dozen pictures, no variety

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5161]
My experience using the `Review` feature (accessible from the menu): I get a picture of a bird, review it, and the next picture... is another picture of a bird, taken by the same person. Reviewing 10 more, all of them are pictures of birds by this same person. Even though the `Explore>Upload via mobile` shows a great variety of pictures uploaded by many different persons.

Sometimes I am slightly more lucky, but anyway after a dozen pictures I am given the same pictures to review again and again.

Why this is an issue:
- Peer review should cover a wide variety of pictures and uploaders. If I send a deletion request for a picture of one uploader, the deletion team will review all recent pictures of that person anyway, so reviewing many pictures of the same uploader is a loss of time.
- Reviewing many similar pictures is boring.

How we could solve this:
- Fix bugs in the randomizer, if there are any,
- If no bug, extend the date range covered, especially towards recent pictures.
- Do not show the same picture twice, by recording the identifier of already reviewed or skipped pictures in a database table.

**Comment by arinmodi** [comment]
According to me, To Solve this 

we need to do changes in the database, so can you tell me which database are we using ?

**Comment by nicolas-raoul** [comment]
>which database are we using ?

Very standard Android database, you can refer to this example code in the app: https://github.com/commons-app/apps-android-commons/blob/ee1bf4b5b6d01e8d638ebad73fe40b6d9518058b/app/src/main/java/fr/free/nrw/commons/bookmarks/locations/BookmarkLocationsDao.java

**Comment by RitikaPahwa4444** [comment]
I too observed the same issue. What I could figure out is that the app fetches recent records and displays them in the Peer Review. Here's a comment related to this issue in the code:
```
/**
     * Fetches recent changes from MediaWiki API
     * Calls the API to get 10 changes in the last 1 hour
     * Earlier we were getting changes for the last 30 days but as the API returns just 10 results
     * its best to fetch for just last 1 hour.
     *
     * @return
     */
```

So, if the same person uploads 10-15 pictures, shuffling them would still show the pictures from that person.

**Comment by RitikaPahwa4444** [comment]
I too observed the same issue. What I could figure out is that the app fetches only the 10 most recently added records and displays them in the Peer Review. Here's a comment related to this issue in the code:
```
/**
     * Fetches recent changes from MediaWiki API
     * Calls the API to get 10 changes in the last 1 hour
     * Earlier we were getting changes for the last 30 days but as the API returns just 10 results
     * its best to fetch for just last 1 hour.
     *
     * @return
     */
```

So, if the same person uploads 10-15 pictures, shuffling them would still show the pictures from that person.  Since the API is returning only 10 results, fetching the recent activity may not help at all, even on extending the date range.

**Comment by nicolas-raoul** [comment]
@RitikaPahwa4444 Great finding! I am indeed still getting bird pictures one day later, even though hundreds of other pictures have been uploaded more recently, as seen in `Explore`>`Uploaded via mobile`.

How about modifying Review to use the same API method as Explore for fetching recent pictures? I t allows paging as much as needed.

**Comment by RitikaPahwa4444** [comment]
I tried investigating why `recentchanges` is not returning the latest list of uploaded images as those bird images date back to February 2023. The API call still shows the same result when I check it on a browser but surprisingly, I am no longer getting those bird images on the app. In any case, a check on the uploader is needed and implementing paging instead of increasing the date range/number of pictures directly sounds like a good idea :)

**Comment by nicolas-raoul** [comment]
Thanks for the investigation! By the way, do you want to be assigned to this issue?

**Comment by RitikaPahwa4444** [comment]
Yes, thank you for asking! I would love to work on this issue.
