### ISSUE TITLE
Picture location is sometimes lost despite being present in EXIF

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5196]
EXIF metadata sometimes gets stripped from pictures, making the uploaded result less useful.

The custom picker had this issue until [Siva Subramaniam](https://github.com/siva-subramaniam-v) kindly fixed it.

There are still features in the app that strip pictures of their EXIF location. The goal of this issue is to:
1. Imagine all (or most) scenarios
2. Fix the scenarios where EXIF location gets stripped.

For (1), non-exhaustive list of hints:
- Uploading from the "Nearby" tab loses EXIF location
- Sharing from Google Photos. Both pictures taken by the phone, and pictures from elsewhere shown by Google Photos. In Google Photos swiping up a photo seems to have some kind of effect on metatata, so better check with and without. Adding/modifying location within Google Photos may also have an effect.
- Sharing from third-party gallery such as Samsung's or https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery
- Uploading from the custom picker, normal picker, built-in camera, using an old version of Android and a recent version of Android (can use emulator).
- Other ideas very welcome.

For (2), this might help: https://github.com/commons-app/apps-android-commons/pull/5190. It might not be enough though.

**Comment by sagarojha772** [comment]
Hey @nicolas-raoul 
Can you please clear me more as I am beginner to GSOC as well as open source contributions, I have been programming in java and have keen interest in  android development, If I can be any helpful, I am ready , please help me in understanding the issue . Thanks.

**Comment by nicolas-raoul** [comment]
@sagarojha772 There is not much time left, but if interested please read the instructions at https://github.com/commons-app/commons-app-documentation/blob/master/android/Students.md thanks and good luck! :-)

**Comment by sagarojha772** [comment]
Hey @nicolas-raoul 
After exploring lot , I found that we can use EXIF libraries such as Metadata-Extractor and save it in a separate variable.
When displaying the picture, use this saved location data instead of relying on the EXIF data in the image file.

1-
We can use this concept to all other features google sharing photos:
Retrieve the EXIF data using Metadata-Extractor and save it in a separate variable or database field before sharing.
Check the effects of swiping up on metadata and modify the saved data accordingly.
When displaying the picture, use this saved location data instead of relying on the EXIF data in the image file. 

2- 
Third party galleries

3-
Uploading from custom picker, normal picker, or built-in camera:

**Comment by sivaraam** [comment]
> - Sharing from third-party gallery such as Samsung's or https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery
> - Uploading from the custom picker, normal picker, built-in camera, using an old version of Android and a recent version of Android (can use emulator).

I happen to be observing an issue w.r.t both of the above cases. See https://github.com/commons-app/apps-android-commons/pull/5190/files#r1167466682

Notes:
- I'm using a OnePlus Nord running Android 12.
- I used Simpletools Gallery to share to the app

**Comment by sivaraam** [comment]
Lets us leave this issue open for now. We could close it once we've done one last exhaustive check and ensure all known location loss issues are gone.

If we find any new onesduring the check , we could open new issues for specific cases and address them.
