### ISSUE TITLE
Edit depictions: "Please wait" forever

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5212]
Steps to reproduce:
1. Tap on any already uploaded picture.
2. Tap the pencil icon of the "Depictions" section.
3. Add any depiction.
4. Tap "Save"
5. Popup saying "Please wait" appears and never disappears.

https://github.com/commons-app/apps-android-commons/assets/99590/c42fc94c-c3d1-41e4-aee1-e02a9956f0c6

![Screenshot_20230417-222342](https://user-images.githubusercontent.com/99590/232499765-9df0e11c-8ffa-4f02-8c45-237a845e4668.png)

Note: The edit is actually saved and pressing Back lets you use the app without killing it.

**Comment by RitikaPahwa4444** [comment]
The edit depictions feature is working fine for me without pressing the back button (I did not use it even to close the keyboard):

https://user-images.githubusercontent.com/83745993/232789607-9f6b95db-041a-4555-8fae-9c80602366cc.mp4

Tested on Redmi 5A, API level 27. This may be specific to some devices/API levels only.

**Comment by TaiHaDev** [comment]
Hi @nicolas-raoul, can you assign me this issue :) Thank you!

**Comment by TaiHaDev** [comment]
Hi @nicolas-raoul, I tried to download and build the project but I am facing a lot of errors and I don't have much experience with it, I have been trying to solve it since yesterday but no progress, Can you please have a look ? Thank you very much 
![image](https://github.com/commons-app/apps-android-commons/assets/97883232/93f49f68-77a3-4f6d-b16c-f8897101e372)
![image](https://github.com/commons-app/apps-android-commons/assets/97883232/63e7934c-d80e-4a70-a566-8933570d9b05)
![image](https://github.com/commons-app/apps-android-commons/assets/97883232/7e7f574e-3509-4d91-9e2d-08d1e8643bb2)

**Comment by nicolas-raoul** [comment]
Sorry the current main branch only works for earlier versions of Java and Android Studio.

You can either downgrade, or work from this branch: https://github.com/commons-app/apps-android-commons/tree/v4.2.0-beta

Thanks and sorry for the inconvenience!

**Comment by TaiHaDev** [comment]
Hi @nicolas-raoul, I can run the beta version using android studio now but I cannot upload image to further do my issue:
![image](https://github.com/commons-app/apps-android-commons/assets/97883232/d7c93db2-2ecf-461f-83e2-e16cbc5f474d)

**Comment by TaiHaDev** [comment]
Hi @nicolas-raoul , I can now run the beta version on my android studio but I couldn't upload the image to further work with my issue, can you please have a look:
![image](https://github.com/commons-app/apps-android-commons/assets/97883232/fbb34bba-e194-4458-9080-8b181aff00fb)

**Comment by nicolas-raoul** [comment]
Please use the prodDebug flavor.

**Comment by nicolas-raoul** [comment]
You don't need to upload anything. Tap "Explore" then "Uploaded via mobile", then had a correct depiction to any picture.

**Comment by TaiHaDev** [comment]
Hi @nicolas-raoul , I think I fixed the bug that causing the progress dialog to run forever on the depiction edit and description edit. I have pushed the commit to a branch on my forked repo but I am not sure where to make the pull request because I don't think I can make the pull request to the current main branch as I used the tag version "v4.2.0-beta" that you showed me above. Can you guide me on how to make a pull request? it's my first time so I am quite lost. Thank you very much 😄
<img width="1291" alt="image" src="https://github.com/commons-app/apps-android-commons/assets/97883232/8d312351-b491-44e3-a877-2db3a6679431">

**Comment by nicolas-raoul** [comment]
Have you tried clicking `base:main` at the top and choosing `base:v4.2.0-release` instead?

**Comment by nicolas-raoul** [comment]
In the future I would recommend not including special characters such as `#` in branch names, it makes command-line manipulations trickier. :-)

**Comment by TaiHaDev** [comment]
Thank you @nicolas-raoul . I'm sorry for that, would you like me to change the branch name? I think by fixing this bug, I am also fixing the similar bug when editing descriptions.

**Comment by nicolas-raoul** [comment]
> would you like me to change the branch name

No please don't worry :-)
Some repositories have rigid conventions so it is good to look at the branch names of recently closed pull requests. Our project here is not so strict haha.
