### ISSUE TITLE
[Bug]: Number of images selected is incorrect All images are getting the total number of images selected.

### ISSUE THREAD

**Issue by VinzRoosen** [commons-app/apps-android-commons#5221]
### Summary

When using the selector to upload multiple images at once. When selecting for example 4 images. All images are labeled as 4 instead of 1,2,3,4.

Only apears to be in 4.1.0 debug-master not in app store version 4.0.5

### Steps to reproduce

1. Go to the Contributions menu
2. click on the add button
3. select Custom Selector
4. select multiple images 

### Expected behaviour

First selected image should be labeled as 1
Second as 2 
and so on...
![Screenshot_20230503_173136_Commons](https://user-images.githubusercontent.com/125285295/235966519-897286e8-3f91-446a-a4bf-b23c45588ad5.jpg)

### Actual behaviour

All selected images are labeled as the total number of images.
![Screenshot_20230503_173136_Commons](https://user-images.githubusercontent.com/125285295/235965961-55c64a39-c21b-49ce-948a-ba704375b077.jpg)

### Device name

Samsung s22

### Android version

Android 13

### Commons app version

4.1.0-debug-master

### Would you like to work on the issue?

Yes

**Comment by nicolas-raoul** [comment]
This is actually intended.
The goal is to make the app simpler, since the order in which pictures get uploaded usually does not matter, and when it matters chronological order is most often good enough.
Imagine selecting pic2 pic13 pic25 pic36 pic159, and then you realize that you want to include pic1 too in the same multi-upload.
Thank you for your understanding! 🙂

**Comment by sivaraam** [comment]
> This is actually intended. The goal is to make the app simpler, since the order in which pictures get uploaded usually does not matter, and when it matters chronological order is most often good enough. Imagine selecting pic2 pic13 pic25 pic36 pic159, and then you realize that you want to include pic1 too in the same multi-upload. Thank you for your understanding! slightly_smiling_face

While this might be fine, I believe the cause of the confusion is the place in which the number is being shown. Rather than showing the totally number of selected pictures in each selected image if it were shown in the top-right or some other place where it is clearly visible, this confusion would not have occurred. A simple tick icon in the top left corner should be sufficient to identify selected images then,

Re-opening in favour of addressing this UI issue. Feel free to share your thoughts.
