### ISSUE TITLE
Minimum android version 10 is mandatory?

### ISSUE THREAD

**Issue by jindamvani** [commons-app/apps-android-commons#5238]
### Description

* f-droid app requires android 10 for installation and usage?
* Is this some kind of bug?

**Comment by sivaraam** [comment]
@jindamvani Sorry for the inconvenience. That's unfortunately the case for v4.1.0 due to a problem with publishing to Play Store. We've since bumped back the requirement to API 21 (Android 5.0) [ref: #5223]. The next update should be available to devices running Android 5.0 at least on F-droid.

**Comment by sivaraam** [comment]
Hey @jindamvani ! We've released v4.2.1 of the app in which we've made the app compatible with Android 5.0 and above. It should be available on F-droid soon. 

Consequently, I'm closing the issue. Feel free to reopen if you face any issues. :-)

(If you only see the 4.2.0 release. Kindly avoid the same since it has some issues.)
