### ISSUE TITLE
Upload Wizard does not show clearly whether location information is present or not

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5246]
The `Media Details` step always shows a blue-background map button, even if location is absent.

Someone uploading a picture of a vegetable in their kitchen might inadvertently share the location of their home.

Showing it differently would reasonably prevent such occurrences.

Maybe some red strike? It must still be obvious (or even more obvious than currently) that this is a button, it is tappable and leads to the location editor.

**Comment by alvinylt** [comment]
Hi @nicolas-raoul!

Since the main objective is to prevent unintended sharing of location, I'm thinking of adding a tick box/indicator next to the button so that users can easily know whether the location should be included in the image metadata. I assume the red strike you mentioned refers to crossing out the button if the location should not be shared?

I'm happy to work on it and we'll see if the result would make the UI more intuitive. Could I give it a try?
