### ISSUE TITLE
Standardise location-related flow in the app

### ISSUE THREAD

**Issue by RitikaPahwa4444** [commons-app/apps-android-commons#5256]
### What is the user problem or growth opportunity you want to see solved?

By addressing the issue of redundant code and inconsistencies, users can benefit from more reliable and consistent location-related features. Additionally, the standardised implementation of location services can provide a solid foundation for future growth and expansion of location-based features within the app.

### How do you know that this problem exists today? Why is this important?

The app uses a lot of redundant code to deal with location services. You may find more details about code redundancy and associated inconsistencies in pull requests #5249 and #5205. Since location services are used in many fragments, standardising them will be helpful to prevent inconsistent behaviour.

**Comment by ShashwatKedia** [comment]
I would like to work on this issue

**Comment by ShashwatKedia** [comment]
After a bit of debugging and research I got to know, "Starting in Android 11 (API level 30), if the user taps Deny for a specific permission more than once during your app's lifetime of installation on a device, the user doesn't see the system permissions dialog if your app requests that permission again". Also, when tested on API levels < 30, the app keeps asking for permission in a loop if the user keeps denying it, until either user checks "Don't ask again" or allows the permission.

So, I think that for API Level < 30, we'll ask for permission only onResume() and if the target icon is clicked (that too only once per click, not in loop). And on API Levlels >= 30, we'll ask for permissions onResume() and when the target icon is clicked. But if it has been denied twice, and user clicks on the target icon then we can show a dialog to the user to give location permission and open the settings page of the app (since after Android 6.0, we cannot open the permissions page of our app directly). @nicolas-raoul @RitikaPahwa4444 your thoughts on this?

**Comment by RitikaPahwa4444** [comment]
Hi Shashwat, thanks for taking this up. Removing that loop would be great, that behaviour is indeed a bit annoying. These additional restrictions might impact Case 1 you mentioned earlier. Also, Android [auto-resets](https://developer.android.com/about/versions/11/privacy/permissions#auto-reset) runtime permissions, so we'll have to verify that case as well.

**Comment by ShashwatKedia** [comment]
> Also, Android [auto-resets](https://developer.android.com/about/versions/11/privacy/permissions#auto-reset) runtime permissions, so we'll have to verify that case as well.

It says that auto reset of permissions has the same effect as if the user denied the permission, and my code follows their advised flow for runtime permissions, so I don't think that would be a problem, but I will still intensively test for all scenarios I can think of. I am done fixing the flow and removing redundant code for all maps except Nearby. I am waiting for #5418 to be merged, as without that, the Nearby fragment crashes and causes problems in testing different cases, and if I change the code in the branch for this issue, it might cause merge conflicts later on.

**Comment by RitikaPahwa4444** [comment]
> I am done fixing the flow and removing redundant code for all maps except Nearby.

Did you fix all of them individually or extracted the common part to a separate class (maybe) for the flow that is same in all the fragments? By standardising, I meant creating some sort of a model for it, just wanted to clarify before you move ahead. 

> Could you @RitikaPahwa4444 merge that one, as you have already tested that branch for https://github.com/commons-app/apps-android-commons/issues/5461 ?

I think @sivaraam is still validating it🙂

**Comment by ShashwatKedia** [comment]
> Did you fix all of them individually or extracted the common part to a separate class (maybe) for the flow that is same in all the fragments? By standardising, I meant creating some sort of a model for it, just wanted to clarify before you move ahead.

I moved all the common parts into the LocationPermissionsHelper class and use it for most of tasks. But, some parts cannot be moved because even though the location flow seems to be the same in all fragments, they serve different purposes and should behave differently in different scenarios (For example, Explore Map does not show any location when lastKnownLocation is null and location is not available, but Nearby shows a default place). 

>  I think @sivaraam is still validating it🙂

Okay :)

**Comment by ShashwatKedia** [comment]
My apologies for taking this long to fix it, I had to redo the Explore fragment's code because migration to OSMDroid was merged in between :)
