### ISSUE TITLE
De-clutter the app's settings

### ISSUE THREAD

**Issue by RitikaPahwa4444** [commons-app/apps-android-commons#5258]
### What is the user problem or growth opportunity you want to see solved?
The General section of the app's settings is too cluttered. A separate section for upload-related settings with the following preferences would help de-clutter it:
- Save In-app shots
- Use custom author name
- Custom author name
- Photo picker one

### Anything else you would like to add?

More details about this suggestion can be found [here](https://github.com/commons-app/apps-android-commons/pull/5249#discussion_r1257318159).

**Comment by Apoorvyash** [comment]
Hi, @RitikaPahwa4444 @nicolas-raoul Can you assign me this issue, I have neat experience in android UI and frontend, I would be adding the following in a separate section as a card layout so that the settings look clean and relatable-
In app shots will be saved in local storage and shown in app-settings
Use and add custom author name based on the current state fetched.

**Comment by RitikaPahwa4444** [comment]
Hi @Apoorvyash, any updates on your progress?

**Comment by Apoorvyash** [comment]
Hi @RitikaPahwa4444 , I couldn't update because of some problems, I am working on it, I have changed author's name and custom author's name to settings and moving the things out of the app's general section to the settings section, I will make a pr in a few days.

**Comment by RitikaPahwa4444** [comment]
Thank you, @Apoorvyash, for the update on your progress regarding the changes! :) 

I just wanted to clarify that instead of naming the section "Settings", it would be more suitable to name it "Uploads". I'm sorry, I think I should have mentioned it in the description instead of giving the link to the suggestion :')

**Comment by nicolas-raoul** [comment]
Thanks @Apoorvyash for the effort!
I want to make you aware that this issue is particular: unlike most other issues, our GSoC student Ritika may take over this issue at any time if she deems it important for her overall task.
If that happens, please do not take it personally and feel free to go for any other issue.
Thank you for your understanding! :-)

**Comment by Apoorvyash** [comment]
No problem, I would surely find another suitable issue, please let @RitikaPahwa4444  continue as her wish. After all, issue resolving is what matters.

**Comment by RitikaPahwa4444** [comment]
I think this has been resolved with #5249, closing this one.
