### ISSUE TITLE
Vienna hackathon: Recruiting and onboarding newcomers who have signed on as mentees

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#529]
For the onboarding session during the hackathon, I was thinking that, after getting them set up, we could pick a few beginner-friendly tasks and let them try it on their own, helping them where needed? Would that be a good idea?

**Comment by whym** [comment]
I have seen the idea of keeping individual, public logs in a beginner-friendly mini hackathon/coding workshop:  https://github.com/oss-gate/workshop/blob/master/tutorial/scenario.md (in Japanese). I haven’t tried it before and I’m not sure if it is the best format for us, but it find it inspiring. The idea is like this (at least this is my understanding):

- Each participants keeps a public log, adding every update they have during the hackathon (tools they have tried, references they have found, other attempts and failures they experienced during the day). It could be a wiki page on MediaWiki.org or a GitHub issue (maybe in a dedicate repository).
- The log doesn’t have to be a complete write-up. Think something like “Tried to reproduce XYZ. Stuck at a different error: …” or “Checked http://stackoverflow.com/xyz/123 but it seems outdated.”
- Participants should feel free to include basic matters such as trying to setup an environment or thoughts that may or may help others later on (e.g. “This feels kind of similar to the XYZ software I worked on in terms of ….”).
- If someone feels it is an obstruction, they don't have to follow this practice thoroughly. (But still, having a paragraph or so for a day can be recommended.)
- Of course, when appropriate, consider also posting to an existing or new GitHub issue instead of the personal log.

The main benefit is that reading the logs helps mentors to help mentees. The logs also may serve as a starting point towards making the software documentation more complete (this can happen post-hackathon).

**Comment by whym** [comment]
Oops I was thinking about the pre hackathon when writing above. Probably not a structure we're looking for the rather short session in Vienna.

**Comment by tobias47n9e** [comment]
@whym I liked your suggestion. We should try that at one of the upcoming events.

@misaochan I do think that that is a good idea.

**Comment by misaochan** [comment]
I talked to Sonja about this, apparently we don't need to register as mentors to run a beginners' workshop. She says there will be more information on how to schedule such sessions on the hackathon page shortly.
