### ISSUE TITLE
Grey empty screen at Upload wizard caption step after denying files permission

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5330]
![Screenshot_20231007-182129.png](https://github.com/commons-app/apps-android-commons/assets/99590/e4686c7a-0ec0-4fe5-b716-d1ac3e9502dd)

**Comment by kanahia1** [comment]
Hi @nicolas-raoul , I would like to work on this issue, can you please assign it to me.

**Comment by nicolas-raoul** [comment]
@kanahia1 Did you manage to reproduce the issue? :-)

**Comment by kanahia1** [comment]
@nicolas-raoul , I have attached the video demonstrating the issue 

https://github.com/commons-app/apps-android-commons/assets/114223204/fa7111c0-5a15-4c65-9608-f38c03e5d512

**Comment by nicolas-raoul** [comment]
@kanahia1 Great! It is yours, thanks 🙂

**Comment by kanahia1** [comment]
Hi @nicolas-raoul, here is the progress of the week

🐛 Fixed grey empty screen at upload caption step ---

https://github.com/commons-app/apps-android-commons/assets/114223204/a1f05ab1-ae99-4dc3-b976-a194aed1a355


https://github.com/commons-app/apps-android-commons/assets/114223204/9325ccf0-56df-4e01-a079-405c48ee1467



➕ Added functionality to the cancel button of the dialog box, because people often don't see or read everything on the screen. Therefore, we must warn them with a toast message in case they click on the cancel button and also inform them that they need to accept permissions in order to access the upload facility.

https://github.com/commons-app/apps-android-commons/assets/114223204/54b03962-0056-41d0-bdd7-a81d6eb37a55


I am currently working on an issue with a dialog box (an infinite loop) that is created due to checking permissions in the ```onResume``` method in Upload Activity. I will be sharing the pull request (PR) next week. ✨

**Comment by nicolas-raoul** [comment]
Looks good, thanks a lot for the update!
Do not hesitate to send a draft pull request.

**Comment by kanahia1** [comment]
Hi @nicolas-raoul , I have fixed loop issue, can you please review it. #5356

🐛Bug 

https://github.com/commons-app/apps-android-commons/assets/114223204/bf423948-4052-4870-b589-fb3f61a19e38


🔧Fixed

https://github.com/commons-app/apps-android-commons/assets/114223204/0d09befd-dbac-4aa2-afb3-625d780c08cf
