### ISSUE TITLE
Create and give out cards or leaflets that introduce the app

### ISSUE THREAD

**Issue by whym** [commons-app/apps-android-commons#536]
In offline events, it can be handy to be able to introduce the app by giving out cards. This might work better at Wikimania and local events than hackathons. Telling "Go to Play Store and search 'Wikimedia Commons'" may or may not work depending on the network access etc.

I think ideally the card should have a QR code of a link to the Play Store page, or at least a short link you can type quickly.

In addition to the design, logistics (printing and its cost) would be an issue, though.

**Comment by nicolas-raoul** [comment]
One of the most important things, I believe, would be to standardize how we call the app, so that a Google search gives relevant links.

"Commons app" gets lots of results about a college signup thing.
"Commons Mobile App" gives us the 3 first results.

So I would suggest calling the app "Commons Mobile App" in any speech or interview or news release or other PR stuff we have.
The actual app name in Play store and name once installed can stay what it is now, as obviously an app' name should not include "Mobile App", that would be redundant.

**Comment by misaochan** [comment]
Sounds good. Perhaps we could just put up the template on our website (The design could be a good task for a non coder wanting to get involved with the project), and see if anyone volunteers to print and distribute in their local events?

@nicolas-raoul I have been using Wikimedia Commons Android App for most of the PR stuff since that seemed most accurate to me. What do you think?

**Comment by whym** [comment]
nicolas-raoul's comment made me think about it. On second thought, adding big enough QR code images to prominent pages such as https://commons-app.github.io/, https://github.com/commons-app/apps-android-commons/ and https://commons.wikimedia.org/wiki/Commons:Mobile_app may be sufficient.

Anyone who tries to introduce the app has probably already bookmarked one of those pages (and if not, can do so easily). They will be able to load it on their phones and show it to others for scanning.

![commonsapp](https://cloud.githubusercontent.com/assets/10674/25806962/155aa1c8-3440-11e7-99c9-b2ef9b740f6f.png)

I agree using consistent names and URLs is important.

**Comment by VojtechDostal** [comment]
I have been calling it "Wikimedia Commons App" or as @misaochan suggests "Wikimedia Commons Android App", let's stick to that :) 

I am very happy to print the cards/leaflets for you and have them ready for the prehackathon (and you can bring them to Vienna), but you need to help me with information and design.

**Comment by nicolas-raoul** [comment]
Ah yes these names are probably better :-)

**Comment by neslihanturan** [comment]
It sounds very good to me. I can help with the design (I am not good at designing but I can implement with your suggestions). I can prepare it even tonight if someone has an idea about design, or a night during prehackathon.

**Comment by VojtechDostal** [comment]
Yes we can work on it during the prehackathon if time allows.
We will collectively decide on our priorities on Friday morning :)

**Comment by misaochan** [comment]
The leaflets have been made! :) Just waiting to put up the posters.
