### ISSUE TITLE
Translation issue with message Wikimedia:Commons-android-strings-description/nl

### ISSUE THREAD

**Issue by CiellB** [commons-app/apps-android-commons#5391]
Looking at the 'live' app, the word **Description** is used as the field to describe the title of the work. However, description often does not refer to 'Title' but to describe the depiction in the image. Can it be made more explicit which strings are used as 'Title" and therefore as title of the filepage as uploaded on Commons? 

Message URL: https://translatewiki.net/w/i.php?title=Special:Translate&showMessage=commons-android-strings-description&group=commons-android-strings&language=nl

**Comment by sivaraam** [comment]
> Looking at the 'live' app, the word Description is used as the field to describe the title of the work.

AFAIK, We actually use the Caption as the title for the work. We don't use the description as the title.

> However, description often does not refer to 'Title' but to describe the depiction in the image. Can it be made more explicit which strings are used as 'Title" and therefore as title of the filepage as uploaded on Commons?

I suppose I'm not understanding your query properly. Could you elaborate a bit for better understanding?

**Comment by CiellB** [comment]
Hi Sivaraam, sure, thanks for your response!

I am trying to untangle a miss in the Dutch translation, so that's an additional layer of complexity, haha. Maybe you can just direct me to the right string in Translatewiki to correct the translation.

I am a beta-tester btw, but I assume new translations go live in the Beta app as well?
['Bijschrift' = caption](https://www.interglot.com/dictionary/nl/en/search?q=bijschrift&m=click), but in the Dutch translation is used where it should say 'Title'. 
![Screenshot_20231128_083909_Commons](https://github.com/commons-app/apps-android-commons/assets/88162036/a67db4f4-b4da-4ca6-885c-09d83a0cddc2)
![Screenshot_20231128_084135_Commons](https://github.com/commons-app/apps-android-commons/assets/88162036/debff3dc-8377-4770-9ca0-71d1e94ddd55)

**Comment by nicolas-raoul** [comment]
@CiellB Thank you for translating, for beta-testing, and for your questions!

- I totally agree with you that we must document the strings, since translatewiki provides such a feature.
- New translations do not go live in the Production nor Beta apps immediately, we have to test and release before, so it typically takes a few months unfortunately.
- Smartphones are a great tool for taking geolocalized+timely pictures, but they are a very bad tool for typing, so we had to make hard choices to reduce typing. Thus we only ask for two fields: caption and description. Then we reuse the caption as a title (filename), automatically adding a suffix if necessary for uniqueness.

If anything is unclear, please do not hesitate to ask. :-)

**Comment by nicolas-raoul** [comment]
I added documentation to the strings.
If you notice any other ambiguous string, please let me know! :-)
