### ISSUE TITLE
Displaced icons in Contributions/Nearby/Explore tab

### ISSUE THREAD

**Issue by RitikaPahwa4444** [commons-app/apps-android-commons#5460]
### Summary

Some of the icons are not at their intended positions

### Steps to reproduce

1. Open the app
2. Check Contributions/Nearby/Explore

### Expected behaviour

The icons should be in proper place.

### Actual behaviour

Icons are displaced.

### Device name

Redmi 5A

### Android version

8.1.0

### Commons app version

main and prodDebug

### Screen-shots

Contributions:
![contributions_fragment](https://github.com/commons-app/apps-android-commons/assets/83745993/cd8373d2-b846-43d8-ade6-1a7d583c7614)

Explore > Map (target icon):
![explore](https://github.com/commons-app/apps-android-commons/assets/83745993/38d09350-1b02-439f-a71f-424118f7ee55)

Nearby:
![nearby](https://github.com/commons-app/apps-android-commons/assets/83745993/1f47e98d-6d70-4757-8805-21e389cc2540)

### Would you like to work on the issue?

None

**Comment by nicolas-raoul** [comment]
Thanks for the report!
Interestingly it is working fine on my device (Android 14).

**Comment by rohit9625** [comment]
It's working fine on my device too. @RitikaPahwa4444 did you build the app from repo or download it from somewhere?

**Comment by RitikaPahwa4444** [comment]
I'm using master branch, prodDebug flavor.

**Comment by rohit9625** [comment]
I am also using the same. What is the screen size of your device or emulator?

**Comment by RitikaPahwa4444** [comment]
5 inches, when measured diagonally.

**Comment by rohit9625** [comment]
The issue with the small screen sizes. I try to install the app on a emulator with screen size 4.6 inches and getting the same as your screenshots :
![Screenshot 2024-01-21 183147](https://github.com/commons-app/apps-android-commons/assets/101377978/c5e35234-4614-44b2-8338-4dca72f2b27e)


![Screenshot 2024-01-21 183204](https://github.com/commons-app/apps-android-commons/assets/101377978/efbbbb7e-dbe0-4d92-b2e0-0a72f29df5be)

**Comment by RitikaPahwa4444** [comment]
It's been a year now, this is for the first time I've noticed this problem. It was working fine, at least until December 2023. It's very likely that some recent changes are affecting it.

**Comment by rohit9625** [comment]
Build a previous version then.

**Comment by rohit9625** [comment]
For how long have you using this device @RitikaPahwa4444?

**Comment by RitikaPahwa4444** [comment]
Using since 2018, I guess. The model was old even back then, but the Commons app is supported even on devices running API level 21 (mine is 27) to ensure it's widely accessible. Irrespective of the API level or how old the phones are, screen sizes should not impact the app.

**Comment by nicolas-raoul** [comment]
Thanks both, great findings!

For any volunteer willing to work on this, I think the next actions should be:
1. Reproduce the issue, if necessary with an emulator to simulate a small screen size.
2. Identify from which commit this is happening. `git bisect` can help you do this efficiently.
3. See what changed in that commit, try to revert it, see whether that solves the issue.
4. Change code so that the commit's intention is still fulfilled.

**Comment by rohit9625** [comment]
Yes, you are right. Now, how can we find which PR affected this behavior?

**Comment by rohit9625** [comment]
Thank you Mr. @nicolas-raoul, we'll work on this.

**Comment by ShashwatKedia** [comment]
@RitikaPahwa4444 I borrowed my friend's phone (Realme 6) and could reproduce the error on master branch. But when I tested branch of PR #5418, it worked fine. Is it the same for you?

**Comment by rohit9625** [comment]
@ShashwatKedia 
Realme 6 has a 6.5-inch screen size. The issue will not appear in that size. You need to test it on a small screen device or create an emulator for instance.

**Comment by RitikaPahwa4444** [comment]
@ShashwatKedia, posted some screencasts on the other issue where I was checking your branch (#5461). I'm able to reproduce it there as well.

**Comment by ShashwatKedia** [comment]
Oh, sorry posted comment in wrong issue

**Comment by ShashwatKedia** [comment]
Oh, sorry posted comment in wrong issue

**Comment by rohit9625** [comment]
For the previous version, the icons were displayed in their right positions. I tried reverting several commits but did not find where this behavior occurred. When was the last time you(@RitikaPahwa4444) tested the app before this behavior?

**Comment by rohit9625** [comment]
Yes just before the current version.

**Comment by RitikaPahwa4444** [comment]
If by version you're referring to the releases, then that happened way back in Oct 2023. I'm talking about the `prodDebug` flavor. Running `git bisect` with [`ffd157d`](https://github.com/commons-app/apps-android-commons/pull/5399/commits/ffd157d1b8cf6c1c44b086da85416553dc25d31d) and [`2c086b3`](https://github.com/commons-app/apps-android-commons/commit/2c086b3d79ceed7be0ea2ceeda6feb36e54122f1) should work.

**Comment by rohit9625** [comment]
> I already tried for commit `2c086b3d79ceed7be0ea2ceeda6feb36e54122f1`, and it didn't worked.

**Comment by RitikaPahwa4444** [comment]
Were you not able to reproduce this issue([this](https://github.com/commons-app/apps-android-commons/issues/5460#issuecomment-1902623130) comment above)? Now the task is to look for the last commit which has every icon in its place, so that we know when this problem started happening.

**Comment by RitikaPahwa4444** [comment]
> Are you going to look for those commits now?

No, not as of now. I'll try running git bisect by next weekend and share my findings, but, please feel free to take it up if you're able to figure that commit out.

**Comment by rohit9625** [comment]
Sure I will :)

**Comment by nicolas-raoul** [comment]
@rohit9625 Thanks for volunteering! Ritika is a senior developer of the app, having her run `git bisect` is not the best use of her time. On the opposite, it would be a good experience for you if you have never done one, as it is a must-have skill for developers. You will need to find any tutorial or video on the topic (preferably geared toward the IDE you are using), understand the concept, then apply it to the present issue with rigor. All included it will probably take 2  or 3 hours, I would say. What do you think? 🙂

**Comment by kuldeep1A** [comment]
i fix those type issue ..

**Comment by rohit9625** [comment]
Using git bisect helped me a lot :)
Thank you @nicolas-raoul, as you said it barely took me 2 hours to learn and find the issue.
I figured out the commit which caused the inappropriate behavior. This is the commit [`b3a4e87`](https://github.com/commons-app/apps-android-commons/commit/b3a4e8731e0e95db79917b287cacf8f7affc6c38), after which the issue occurred.

The changes in file `app/src/main/res/values/styles.xml` and `app/src/main/res/layout/fragment_contributions_list.xml` causes the issue, not the other ones.
However, I didn't get why these files were modified because it doesn't make any changes to the UI.

After discarding those changes the application is looking fine. 
![image](https://github.com/commons-app/apps-android-commons/assets/101377978/3b39fa09-40dd-450b-b7cb-baed332ac9a8)

**Comment by nicolas-raoul** [comment]
@rohit9625 Fantastic! Looking forward to your PR. 🙂

**Comment by ShashwatKedia** [comment]
> The changes in file `app/src/main/res/values/styles.xml` and `app/src/main/res/layout/fragment_contributions_list.xml` causes the issue, not the other ones.
> However, I didn't get why these files were modified because it doesn't make any changes to the UI.

Discarding these files does make a change to the UI, as the + button of the floating action button's colour was changed in that style file. But the main question is why/how, changing just the tint/colour of a button would cause such an issue, that too only on small devices. @nicolas-raoul your thoughts on this?

**Comment by ShashwatKedia** [comment]
@rohit9625 Also, the issue was with the target icon (in the nearby tab) as well. Is that also happening because of this particular commit?

**Comment by rohit9625** [comment]
No, the target icon was working fine with the commit and after reverting the changes as well.
And yeah, I also wonder how can this small change can cause this behavior.

**Comment by rohit9625** [comment]
After some research, I found that the styles were defined incorrectly in the `styles.xml`. We should first define a style like this :
`<style name="AppTheme.FloatingActionButton" parent="Widget.MaterialComponents.FloatingActionButton">
<item name="backgroundTint">@color/your_tint_color</item>
    
</style>`

Then we can define colors as you defined in that file. Also, I think that it is not that necessary because without those colors the icon has more visibility.
![image](https://github.com/commons-app/apps-android-commons/assets/101377978/d0a37c40-12b2-4e2e-af76-64e37951f5c7)

But with those colors, it's looking like this in the dark mode (ignore the gravity of the icon):
![image](https://github.com/commons-app/apps-android-commons/assets/101377978/8de0afc0-3dad-4861-b0e7-9b7fcbb3d449)

One last question, i.e., you must have used these colors for some reason. Can you please tell me that? 
Because maybe this was necessary somewhere else. So that we can find other ways to resolve this.
@ShashwatKedia

**Comment by ShashwatKedia** [comment]
I don't know if it's relevant, now that the issue seems to be solved, but the problem was with the API level of the device, not the screen size. I tried several API and screen size combinations and I could reproduce the issue on Pixel 6 pro with API Level <=30 but not on API Level >= 31. The same was the case with Galaxy Nexus, which has a 4.65-inch screen size.

**Comment by rohit9625** [comment]
Oh, so that is the problem. I thought the screen size was the problem. Thank you for looking into it :)

**Comment by nicolas-raoul** [comment]
Merged, thanks @rohit9625 and @ShashwatKedia !

Anyone if you observe the issue again do not hesitate to reopen. :-)
