### ISSUE TITLE
Selected 18 pictures for multi-upload, but Upload Wizard only asks metadata for 1 picture

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5477]
![Screenshot_20240125-092335~2.png](https://github.com/commons-app/apps-android-commons/assets/99590/082dc429-6495-41b5-adaa-fc4561cb760a)

![Screenshot_20240125-092310.png](https://github.com/commons-app/apps-android-commons/assets/99590/294d28c4-119a-4872-83d5-b8a0a0668718)

Tasks:
1. Run gitbisect to find the problematic commit.
2. Revert it, or even fix the commit if you can.

**Comment by rohit9625** [comment]
Can I take this one Mr. @nicolas-raoul ?

**Comment by nicolas-raoul** [comment]
@rohit9625 Yes thanks! 🙂

**Comment by rohit9625** [comment]
I found out that after PR #5466, the issue occurred. The problem is not only with the large number of uploads but also when we upload 2 images at least.

**Comment by rohit9625** [comment]
The issus is here :
![image](https://github.com/commons-app/apps-android-commons/assets/101377978/8aa3cca1-e8b4-44b4-9ee2-2c640c028064)


It adds a callback only for 1st fragment not for all other fragments. And I am unable to figure out what should I do to avoid adding this for only 1st fragment.
Because when I changed the code to this :
![image](https://github.com/commons-app/apps-android-commons/assets/101377978/de7118d8-f8b3-46e6-b2d0-8e90233456c8)

The app again crashed.😑

Can you please look at it Mr. @shashankiitbhu

**Comment by shashankiitbhu** [comment]
Sure

**Comment by shashankiitbhu** [comment]
I think #5478 Fixes the issue, this PR correctly Implements the logic for Multiple Uploads. @nicolas-raoul Please Review the PR
