### ISSUE TITLE
Nearby: Some pins disappear after switching apps

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5482]
... even though I didn't change location (using FakeGPS).

Observed on main branch at 96b2608eb11bbb3547c5b36a851beef90282d3a7, but might have started earlier. `git bisect` will most probably help.

https://github.com/commons-app/apps-android-commons/assets/99590/576a469c-ec87-4a3e-ab08-a94f1143c611

**Comment by shashankiitbhu** [comment]
I think this issue is related to that configuration change issue that I am currently working on in my other PRs , can you assign this to me @nicolas-raoul

**Comment by rohit9625** [comment]
Did you find out where is the problem? If not then please find it first :)

**Comment by nicolas-raoul** [comment]
I think it is fine to get assigned before starting to investigate. :-)

**Comment by rohit9625** [comment]
Yes, you are right. But what I think is, that we should first reproduce the issue and then have a scenario ahead of how a particular issue will be solved. 
: )

**Comment by nicolas-raoul** [comment]
Yes, being able to reproduce can probably be considered a minimum. Different projects have different rules/habits though. 🙂

**Comment by rohit9625** [comment]
Well yeah 🙂

**Comment by shashankiitbhu** [comment]
@nicolas-raoul I examined the issue well and I was able to reproduce it as you can see below 

https://github.com/commons-app/apps-android-commons/assets/126143257/1ededad1-72d1-4796-8ec2-fd6db5266087

on deep examination, I found out that this issue is not of some pins disappearing but rather extra pins loading when the view is created, which is because of a duplicate call for ```performMapReadyActions()```  in ```onViewCreated```
![WhatsApp Image 2024-02-04 at 1 49 58 PM](https://github.com/commons-app/apps-android-commons/assets/126143257/69c72de8-59d5-4928-893b-fd1568c0decc)
It calls ```performMapReadyActions()``` but also ```onResume()``` (even if it doesn't call onResume(), it will get called anyways because it's a lifecycle event) and ```onResume``` also calls the ```startMap()``` which calls ```performMapReadyActions()```
![WhatsApp Image 2024-02-04 at 1 54 00 PM](https://github.com/commons-app/apps-android-commons/assets/126143257/1df84324-35ab-4b08-b9f7-9e871d407ca8)
![WhatsApp Image 2024-02-04 at 1 53 49 PM](https://github.com/commons-app/apps-android-commons/assets/126143257/4c46a7a8-ce5c-403c-97bd-d23eeed7884c)

Due to this repeated call, an extra number of pins are loaded (which could have been otherwise loaded when recentering the map and searching the area), but when you switch apps only ```onResume``` is getting called (as it should be) and ```onViewCreated``` so the ```performMapReadyActions()``` is not called twice which gives us the impression that some pins have disappeared (which is not really the case 😅 )

**Comment by nicolas-raoul** [comment]
Working fine now.
