### ISSUE TITLE
Commons app feedback with reference to GitHub

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5563]
### What is the user problem or growth opportunity you want to see solved?

From my point of view, it is an invaluable advantage that the Commons App allows you to leave feedback ( https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback ) without having to be logged in to GitHub.

At the same time, I think it would be good if it were pointed out that feedback is better submitted via GitHub. Perhaps it would be enough to simply provide a link to GitHub! ( https://github.com/commons-app/apps-android-commons/issues )

### How do you know that this problem exists today? Why is this important?

Feedback is left on Commons, but processing is better if the feedback is stored directly on GitHub.

### Who will benefit from it?

all users

**Comment by OpenGreenStreet** [comment]
I had thought that a link to GitHub would be offert here: https://commons.wikimedia.org/wiki/File:20240218_xl_1536-Commons_AppFeedback.png

**Comment by neeldoshii** [comment]
Can i get this issue assigned?

**Comment by neeldoshii** [comment]
Implemented in BottomSheet a place for users to give feedback on Github.
Concerns : 
1. What should be the text for feedback on github. 

What do you think about this?

https://github.com/commons-app/apps-android-commons/assets/60827173/f60d2287-db80-4cb0-b49b-ddb37eb0ea1d

Should I now release a PR for this?
@nicolas-raoul @OpenGreenStreet

**Comment by OpenGreenStreet** [comment]
I really like the proposed solution!

Question: My Wikipedia and GitHub accounts have different names and passwords. Would it also be possible to store my different GitHub account in the Commons app?

**Comment by neeldoshii** [comment]
> Question: My Wikipedia and GitHub accounts have different names and passwords. Would it also be possible to store my different GitHub account in the Commons app?


Sorry, I didn't understood your question exactly. 
When you click feedback on Github it will open it on the web browser now over there whichever Github account you logged in will be used to send feedback from that account. Wikipedia account will have no relation to it.

**Comment by ShashwatKedia** [comment]
> What do you think about this?

Hey @neeldoshii I just saw your implementation and it looks good. Sorry for my late feedback, but I don't think that we should add another item to the bottom menu, as it's already pretty long. Also, in case you didn't know, our app already has a link which opens the issues section of the GitHub repo of the Commons app. You can find it inside the 'About' section in the bottom menu.

What we can do is integrate the GitHub link into the normal Feedback dialog. Maybe we can add the link at the bottom of the dialog as a link, "Send feedback on GitHub", clicking which will open the Issues section. @nicolas-raoul your thoughts on this?

**Comment by OpenGreenStreet** [comment]
> > Question: My Wikipedia and GitHub accounts have different names and passwords. Would it also be possible to store my different GitHub account in the Commons app?
> 
> Sorry, I didn't understood your question exactly. When you click feedback on Github it will open it on the web browser now over there whichever Github account you logged in will be used to send feedback from that account. Wikipedia account will have no relation to it.

I had thought about saving the GitHub password in the Commons app (if desired), so that an automatic login to the GitHub web frontend would be possible.

**Comment by nicolas-raoul** [comment]
Sorry for coming late to this, or for not defining what would be the best solution.

Strategies that I do not think are ideal:
- I also think that having two different `Feedback` items in the menu is not ideal.
- Moving the link to the bottom of the existing feedback dialog is an option, but I fear that some users will fill the fields then click the button, thus losing the input.
- Adding a "Send to GitHub" button to [pre-fill a GitHub issue](https://github.com/commons-app/apps-android-commons/issues/new?body=This%20is%20a%20prefilled%20comment) is not a good idea because it will fail for people who are not logged into GitHub.

So, I think this strategy might be the best: Upon `Feedback` being clicked, show a small dialog asking the user `Do you have a GitHub account?`, if yes open https://github.com/commons-app/apps-android-commons/issues, if not open the normal dialog. Other ideas welcome though. :-)

Cheers!

**Comment by ShashwatKedia** [comment]
> - Moving the link to the bottom of the existing feedback dialog is an option, but I fear that some users will fill the fields then click the button, thus losing the input.

Yeah, but to solve that we could copy the issue description to the clipboard, when the user clicks on the link and show a toast to the user that their issue description has been copied. 

> So, I think this strategy might be the best: Upon `Feedback` being clicked, show a small dialog asking the user `Do you have a GitHub account?`, if yes open https://github.com/commons-app/apps-android-commons/issues, if not open the normal dialog. Other ideas welcome though. :-)

I am not aware of what percent of our users have a GitHub account, because if a large percent don't have an account then it would be an additional step. Though, if a large userbase has an GitHub account then this would be a good solution :)

**Comment by nicolas-raoul** [comment]
I think the clipboard is not a very reliable way to store the text that the user typed, speaking from experience I sometimes get my clipboard content overwritten haha... especially on mobile where more urgent tasks (such as work emails or friend messages) often pop up.

> would be an additional step

True, but a small additional step, compared to re-typing everything. :-)

**Comment by ShashwatKedia** [comment]
> True, but a small additional step, compared to re-typing everything. :-)

Fair enough, better safe than sorry ;)
