### ISSUE TITLE
[Bug]: On the personal page, some numerical values are not legible on the smartphone (too small)

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5565]
### Summary

On the personal page, some numerical values are not legible on the smartphone (too small)

### Steps to reproduce

go to personal overview

### Expected behaviour

the figures should be displayed larger

### Actual behaviour

the numerical values are too small

* On the personal page, some numerical values are not legible (too small).

* Their meaning is unclear to me (also (i) does not clarify sufficiently (what number of what: 4317/2560 or 709/1280? What refers to what?))

* An overview of the images used would be nice (by tapping on (here) "(709/1280)")

### Device name

Google Pixel 7 Pro

### Android version

Android 14

### Commons app version

4.2.1~14b6c455b

### Screen-shots

https://commons.wikimedia.org/wiki/File:20231215_xl_0658_xl_CommonsApp-Screenshot.png
https://commons.wikimedia.org/wiki/File:20240218_xl_1731-Commons_App_Feedback.png

https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#Feedback_from_Molgreen_for_version_4.2.1~14b6c455b_7

### Would you like to work on the issue?

None

**Comment by kanahia1** [comment]
How about removing the circle around the text OR replacing it with Linear Progress Bar, since it will give more space for text to breathe?

**Comment by nicolas-raoul** [comment]
Linear progress bar sounds good. :-)

**Comment by neeldoshii** [comment]
I would like to take it up. 

@nicolas-raoul 
Few Questions before starting it up.
is there any way to test the code on production environment. This requires testing on production environment (currently leaderboard is only supported on production environment not on debug).

**Comment by ShashwatKedia** [comment]
> Few Questions before starting it up.
> is there any way to test the code on production environment. 

Yes, you can use the prodDebug build variant to test the production server.

>This requires testing on production >environment (currently leaderboard is >only supported on production >environment not on debug).

Actually, the leaderboard is supported on the prod flavour, not on the beta flavour. But it works on debug variant correctly (since to test the release variant you'll have to sign it, it's better to use the prodDebug variant). To know more about flavours and build variants look up [this](https://developer.android.com/build/build-variants#product-flavors)

**Comment by nicolas-raoul** [comment]
I would recommend always using prod, unless you are actually uploading and have zero self-authored encyclopedic pictures.

**Comment by neeldoshii** [comment]
@nicolas-raoul just a proposed solution, not a thought towards complexity & priority.

**This is the current the UI we currently have**

![image](https://github.com/commons-app/apps-android-commons/assets/60827173/d57df292-0a86-4aa3-bc2c-67b6493b1525)

** This is the solution which will solve this issue, increase performance, and good user experience, removal of third party dependency `(<com.dinuscxj.progressbar.CircleProgressBar)`**

![image](https://github.com/commons-app/apps-android-commons/assets/60827173/3f2c418d-5f45-44c2-963e-887cb9509cb5)

If we wish to go with this my view would be revamp the fragment_achievement due to linear nesting, third party dependency and not use the recycler view as of now. 

Once this get merged we can start working on adapting this towards recycler view if we wish. Thus reducing the complexity and number of changes. 

This is what I thought feel free to leave the feedback is it worth a go?

**Comment by neeldoshii** [comment]
Just a friendly ping @nicolas-raoul, Can i implement the proposed solution?

**Comment by RitikaPahwa4444** [comment]
Is a recycler view really required?🤔I don't think we've too many changes from the server side, the list isn't dynamic. Only the stats change, and we need an appropriate way to display them so that they're legible enough as the number of digits increases.

**Comment by neeldoshii** [comment]
> Is a recycler view really required?🤔

Well, you are right there is not much need for it. Listview will do all the work. 

So, in order to fix 1/2 issue of the current above issue, can I alter this like this and this refactor will fix the issue on smaller devices. 

![image](https://github.com/commons-app/apps-android-commons/assets/60827173/5e689034-e1f8-4b40-8836-8d71fbc789f6)

What do you think about this @RitikaPahwa4444 ?

**Comment by nicolas-raoul** [comment]
The numbers are much more readable indeed. :-)
Keeping this page attractive and fun is important, it should look like a game stats page.
How about something like this (with a green progress bar, and 18/25 instead of 60%):
<img width="333" alt="Screenshot 2024-03-27 at 16 40 20" src="https://github.com/commons-app/apps-android-commons/assets/99590/3aaa81ed-e9bd-461a-b74d-7a04e3188713">

**Comment by neeldoshii** [comment]
> How about something like this (with a green progress bar, and 18/25 instead of 60%):

Works fine. Working on it.

**Comment by nicolas-raoul** [comment]
@neeldoshii  I unassign for now, but if you are you still working on this, please let us know. If no answer, someone else may be assigned to it. Thanks a lot. :-)

**Comment by neeldoshii** [comment]
Hi @nicolas-raoul, I am quite occupied lately It would be best if someone who can take it ahead. for someone who's working on this u can take this reference #5666

**Comment by nicolas-raoul** [comment]
@neeldoshii Understood, thanks! 🙂
