### ISSUE TITLE
values-yue-hant: Resource and asset merger: Invalid resource directory name

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5571]
```
> Task :app:mergeProdDebugResources FAILED
ERROR: /Users/nicolasraoul/src/commons-app/app/src/main/res/values-yue-hant: Resource and asset merger: Invalid resource directory name
```

Very similar past fix:
https://github.com/commons-app/apps-android-commons/pull/5040
https://gerrit.wikimedia.org/r/c/translatewiki/+/826587

Good issue for someone familiar with Gerrit, just mimic the fix above.

Workaround for anyone trying to build: Remove that folder.

**Comment by nicolas-raoul** [comment]
Anyone interested in this issue?
Good opportunity to experience Gerrit with a tiny change. :-)

**Comment by shashankiitbhu** [comment]
I'll work on it, was waiting for newcomers to try it as it's a good first issue.

**Comment by shashankiitbhu** [comment]
@nicolas-raoul For me renaming the directory seems to work fine and I am able to build and run apk without any issues, Should I make a PR ?

**Comment by abhinandan-verma** [comment]
@nicolas-raoul  Kindly give this work to me, I shall do it.

**Comment by neeldoshii** [comment]
Did a well go through I have two proposed solution.

While I was installing the project locally I faced the issue.

```
AGPBI: {"kind":"error","text":"Invalid resource directory name",
Execution failed for task ':app:mergeBetaDebugResources'.
> /project-directory/apps-android-commons/app/src/main/res/values-yue-hant: Error: Invalid resource directory name
```

values-yue-hant is basically used for Cantonese speakers who read Traditional Chinese characters. But the issue here arises is that Android's resource management system may not recognize `values-yue-hant`. 

<img width="825" alt="image" src="https://github.com/commons-app/apps-android-commons/assets/60827173/b563f362-7f8b-4cbb-83dc-909f32159c4d">

We already have resource `zh-rHK` & `zh-rTW`
For `values-zh-rHK`, focus on Cantonese-specific wording. For `values-zh-rTW`, focus on standard Traditional Chinese.
 
1. There is no need for redundant `value-yue-hant` and can be elimated is the first proposed solution. 

2. The second thing which we can do is 
  
![image](https://github.com/commons-app/apps-android-commons/assets/60827173/7e1adc0d-3cbb-487e-98f7-6063d19ab1bf)

Create two directory for simplified and traditional and include all region from it,
 
 
@nicolas-raoul What do you think of it? I did checked #5573 so if removing `value-yue-hant` is not the recommended solution then we can move to 2nd proposed solution.

Also can I get assigned to this issue?

**Comment by nicolas-raoul** [comment]
Even if we move or remove it, the folder will be recreated by translatewiki.

The most importnt is to modify the translatewiki configuration in gerrit, see similar issue in initial description.

**Comment by rohit9625** [comment]
I added a commit on Gerrit - https://gerrit.wikimedia.org/r/c/translatewiki/+/1007685

**Comment by rohit9625** [comment]
I made the new changes and sorry I didn't notice that at first.

**Comment by rohit9625** [comment]
Do I need to link a PR because I didn't make any changes to the files on my PC?

**Comment by nicolas-raoul** [comment]
Thanks for posting the link https://gerrit.wikimedia.org/r/c/translatewiki/+/1007685 that's enough. :-)
