### ISSUE TITLE
category search for "Hansaviertel" does nnot find Category:Holsteiner Ufer (Berlin-Hansaviertel)

### ISSUE THREAD

**Issue by OpenGreenStreet** [commons-app/apps-android-commons#5588]
### What is the user problem or growth opportunity you want to see solved?

Searching by category is not optimal on a smartphone

It would be nice if the search for categories could be "optional":
Example: I search for "Hansaviertel" and the Category:Holsteiner Ufer (Berlin-Hansaviertel) would also be offered to me in the selection list of categories

### How do you know that this problem exists today? Why is this important?

When uploading, I need to know exactly which categories exist and how they are written

### Who will benefit from it?

all users

### Anything else you would like to add?

see also: https://commons.wikimedia.org/wiki/Commons:Mobile_app/Feedback#Feedback_from_Molgreen_for_version_4.2.1~14b6c455b

**Comment by sivaraam** [comment]
For reference, as mentioned in https://github.com/commons-app/apps-android-commons/issues/5712#issuecomment-2107593881, this is due to our category search bringing only prefix matches. So, I'm closing this issue in favour of continuing the discussion at #3179 where we could discuss about fixing various scenarios related to category search.

Feel free to re-open if I seem to have misunderstood the issue.
