### ISSUE TITLE
Tapping outside popup dialog closes it, potentially making user miss it

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#5778]
... especially when uploading many pictures.

I would suggest making such dialogs modal.

https://github.com/user-attachments/assets/9b66d25d-7b45-4dd9-8a1b-899d8f3201da

**Comment by Akshaykomar890** [comment]
Can I work on this ?

**Comment by nicolas-raoul** [comment]
Hi @Akshaykomar890 and thanks for your interest!

Would you mind choosing a bug from the list at https://github.com/commons-app/apps-android-commons/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+-label%3Adebated+label%3Abug+-label%3A%22low+priority%22 ?

Per https://github.com/commons-app/commons-app-documentation/blob/master/android/Volunteers-welcome!.md#developers

Thank you! :-)

**Comment by ersalazar** [comment]
Hello; can i work on this?

**Comment by parneet-guraya** [comment]
Could you confirm this again? I tried this by making the dialog show indefinitely (by disabling the code that dismisses it on showLoading(false) event) and on tapping outside or pressing back doesn't dismiss the dialog. I tried in this very same screen. 

https://github.com/user-attachments/assets/a354e854-1352-4e49-9914-7205268e7b36



Any chance you're talking about that dialogs should be not cancelable anywhere in the app?

**Comment by nicolas-raoul** [comment]
This is about this dialog seen in the screencast above:
![Screenshot_20241208-103117.png](https://github.com/user-attachments/assets/55b8ba82-b418-4c53-befa-97d7160765e3)

**Comment by parneet-guraya** [comment]
Got it! 

So, in the API that we use to build these dialogs we have this `setCancelable(boolean)`  which affect both touching outside it's bounds as well as back press meaning if set `false` it wouldn't let user dismiss the dialog upon back press as well, which we don't intend right? I just want to confirm this because if we want to disable the `touch outside` part only then we may have to  use something else.

So, we have two options:
- use the above `setCancelable(boolean` (disabling both outside touches & back press) and rely on the buttons that dialogs have.
- as stated above, have some way out to only block outside touch and not block back press events.

Also, I think both `touching outside` & back press disable would make sense only in loading dialogs

**Comment by nicolas-raoul** [comment]
There is a "No" button so I would say disabling Back is OK if easier to implement/maintain. 🙂
