### ISSUE TITLE
Warn if folder to delete contains subfolders

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#6020]
The custom picker has a feature to delete the current folder, it has to be enabled in the settings.

Problem: it does not warn if the folder contains subfolders:
![Screenshot_20241211-072319.png](https://github.com/user-attachments/assets/a6f11ceb-a56e-4516-8c2e-ef835a8a9cb4)
![Screenshot_20241211-072240.png](https://github.com/user-attachments/assets/4068b4f3-4bea-4eef-81bb-f84a30390416)

Solution: If the folder contains subfolder, add at the beginning of the popup (or as a different initial popup if needed) that says something like:
```
Warning: This folder contains the following non-empty subfolders:
Messenger
Panorama
Screenshots
```

Sub-sub-folders/etc would be a nice plus if easily done, but not strictly necessary.

**Comment by savsch** [comment]
I'd like to start contributing to this project. Could this issue be assigned to me?

**Comment by savsch** [comment]
@nicolas-raoul, in my opinion choosing not to delete any subfolder is preferable to deleting them (with or without warning), because it aligns more with the typical end-user's expectation of a gallery folder being "flat" (i.e. containing media files and not subfolders).

That being said, I have no problems simply implementing a warning for the presence of subfolders as requested in the issue description. I am just sharing my perspective here for consideration.

Should I go ahead with implementing a warning, or change the deletion logic so as to not delete subfolders?

**Comment by savsch** [comment]
@nicolas-raoul, in my view, choosing not to delete any subfolder is preferable to deleting them (with or without warning), because it aligns more with the typical end-user's mindset of a gallery folder being "flat" (i.e. containing media files and not subfolders). Also because the custom picker does not list the media contained within subfolders.

That being said, I have no problems simply implementing a warning for the presence of subfolders as requested in the issue description. I am just sharing my perspective here for consideration.

Should I go ahead with implementing a warning, or change the deletion logic to not delete subfolders?

**Comment by nicolas-raoul** [comment]
Fantastic insight, you are totally right. Actually, would you mind checking what is the current behavior? Do the subfolders get deleted or not?

**Comment by savsch** [comment]
> Fantastic insight, you are totally right. Actually, would you mind checking what is the current behavior? Do the subfolders get deleted or not?

Yes, the subfolders do get deleted under the current behavior.

To be precise:
1. For API Level 30 and above, all media (images, video and audio) contained inside the selected folder (and any of its subfolder/sub-subfolder/etc) get deleted. (because the query is of the form `"${MediaStore.MediaColumns.DATA} LIKE $folderPath/%"`:
The current code:
```kt
        val mediaUris = listOf(
            MediaStore.Images.Media.EXTERNAL_CONTENT_URI,
            MediaStore.Video.Media.EXTERNAL_CONTENT_URI,
            MediaStore.Audio.Media.EXTERNAL_CONTENT_URI
        )

        for (mediaUri in mediaUris) {
            val selection = "${MediaStore.MediaColumns.DATA} LIKE ?"
            val selectionArgs = arrayOf("$folderPath/%")

            contentResolver.query(mediaUri, arrayOf(MediaStore.MediaColumns._ID), selection,
                selectionArgs, null)
                ?.use{ cursor ->
                val idColumn = cursor.getColumnIndexOrThrow(MediaStore.MediaColumns._ID)
                while (cursor.moveToNext()) {
                    val id = cursor.getLong(idColumn)
                    val fileUri = ContentUris.withAppendedId(mediaUri, id)
                    urisToTrash.add(fileUri)
                }
            }
        }
```

2. On API levels lower than 30, the selected folder (and anything  inside it, including non-media items) gets recursively deleted: `folder.deleteRecursively()` (thus also obliterating any subfolder within).

**Comment by savsch** [comment]
Thank you for the clarification! I'm happy to update the behavior as you've requested, even though it wasn't mentioned in the original issue description.
Working on the fix.
