### ISSUE TITLE
Allow multiple uploads from within the app

### ISSUE THREAD

**Issue by sandarumk** [commons-app/apps-android-commons#604]
The current version of the app only allows multiple uploads when it is used inside of the Gallery. It do not let users to select multiple images to upload.

**Comment by misaochan** [comment]
Agreed. To clarify, MultipleShareActivity only gets called if the user starts from their gallery, selects more than one image, and clicks "share". We should allow multiple image selection from within our app as well. I imagine we would probably need to refactor ShareActivity first though so we can reuse the shared logic.

**Comment by misaochan** [comment]
We may need to think about 'what sort' of multiple uploads we would like to allow. The browser-based Upload Wizard allows any multiple uploads, even of unrelated pictures - all pictures must have their titles, desc, and categories selected separately later.

I propose that we do not allow this, but instead only allow multiple uploads of ONE subject. So instead of having the user type in titles, desc, categories for all of them, they need only do it once (this also simplifies the UI logic IMO). However we need to make this explicit to the user somehow (perhaps in the tutorial or via a one-time popup during the first time they submit multiple images).

**Comment by nicolas-raoul** [comment]
I am a heavy user of the app but I have almost never used multiple upload. Is it really needed? It sounds like it might lead some people to upload a lot of pictures with only approximate titles/categories.

**Comment by misaochan** [comment]
Ah, interesting. I would personally use them, especially if I was taking photos of an event or of a particular location from a few angles.

Would anyone else like to weigh in?

**Comment by misaochan** [comment]
This will be done in the later half of the IEG renewal. 

**Use case:**
Currently, the only way to submit multiple uploads (many files in one upload step) is to go to the Android gallery app, select more than one image, and click "share". We would like to implement multiple image selection from within our app as well, to prevent the need for re-submitting many times if the user has several different images of the same item. This might have the beneficial side effect of reducing overwrites, and is also necessary prior to implementation of overwrite prevention at #703 , as otherwise users will be prompted for every single successive image of the same title that they upload.

**Scope:**
* Modify the intent triggered by the "upload from gallery" button to allow multiple uploads -
 https://stackoverflow.com/questions/44082151/multiple-images-select-from-gallery
* Decide how to handle multiple uploads, and if MultipleShareActivity can be generalized to include multiple uploads from within the app
* Decide how we want to handle titles and descs. My suggestion would be to make it explicit to the user somehow that multiple uploads should only be done for multiple pictures of the same thing (similar to how it currently works under "Share"), NOT for pictures of different things (which is allowed by the browser Upload Wizard because they allow you to title each pic individually). If we do this, then we can mostly reuse our current ShareActivity UI, except with the addition of the information above
* Handle file titles to ensure we don't overwrite filenames

**Comment by misaochan** [comment]
Based on discussion on the gamification issue #85 , I think it would indeed be a good idea for the multiple upload feature to eventually be dependent on the user's upload vs deletion statistics. Perhaps if we do manage to find a way to ascertain % of reverts for a particular username, we can set a requirement like "at least 50 uploads, and less than 10% of uploads are reverted".

That is out of the scope of both our grant task and GSoC, though. So for the moment, to be safe, my proposal would be:

- Multiple uploads should only be done for images of the same thing (ergo only one title and desc, with numbers appended as a suffix automatically). We probably want to make this explicit to the user by having text in the upload screen that says: "Provide a title and description for these [n] images", where we fill [n] in with the number that the user selected.
- For the time being, limit the number of uploads per upload round to 5. I think this should be mostly enough for legitimate users (I have never needed more than 3-4 personally), but will prevent new users from "uploading their entire camera roll". Later on, we can consider increasing the limit for users with very good stats?

**Comment by maskaravivek** [comment]
As mentioned in #2286, the image picker lets you choose only local images. Supporting other galleries(like google photos, drive etc.) means that we need to enforce the limit on the number of images that can be uploaded at one go on our own. 

One suggestion is to have this check in the 1st step of the upload flow itself. If the user has selected more than 5 images, he will need to remove the extra ones before proceeding. 

The top bar can have a close icon to remove an image before proceeding. The user can simply remove any image before proceeding.

**Comment by ilgazer** [comment]
>we need to enforce the limit on the number of images that can be uploaded at one go

Why does such a limit exist anyways?

**Comment by maskaravivek** [comment]
> > we need to enforce the limit on the number of images that can be uploaded at one go
> 
> Why does such a limit exist anyways?

Just so that anyone doesn't try to upload a lot of random images at once.

**Comment by ilgazer** [comment]
That's fair. Shouldn't be too hard to implement :)
