### ISSUE TITLE
Trying to add a depiction, existing depiction was removed

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#6068]
1. In Media Details I tried to add a depiction to a picture.
2. A "Please wait" dialog appeared.
3. After an hour, the dialog was still there.
4. Existing depiction had been removed: https://commons.m.wikimedia.org/w/index.php?title=File%3AWalk_around_Hatsudai_-33418.jpeg&diff=974361608&oldid=974152924

Reproducible every time

https://github.com/user-attachments/assets/7678fc4f-5288-46a2-a5ec-5d08f408b247

**Comment by parneet-guraya** [comment]
Yes, I can see the dialog being shown indefinitely. I found the request actually fails and the dialog isn't dismissed, guessing error is not propagated upwards properly. 

PR: #4725
> Adding two depictions, actually only adds one.

I just want to ask was this working before? because I see this PR mentioning above.  

Also, does this work in `betaDebug` for you? for me it fails
![photo_6291913921279410135_y](https://github.com/user-attachments/assets/01696222-cd1e-45b6-9967-0dc04e760e70)

**Comment by parneet-guraya** [comment]
> Yes, I can see the dialog being shown indefinitely. I found the request actually fails and the dialog isn't dismissed, guessing error is not propagated upwards properly.
> 
> PR: #4725
> 
> > Adding two depictions, actually only adds one.
> 
> I just want to ask was this working before? because I see this PR mentioning above.
> 
> Also, does this work in `betaDebug` for you? for me it fails ![photo_6291913921279410135_y](https://private-user-images.githubusercontent.com/111801812/398144907-01696222-cd1e-45b6-9967-0dc04e760e70.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTI4NDcsIm5iZiI6MTczNDk1MjU0NywicGF0aCI6Ii8xMTE4MDE4MTIvMzk4MTQ0OTA3LTAxNjk2MjIyLWNkMWUtNDViNi05OTY3LTBkYzA0ZTc2MGU3MC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxMTE1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODAzODM2MGUwMzIzY2MyMjc4ZDgzMGRkNTIyZDk0YTZmMjAxNWFiNDM2NGEwNDNkM2E3ODIxMTY0MzU5NjZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6Y-u2CL7DLMuKdCa7wObAJLXWRSC_Hdp1KUMG1AlrpE)

P.S: I know I have already picked up some issues [WIP]. Just saw this high priority issue, thought let's fix this first :)

**Comment by nicolas-raoul** [comment]
> Adding two depictions, actually only adds one

Thanks for finding that PR! There is a checkbox enabled in front of that item, so that means it has been fixed at that time.

> does this work in betaDebug for you?

It might work better in prodDebug.
To minimize disruption in production, could you please use [that image](https://commons.wikimedia.org/wiki/File:Walk_around_Hatsudai_-33175.jpeg)? You can put the depiction back using the website.

> high priority issue, thought let's fix this first :)

Yes that's OK since you are already kind of senior in this project, thanks a lot! :-)

**Comment by parneet-guraya** [comment]
This #5741 PR does this 
> Now: Two APIs are used to delete older depictions only and update with the new ones.

It was done because when editing depiction some other data was also getting deleted. So, it first deletes and then adds new ones including existing ones.

I switch to old way by just editing the depict only, it worked and this is the [change](https://commons.wikimedia.org/w/index.php?title=File%3AWalk_around_Hatsudai_-33175.jpeg&diff=974928318&oldid=974765737) introduced, does this still delete other data that the above PR aimed to fix? If not, we can revert back to that I guess?

![Screenshot from 2024-12-24 16-37-38](https://github.com/user-attachments/assets/3199dc6d-cf02-4a5c-a121-8fd7a7490d61)

Works as intended as it adds both existing and new one.

![photo_6291805305851461677_y](https://github.com/user-attachments/assets/8884b7dd-7816-4e24-83bf-dab5cc37dcd5)


From the issue reported (that the PR fixes) it included whole lot of changes but this here doesn't so it works now?

**Comment by nicolas-raoul** [comment]
I just tried on latest main, the problem still happens ("Please wait", depiction removed).

**Comment by parneet-guraya** [comment]
Sorry by "it works now" I meant when I tried by reverting  the workaround mentioned in the PR. So, I was wondering if the issue doesn't happen anymore. You cannot check it obviously, I was just trying to confirm by showing you the diff image that shows the changes in depiction.

**Comment by nicolas-raoul** [comment]
Understood thanks! :-)

**Comment by savsch** [comment]
Decided to take a look into the issue out of curiosity.
Some analysis reveals that the delete request succeeds, with a json response of the following form:
```
{
 // other fields snipped
  "success": 1
}
```
This request is made by `WikiBaseClient.kt`'s `postDeleteClaims`, which is invoked by the following code in `WikidataEditService`:
```

    @SuppressLint("CheckResult")
    fun updateDepictsProperty(
        fileEntityId: String?,
        depictedItems: List<String>
    ): Observable<Boolean> {
        val entityId: String = PAGE_ID_PREFIX + fileEntityId
        val claimIds = getDepictionsClaimIds(entityId)

        /* Please consider removeClaim scenario for BetaDebug */
        val data = RemoveClaim.from(if (isBetaFlavour) listOf("Q10") else claimIds)

        return wikiBaseClient.postDeleteClaims(entityId, gson.toJson(data))
            .doOnError { throwable: Throwable? ->
                Timber.e(
                    throwable,
                    "Error occurred while removing existing claims for DEPICTS property"
                )
                showLongToast(
                    context,
                    context.getString(R.string.wikidata_edit_failure)
                )
            }.switchMap { success: Boolean ->
                if (success) {
                    Timber.d("DEPICTS property was deleted successfully")
                    return@switchMap addDepictsProperty(fileEntityId!!, depictedItems)
                } else {
                    Timber.d("Unable to delete DEPICTS property")
                    return@switchMap Observable.empty<Boolean>()
                }
            }
    }
```
**The problem is that the value of `success` boolean is false even though the response clearly says `"success": 1`**, and `return@switchMap Observable.empty<Boolean>()` gets executed, instead of the intended `return@switchMap addDepictsProperty(fileEntityId!!, depictedItems)`.

Apparently, this occurs because the json response isn't correctly deserialized into the `MwPostResponse` object that `WikiBaseInterface::postDeleteClaims` returns, which in turn is then returned as `response.successVal == 1` inside ``WikiBaseClient::postDeleteClaims``.

> I switch to old way by just editing the depict only...
@parneet-guraya In my opinion, switching to the old way can be avoided if this deserialization can be taken care of (maybe by changing `WikiBaseInterface::postDeleteClaims` to return something other than `MwPostResponse` (which has a `successVal` int field, but no `success` field), or by using custom deserialization, or maybe with a more elegant solution).

---

Btw, to verify this behavior, the `if (success) {` above can be temporarily changed to `if (true) {`, which will make the app behave as intended.

**Comment by parneet-guraya** [comment]
@savsch Thankyou for your interest. Yes, I noticed that too and parsing issue is because we have property with name `successVal` rather than `success` so just a @SerializedName() annotation would be enough. 

The reason I was trying to revert to old way was because the mentioned PR did a workaround by deleting and then adding new one. I noticed that it doesn't happen anymore (or atleast I think it doesn't) so, I thought if this doesn't reproduce the issue (the said PR solves) why not make the request atomic instead of making two separate requests. 

Anyways, solutions seems to be very simple. I will keep this idea in backlog maybe when we refactor the client class then we can fix this. Thanks again :-)
