### ISSUE TITLE
Use vector icons for nearby-map markers

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#621]
Icon is currently a raster image, which can look blurry on phones with a high pixel density. Is it possible to replace it with an SVG icon?

![screenshot_20170715-093544](https://user-images.githubusercontent.com/6953323/28237495-484cc670-6941-11e7-94e0-61ab51ad4251.png)

**Comment by gupta-meghna64** [comment]
![image](https://user-images.githubusercontent.com/20908024/27623150-b43da152-5bf8-11e7-9495-c531f48fc95a.png)
@tobias47n9e  Is this vector image fine instead of the raster image that is currently being used for nearby-map markers ?
If so, can I work on this issue ?

**Comment by misaochan** [comment]
@gupta-meghna64 I can't answer your image question, will have to wait for @tobias47n9e or @neslihanturan for that. But absolutely, feel free to work on any issue here at all, and let us know if you need any help. :)

**Comment by neslihanturan** [comment]
Hi @gupta-meghna64 , thanks for your interest. I think we should definitely use vectors in our app. But it can be better if you can colourise the icon to our application blue. 

Plus, the file is a .png export, however it is suppose to be a .svg file to solve the problem. Otherwise same thing would happen again. Or, we can use .xml files with <vector> tags also.

I use inkscape software (free softwre) for vector editing if you need to find such software to change the colour. Please let us know for further questions:)

**Comment by akaita** [comment]
Hi guys, I thought I could help out with the project so I completed the task and created #775 .
I hope that is fine :)

**Comment by tobias47n9e** [comment]
Sorry missed the ping. I think black is fine for the icon if we can change the color in the code? That way we only need 1 SVG for day and night theme.

**Comment by tobias47n9e** [comment]
Although this issue can be about all the icons in the app, I added a screenshot of the main icon this task is about. Compared to the other mapbox GL map-features it is very pixelated on my phone.

**Comment by akaita** [comment]
Oh 💡, I see I misunderstood which icon you were referring to... 
Indeed, the one you refer to looks way worse (for some reason, there is only a mdpi version of it).

We will need a different svg for this one, mostly because of the shadow.
I'll check the best way to get this one done.

I will leave the #775 open, as it also seems to be relevant.

**Comment by akaita** [comment]
Created new PR with the proper change :)

**Comment by whym** [comment]
closed via #786
