### ISSUE TITLE
Make the app usable without login

### ISSUE THREAD

**Issue by tobias47n9e** [commons-app/apps-android-commons#629]
From the Vienna hackathon feedback session: People should at least be able to get a look and feel of the app before logging in. A lot of users will uninstall the app if they need an account just to look at the app.

Maybe only ask for the login at the first update. Example of this is Duolingo. You can do a lot in the app before it wants you to log in.

**Comment by misaochan** [comment]
I agree, but this can only be done once we have completely implemented a home screen that does not require loading the user's contributions. Either it checks for whether there are contributions and displays them if yes and otherwise displays something else (e.g. picture of the day), or a different main page is used entirely (e.g. Nearby).

**Comment by nicolas-raoul** [comment]
I agree, some people might even be reluctant to log in on mobile (ex: shared device), and only use the app for the Nearby map, and take pictures with their DLSR, and then upload using a desktop computer.

How about only asking for login details when the first upload actually happens?

**Comment by domdomegg** [comment]
Same as #1238, which was done in PR #1486
