### ISSUE TITLE
"Commons article" link in Nearby Places is never available

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#730]
The option to see the Commons page for a Nearby place is always greyed out for me. Does it show up for anyone else?

**Comment by oe-bayram** [comment]
Yes it shows up for me! The link only appears, if there is a category or a common article page for the Nearby place!

**Comment by misaochan** [comment]
@oe-bayram Thanks! It works as intended, then? :)

**Comment by oe-bayram** [comment]
@misaochan Then? Close the issue please :) 
We are a group of two students from Freie Universität Berlin and as a part of a Software Engineering course we want to contribute to this project by solving an issue or an enhancement. But it was very difficult to find an issue, because most of them have been already solved, but aren't marked as closed!
So now want to take the issue #591 and would be glad if we get it :)

**Comment by neslihanturan** [comment]
I wouldn't say most, but yes somethimes we miss closing them:) We will be very happy if you comment them as "should be closed" to lead us:)

**Comment by misaochan** [comment]
Yes, sorry about that @oe-bayram . The past few months have been a rather difficult time for our dev team. 

How involved/large does your contribution need to be, in order to be counted as course credit? Perhaps you could start a new issue of your own and people might suggest issues to you?
