### ISSUE TITLE
Replace ListView with RecyclerView

### ISSUE THREAD

**Issue by veyndan** [commons-app/apps-android-commons#743]
`ListView` is basically deprecated and as we move to the future, `RecyclerView` should be used instead.

**Comment by psh** [comment]
Couple of things of note:

* Nearby will be a lot easier to jump into - it's just a single linear list of known `Place` objects
* There is no simple analog of the `CursorAdapter` in the world of RecyclerViews. This means there is a bunch of _implied_ functionality behind the `Contribution` list view due to the ability to observe changed values out of the content provider.
* There is a nice (rich) model object hiding in the code waiting to be extracted. Doing so should reduce coupling of classes & fix a memory leak (follow all the calls to get activity() & where it's getting used)
