### ISSUE TITLE
Peer review -  review the latest pictures uploaded by other people

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#780]
Let's say Joe is in the train with 30 minutes to kill, and he has already uploaded all of his interesting pictures. Joe could start playing a mobile game, but he prefers doing something for the greater good.

We should let Joe easily review the latest pictures uploaded by other people. Suggested user interface:
- The picture
- Good action buttons: Looks good, Send a public thank, Selfie, Copied from the Web, I don't know
- Some statistics about the author, and a browser link to their talk page

Benefits:
- Give Joe something to do rather than upload less-interesting pictures
- Relieve some of the burden of the Commons reviewers.

We could experiment like this for now, but if they are too many positives we could wait for 2 or 3 people with the same opinion before marking the picture (in that case the marking would be done in the name of the second/third person)

If this is successful, we could also ask people to categorize pictures with no categories. These actions could be counted for gamification.

**Comment by misaochan** [comment]
This sounds really interesting! Is there already a framework in Commons that has those options? I know "thank" exists, but I haven't seen the others (I suppose "selfie" and "copied" can just use the nomination for deletion framework). If there isn't already a framework, I don't think we have the privileges to implement one server-side?

**Comment by nicolas-raoul** [comment]
For deletions I suggest copying the concept from https://commons.wikimedia.org/wiki/MediaWiki:Gadget-QuickDelete.js . It is a gadget that can be enabled in your Commons preferences, I use it a lot, here is how it looks like on the Web UI:
![screenshot from 2017-07-18 12-32-52](https://user-images.githubusercontent.com/99590/28299704-b984775e-6bb5-11e7-94a4-48a1582331a3.png)

I suggest doing it directly from the app (which is logged in), rather than server-side. The server-side (if needed) would only be for coordination (if needed). If the app selects relatively recent pictures randomly, and remembers what pictures the user has reviewed, then at first we might not need anything server-side (until we decide that we need to wait for several people's opinion, but that won't work unless we have many reviewers already, so going without first).

**Comment by hismaeel** [comment]
Hello! I have a proposal for GSOC that is related to this, but is a bit different. Sorry for being late
## Summary
The first time I got the app I thought the "Nearby" Tab showed in menu showed the **photos** taken by the people close to me, rather than the places nearby. I then thought it would be great if users could look at photos from others, and look at them by different criteria-Nearby, Relevant (explained below), location, Newest, etc. I think this can transform the app from a pictures repo to a photo sharing community.

## Screenshots and Explanation
I tried so hard to make a functioning design but really couldn't do so properly. The photos below are just intended to be a far representation. The numbering in red on the different elements are explained:

![1](https://user-images.githubusercontent.com/25305892/37318261-c429723c-2626-11e8-91ef-ae6a74755bd2.png)



1. The tab that shows the contributions of the user

2. The tab that shows the photos taken by other people (see next)


![2](https://user-images.githubusercontent.com/25305892/37318262-c55ad7c2-2626-11e8-81b0-07339ca589b3.png)

Since we have a proposal to allow users to search through commons repo, I think it can blend very well with this.


1. Filter/Categorize picture results (by location, Category, etc)

2. SearchView for searching Commons repo

3. Sort the photos by (in dropdown menu): Nearby, Relevant (can ask users first time for their interests, such as nature, cars, etc), Newest, Country---can think of more---. Note: this doesn't require you to search the repo, the "Nearby" will automatically be active, and whenever you come to this tab it will be automatically populated by photos from others based on Nearest photos first (change by selecting some other criteria from dropdown)

## Why this
So form the pic above, users can just swipe left to look at photos from other people. I think this is good because people can just come visit the app without a specific purpose in mind. Just maybe to look at photos from people in their neighborhood, or in different countries, or of their interest. I think this will make the app more functional and enjoyable. If they do come to the app with purpose of searching repo for something, can do so with the search view. 

## Peer Review?
I think that could be a great step, but sometimes users upload distasteful photos; we shouldn't have people go through the experience of looking at them. The photos shown should be only the ones approved :-)

Any thoughts? @nicolas-raoul  @misaochan

**Comment by nicolas-raoul** [comment]
@hismaeel Please copy-paste the above as a [new issue](https://github.com/commons-app/apps-android-commons/issues/new), as it is unrelated to peer review. Thanks!

**Comment by misaochan** [comment]
Hi @hismaeel ,

Thanks for the suggestion! Indeed many other people have mentioned having the same initial misconception of Nearby. :) We are hoping to alleviate that by creating a mini-tutorial about Nearby soon, but being able to view nearby pictures submitted by other people would still be nice. However, as @nicolas-raoul says, this is quite a different feature from Browse and so should have its own issue to discuss it further.

Regarding creating a whole new task for GSoC, from my perspective as the project maintainer that would be great, but as a mentor my main concern is that AFAIK you would need to find new mentors for this task. 2 mentors are needed for each task, and @maskaravivek , @neslihanturan , @nicolas-raoul and myself all already have our own tasks to mentor. I'm not sure how things would work in this regard - you might find yourself needing to find 2 mentors in a very short period of time. Perhaps @srish can clarify?

**Comment by srish** [comment]
@misaochan Yes, that's right! @hismaeel would need two mentors to proceed with this. As you all are packed right now with other projects, it does not seem feasible to move forward with this right now (unless we have a secret mailing list on which we could hunt for more app contributors as potential mentors). So, I would encourage @hismaeel to check out other ideas that we are showcasing:  http://mediawiki.org/wiki/Google_Summer_of_Code/2018 or contribute to the project as a volunteer :-)

**Comment by nicolas-raoul** [comment]
Queries that show the latest uploads by the app, they should be tested for performance and quality of the results:
- https://quarry.wmflabs.org/query/26940
- https://quarry.wmflabs.org/query/10587
- https://tools.wmflabs.org/catfood/catfood.php?category=Uploaded_with_Mobile/Android
- https://commons.wikimedia.org/wiki/User:Didym/Mobile_upload (probably fastest but painful to parse)
We should filter out the user's own uploads, either in the query or in the app.

**Comment by misaochan** [comment]
I think this is done. :)
