### ISSUE TITLE
Day mode by default

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#825]
Is it me or the default mode when first installed is night mode?

If yes, I would suggest making it day mode by default.
Most people probably use this app while outside, for which night mode is not the best.
In particular, the night-mode nearby map is unreadable in day light.

**Comment by neslihanturan** [comment]
I also prefer day mode frequently.

**Comment by misaochan** [comment]
Yeah the default mode is night mode. I'm good with changing it to day mode, if the majority agree. :)

**Comment by mebr1416** [comment]
Good day. I am looking into this.

**Comment by mebr1416** [comment]
Thank you @neslihanturan for your input.

**Comment by akaita** [comment]
Would it make sense to use the device's time to choose the default day/night mode?
Or even better, the light sensor?

**Comment by mebr1416** [comment]
Device's time would have to consider sunset time per season. So that would
have to be downloaded info that is stored per season per location. You know
that in the month of June there is about a week or more of no sunset in
Northern Sweden :)

The light sensor would make sense.

Overall, let's close this issue as it is and maybe reopen a new one with
your question. I feel the current options are sufficient.

B

**Comment by janpio** [comment]
The day/night mode is in reality more a "light UI/dark UI" mode. Different people prefer different colors, see Visual Studio (default light) vs. Visual Studio Code (default light).

**Comment by nicolas-raoul** [comment]
Thanks @mebr1416 ! :-)
