### ISSUE TITLE
Crash after taking pictures on devices before Android 5.0

### ISSUE THREAD

**Issue by neslihanturan** [commons-app/apps-android-commons#877]
You can reproduce this bug by click to save button (tick) after taking photo on before Android 5.0. Error says
 `java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{42992670 2928:com.android.gallery3d/u0a52} (pid=2928, uid=10052) that is not exported from uid 10151`

**Comment by Bluesir9** [comment]
By any chance, was the app running on a Stock Android device or was it a Xiaomi/OPPO/Huawei/Letv etc.?

**Comment by neslihanturan** [comment]
I heard some inconsistencies about this bug, my test device was Lenovo, Android 4.0.2. I have sent the solution on PR #878 . At least it solved the situation on my device :). Here is the related SOF link https://stackoverflow.com/questions/24467696/android-file-provider-permission-denial/24467912

**Comment by Bluesir9** [comment]
Ah, haven't worked with a FileProvider before so that Security Exception straight up reminded me of the permission management systems in place in quite a few non stock android devices especially the ones I mentioned earlier.

The solution provided in the SO post makes sense. I followed the chain and found that the issue has been reported to google's issue tracker as well here -> https://issuetracker.google.com/issues/37005552. Unless reported otherwise, I think the changes made should fix the problem for all.
