### ISSUE TITLE
Kabyle localization

### ISSUE THREAD

**Issue by belkacem77** [commons-app/apps-android-commons#893]
As we just finished the kab localization of Wikimedia Mobile Apps and Commons Android App, would you like consider kabyle language within the next release of Wikipedia Android app?

Thank you
Regards

**Comment by janpio** [comment]
Here is some information on how translation of the Commons app is handled:
https://github.com/commons-app/apps-android-commons/wiki/Translating-the-app

**Comment by belkacem77** [comment]
Thanks @janpio

**Comment by whym** [comment]
It looks like your translations have been integrated to this repository since August. (Thanks for your help!)

https://github.com/commons-app/apps-android-commons/commits/master/app/src/main/res/values-kab/strings.xml

I believe we will have a release in the coming months, and Kabyle localization will be automatically incorporated.

**Comment by belkacem77** [comment]
Sorry to let this issue open!!!! I forgot it!!! Yeah it's integrated. And thank you again.
