### ISSUE TITLE
Image that is currently being uploaded switches constantly from image thumbnail to "empty thumbnail" in ContributionsActivity

### ISSUE THREAD

**Issue by misaochan** [commons-app/apps-android-commons#939]
It switches back and forth from the first screenshot to the second, back to the first, so on and so forth until the progress bar is complete and the image has completed uploading. Does anyone else get this issue? I tested with a real device running Android 7.0.

![flicker 1](https://user-images.githubusercontent.com/3611199/32433020-4e3a7e36-c325-11e7-935d-98697ada84c0.png)
![flicker 2](https://user-images.githubusercontent.com/3611199/32433028-50b821cc-c325-11e7-878e-505e049f6e99.png)

**Comment by neslihanturan** [comment]
Hmm, I tried on a real device 4.2.4, and this case didn't occurred. First it shows empty thumbnail, and after progress bar is done, it shows thumbnail. However empty thumbnail is flashing. So I think someone has better network connection (since I use VPN to access, thumbnail can becomes visible after all progress is completed ) would verify your bug report.

**Comment by nicolas-raoul** [comment]
Actually now the thumbnail is not shown until the picture is uploaded:

**Comment by neslihanturan** [comment]
Currently, it is only white. No flickering thumbnails exists.

**Comment by misaochan** [comment]
Yup, this is solved.
