### ISSUE TITLE
Google Code-In: Setup development environment and run tests

### ISSUE THREAD

**Issue by feelfreelinux** [commons-app/apps-android-commons#959]
- [Download Android Studio 3.0](https://developer.android.com/studio/index.html)
- [Install and configure git on your machine](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
- Create github account
- [Fork apps-android-commons repository on github](https://help.github.com/articles/fork-a-repo/)
- [Clone your fork into your local machine.](https://help.github.com/articles/cloning-a-repository/)
- Import your freshly cloned repository into Android Studio. This might take a while.
- Try to build and run app on your android device / emulator.
- In console run `./gradlew clean check connectedCheck jacocoTestReport --stacktrace
` to execute unit tests.
- Provide results of your tests, and screenshot of running instance. If any of unit tests are failing please document it in this issue.

Feel free to contact us if you have any problems.

**Comment by feelfreelinux** [comment]
@nicolas-raoul I've added this as beginner task on GCI dashboard, let me know if this suits you

**Comment by nicolas-raoul** [comment]
While this does not add immediate new features to the app, it is a good exercise, don't hesitate to improve our wiki (do you have write access to it?) based on the difficulties they encounter, thanks a lot! :-)

**Comment by singh-anmol** [comment]
-GCI 2017-

Hello,
I am encountering build errors while running tests in Android Studio.
Simply running the app in emulator works. Only the command provide in GCI dashboard produces the error.
While test are running i can see some automated stuff happening in emulator like opening/closing of app (nearby) etc. (i also accepted some permission request)
sorry for the trouble, i'm new to android development.

Logs as requested -> https://pastebin.com/CshEhZva
![report](https://user-images.githubusercontent.com/34099939/33420370-4f5314ec-d5d4-11e7-8ab4-2425a6ccbfd2.png)
![report 2](https://user-images.githubusercontent.com/34099939/33420378-56115596-d5d4-11e7-8063-5c7d62e02f2c.png)

**Comment by nicolas-raoul** [comment]
@feelfreelinux I let you check and approve the task. Please note that the unit tests are currently broken, so the result obtained by Singh is probably expected.

**Comment by singh-anmol** [comment]
@nicolas-raoul Sir, should i submit the task for review with the above results then?

**Comment by nicolas-raoul** [comment]
Let's wait for @feelfreelinux 's evaluation.

**Comment by feelfreelinux** [comment]
@nicolas-raoul @singh-anmol I just ran unit tests on my machine, can confirm this issue. You can submit task on GCI dashboard, and I will accept it :) Need to add note in task description that tests are currently broken

**Comment by psh** [comment]
There's a PR (#990) that addresses the broken test.

**Comment by nicolas-raoul** [comment]
@feelfreelinux I would highly suggest that you modify the task description to something like "1. Build, 2. Run the unit tests, 3. Tell us whether the unit tests are passing or failing"

Advantages of adding the 3rd step:
- You don't have to modify the description every time the tests fail or get fixed.
- More importantly, it teaches the students that unit tests are a way to get informed, not a thing that you perform because someone told you do so. A common problem is people running unit tests religiously but actually not caring whether they pass or fail: we want to avoid teaching them to be like that.
- It is actually rather informative (even though the same information is available through Travis when Travis is not down). Students can feel that their work is more useful than the many tasks that provide us zero value such as "Connect to IRC".

Also, I suggest using the expression "unit tests are failing" rather than "unit tests are broken", as far as I can tell it seems to be the right terminology, even though casual usage might differ :-)

Cheers!

**Comment by misaochan** [comment]
Tests should hopefully be passing now, sorry about that guys!

I agree with Nicolas's suggestion for the 3rd step... the status of our tests can change fairly often.
