### ISSUE TITLE
Opt-in for event logging

### ISSUE THREAD

**Issue by nicolas-raoul** [commons-app/apps-android-commons#995]
> The app does not seem to provide a way for the user to opt out of event logging. Ideally this should be an opt-in selection that is provided during the initial onboarding workflow in the app.

Event logging meaning https://meta.wikimedia.org/w/index.php?title=Special%3APrefixIndex&prefix=MobileApp&namespace=470
Actually do we really need this logging at all?

**Comment by misaochan** [comment]
I was wondering about that - it's likely there because the original devs intended for some sort of analytics to be run (AFAIK WMF runs analytics on most of its projects?). I don't think we need it for the time being, but when we implement the Wikidata edits with Nearby we would need to log those (but that might not be related).

**Comment by dbrant** [comment]
Closing, since event logging was removed from the app.
